// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: nexusim/mcpgateway/v1/mcp_gateway_service.proto

package mcpgatewayv1

import (
	v1 "github.com/qsyy0921/IM/api/proto/nexusim/policy/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthContext) Reset() {
	*x = AuthContext{}
	mi := &file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthContext) ProtoMessage() {}

func (x *AuthContext) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthContext.ProtoReflect.Descriptor instead.
func (*AuthContext) Descriptor() ([]byte, []int) {
	return file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_rawDescGZIP(), []int{0}
}

func (x *AuthContext) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AuthContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthContext) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AuthContext) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AuthContext) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *AuthContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type PrepareToolCallRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AuthContext    *AuthContext           `protobuf:"bytes,1,opt,name=auth_context,json=authContext,proto3" json:"auth_context,omitempty"`
	SkillId        string                 `protobuf:"bytes,2,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	ToolName       string                 `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Action         v1.ToolAction          `protobuf:"varint,4,opt,name=action,proto3,enum=nexusim.policy.v1.ToolAction" json:"action,omitempty"`
	ResourceType   string                 `protobuf:"bytes,5,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId     string                 `protobuf:"bytes,6,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	RiskLevel      string                 `protobuf:"bytes,7,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	Intent         string                 `protobuf:"bytes,8,opt,name=intent,proto3" json:"intent,omitempty"`
	InputJson      string                 `protobuf:"bytes,9,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,10,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrepareToolCallRequest) Reset() {
	*x = PrepareToolCallRequest{}
	mi := &file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareToolCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareToolCallRequest) ProtoMessage() {}

func (x *PrepareToolCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareToolCallRequest.ProtoReflect.Descriptor instead.
func (*PrepareToolCallRequest) Descriptor() ([]byte, []int) {
	return file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_rawDescGZIP(), []int{1}
}

func (x *PrepareToolCallRequest) GetAuthContext() *AuthContext {
	if x != nil {
		return x.AuthContext
	}
	return nil
}

func (x *PrepareToolCallRequest) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *PrepareToolCallRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *PrepareToolCallRequest) GetAction() v1.ToolAction {
	if x != nil {
		return x.Action
	}
	return v1.ToolAction(0)
}

func (x *PrepareToolCallRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *PrepareToolCallRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *PrepareToolCallRequest) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *PrepareToolCallRequest) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

func (x *PrepareToolCallRequest) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

func (x *PrepareToolCallRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type PrepareToolCallResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TenantId          string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId            string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SkillId           string                 `protobuf:"bytes,3,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"`
	ToolName          string                 `protobuf:"bytes,4,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Action            v1.ToolAction          `protobuf:"varint,5,opt,name=action,proto3,enum=nexusim.policy.v1.ToolAction" json:"action,omitempty"`
	ResourceType      string                 `protobuf:"bytes,6,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId        string                 `protobuf:"bytes,7,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	RiskLevel         string                 `protobuf:"bytes,8,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	Allowed           bool                   `protobuf:"varint,9,opt,name=allowed,proto3" json:"allowed,omitempty"`
	RequiresApproval  bool                   `protobuf:"varint,10,opt,name=requires_approval,json=requiresApproval,proto3" json:"requires_approval,omitempty"`
	PermissionVersion int64                  `protobuf:"varint,11,opt,name=permission_version,json=permissionVersion,proto3" json:"permission_version,omitempty"`
	Classification    string                 `protobuf:"bytes,12,opt,name=classification,proto3" json:"classification,omitempty"`
	Reason            string                 `protobuf:"bytes,13,opt,name=reason,proto3" json:"reason,omitempty"`
	DecisionSource    string                 `protobuf:"bytes,14,opt,name=decision_source,json=decisionSource,proto3" json:"decision_source,omitempty"`
	AuditId           string                 `protobuf:"bytes,15,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PrepareToolCallResponse) Reset() {
	*x = PrepareToolCallResponse{}
	mi := &file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareToolCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareToolCallResponse) ProtoMessage() {}

func (x *PrepareToolCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareToolCallResponse.ProtoReflect.Descriptor instead.
func (*PrepareToolCallResponse) Descriptor() ([]byte, []int) {
	return file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_rawDescGZIP(), []int{2}
}

func (x *PrepareToolCallResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PrepareToolCallResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PrepareToolCallResponse) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

func (x *PrepareToolCallResponse) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *PrepareToolCallResponse) GetAction() v1.ToolAction {
	if x != nil {
		return x.Action
	}
	return v1.ToolAction(0)
}

func (x *PrepareToolCallResponse) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *PrepareToolCallResponse) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *PrepareToolCallResponse) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *PrepareToolCallResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *PrepareToolCallResponse) GetRequiresApproval() bool {
	if x != nil {
		return x.RequiresApproval
	}
	return false
}

func (x *PrepareToolCallResponse) GetPermissionVersion() int64 {
	if x != nil {
		return x.PermissionVersion
	}
	return 0
}

func (x *PrepareToolCallResponse) GetClassification() string {
	if x != nil {
		return x.Classification
	}
	return ""
}

func (x *PrepareToolCallResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PrepareToolCallResponse) GetDecisionSource() string {
	if x != nil {
		return x.DecisionSource
	}
	return ""
}

func (x *PrepareToolCallResponse) GetAuditId() string {
	if x != nil {
		return x.AuditId
	}
	return ""
}

var File_nexusim_mcpgateway_v1_mcp_gateway_service_proto protoreflect.FileDescriptor

const file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_rawDesc = "" +
	"\n" +
	"/nexusim/mcpgateway/v1/mcp_gateway_service.proto\x12\x15nexusim.mcpgateway.v1\x1a&nexusim/policy/v1/policy_service.proto\"\xb9\x01\n" +
	"\vAuthContext\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\"\x93\x03\n" +
	"\x16PrepareToolCallRequest\x12E\n" +
	"\fauth_context\x18\x01 \x01(\v2\".nexusim.mcpgateway.v1.AuthContextR\vauthContext\x12\x19\n" +
	"\bskill_id\x18\x02 \x01(\tR\askillId\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x125\n" +
	"\x06action\x18\x04 \x01(\x0e2\x1d.nexusim.policy.v1.ToolActionR\x06action\x12#\n" +
	"\rresource_type\x18\x05 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x06 \x01(\tR\n" +
	"resourceId\x12\x1d\n" +
	"\n" +
	"risk_level\x18\a \x01(\tR\triskLevel\x12\x16\n" +
	"\x06intent\x18\b \x01(\tR\x06intent\x12\x1d\n" +
	"\n" +
	"input_json\x18\t \x01(\tR\tinputJson\x12'\n" +
	"\x0fidempotency_key\x18\n" +
	" \x01(\tR\x0eidempotencyKey\"\x9d\x04\n" +
	"\x17PrepareToolCallResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bskill_id\x18\x03 \x01(\tR\askillId\x12\x1b\n" +
	"\ttool_name\x18\x04 \x01(\tR\btoolName\x125\n" +
	"\x06action\x18\x05 \x01(\x0e2\x1d.nexusim.policy.v1.ToolActionR\x06action\x12#\n" +
	"\rresource_type\x18\x06 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\a \x01(\tR\n" +
	"resourceId\x12\x1d\n" +
	"\n" +
	"risk_level\x18\b \x01(\tR\triskLevel\x12\x18\n" +
	"\aallowed\x18\t \x01(\bR\aallowed\x12+\n" +
	"\x11requires_approval\x18\n" +
	" \x01(\bR\x10requiresApproval\x12-\n" +
	"\x12permission_version\x18\v \x01(\x03R\x11permissionVersion\x12&\n" +
	"\x0eclassification\x18\f \x01(\tR\x0eclassification\x12\x16\n" +
	"\x06reason\x18\r \x01(\tR\x06reason\x12'\n" +
	"\x0fdecision_source\x18\x0e \x01(\tR\x0edecisionSource\x12\x19\n" +
	"\baudit_id\x18\x0f \x01(\tR\aauditId2\x85\x01\n" +
	"\x11MCPGatewayService\x12p\n" +
	"\x0fPrepareToolCall\x12-.nexusim.mcpgateway.v1.PrepareToolCallRequest\x1a..nexusim.mcpgateway.v1.PrepareToolCallResponseBEZCgithub.com/qsyy0921/IM/api/proto/nexusim/mcpgateway/v1;mcpgatewayv1b\x06proto3"

var (
	file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_rawDescOnce sync.Once
	file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_rawDescData []byte
)

func file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_rawDescGZIP() []byte {
	file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_rawDescOnce.Do(func() {
		file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_rawDesc), len(file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_rawDesc)))
	})
	return file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_rawDescData
}

var file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_goTypes = []any{
	(*AuthContext)(nil),             // 0: nexusim.mcpgateway.v1.AuthContext
	(*PrepareToolCallRequest)(nil),  // 1: nexusim.mcpgateway.v1.PrepareToolCallRequest
	(*PrepareToolCallResponse)(nil), // 2: nexusim.mcpgateway.v1.PrepareToolCallResponse
	(v1.ToolAction)(0),              // 3: nexusim.policy.v1.ToolAction
}
var file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_depIdxs = []int32{
	0, // 0: nexusim.mcpgateway.v1.PrepareToolCallRequest.auth_context:type_name -> nexusim.mcpgateway.v1.AuthContext
	3, // 1: nexusim.mcpgateway.v1.PrepareToolCallRequest.action:type_name -> nexusim.policy.v1.ToolAction
	3, // 2: nexusim.mcpgateway.v1.PrepareToolCallResponse.action:type_name -> nexusim.policy.v1.ToolAction
	1, // 3: nexusim.mcpgateway.v1.MCPGatewayService.PrepareToolCall:input_type -> nexusim.mcpgateway.v1.PrepareToolCallRequest
	2, // 4: nexusim.mcpgateway.v1.MCPGatewayService.PrepareToolCall:output_type -> nexusim.mcpgateway.v1.PrepareToolCallResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_init() }
func file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_init() {
	if File_nexusim_mcpgateway_v1_mcp_gateway_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_rawDesc), len(file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_goTypes,
		DependencyIndexes: file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_depIdxs,
		MessageInfos:      file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_msgTypes,
	}.Build()
	File_nexusim_mcpgateway_v1_mcp_gateway_service_proto = out.File
	file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_goTypes = nil
	file_nexusim_mcpgateway_v1_mcp_gateway_service_proto_depIdxs = nil
}
