// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: policy/v1/im.policy.events.proto

package policyeventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Topic: im.policy.events
// Partition key: tenant_id + ":" + stable conversation key.
// Producer: policy-service decision audit outbox relay.
type PolicyEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventId          string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType        string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventVersion     string                 `protobuf:"bytes,3,opt,name=event_version,json=eventVersion,proto3" json:"event_version,omitempty"`
	TenantId         string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AggregateType    string                 `protobuf:"bytes,5,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	AggregateId      string                 `protobuf:"bytes,6,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	AggregateVersion int64                  `protobuf:"varint,7,opt,name=aggregate_version,json=aggregateVersion,proto3" json:"aggregate_version,omitempty"`
	PartitionKey     string                 `protobuf:"bytes,8,opt,name=partition_key,json=partitionKey,proto3" json:"partition_key,omitempty"`
	MappingVersion   int64                  `protobuf:"varint,9,opt,name=mapping_version,json=mappingVersion,proto3" json:"mapping_version,omitempty"`
	TraceId          string                 `protobuf:"bytes,10,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	CorrelationId    string                 `protobuf:"bytes,11,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	CausationId      string                 `protobuf:"bytes,12,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	Producer         string                 `protobuf:"bytes,13,opt,name=producer,proto3" json:"producer,omitempty"`
	OccurredAt       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PolicyEvent_MessageActionDecision
	Payload       isPolicyEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyEvent) Reset() {
	*x = PolicyEvent{}
	mi := &file_policy_v1_im_policy_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyEvent) ProtoMessage() {}

func (x *PolicyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_im_policy_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyEvent.ProtoReflect.Descriptor instead.
func (*PolicyEvent) Descriptor() ([]byte, []int) {
	return file_policy_v1_im_policy_events_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PolicyEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PolicyEvent) GetEventVersion() string {
	if x != nil {
		return x.EventVersion
	}
	return ""
}

func (x *PolicyEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PolicyEvent) GetAggregateType() string {
	if x != nil {
		return x.AggregateType
	}
	return ""
}

func (x *PolicyEvent) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *PolicyEvent) GetAggregateVersion() int64 {
	if x != nil {
		return x.AggregateVersion
	}
	return 0
}

func (x *PolicyEvent) GetPartitionKey() string {
	if x != nil {
		return x.PartitionKey
	}
	return ""
}

func (x *PolicyEvent) GetMappingVersion() int64 {
	if x != nil {
		return x.MappingVersion
	}
	return 0
}

func (x *PolicyEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *PolicyEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *PolicyEvent) GetCausationId() string {
	if x != nil {
		return x.CausationId
	}
	return ""
}

func (x *PolicyEvent) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *PolicyEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *PolicyEvent) GetPayload() isPolicyEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PolicyEvent) GetMessageActionDecision() *PolicyMessageActionDecisionV1 {
	if x != nil {
		if x, ok := x.Payload.(*PolicyEvent_MessageActionDecision); ok {
			return x.MessageActionDecision
		}
	}
	return nil
}

type isPolicyEvent_Payload interface {
	isPolicyEvent_Payload()
}

type PolicyEvent_MessageActionDecision struct {
	MessageActionDecision *PolicyMessageActionDecisionV1 `protobuf:"bytes,20,opt,name=message_action_decision,json=messageActionDecision,proto3,oneof"`
}

func (*PolicyEvent_MessageActionDecision) isPolicyEvent_Payload() {}

type PolicyMessageActionDecisionV1 struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	TenantId                 string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ActorUserKey             string                 `protobuf:"bytes,2,opt,name=actor_user_key,json=actorUserKey,proto3" json:"actor_user_key,omitempty"`
	DeviceKey                string                 `protobuf:"bytes,3,opt,name=device_key,json=deviceKey,proto3" json:"device_key,omitempty"`
	ConversationKey          string                 `protobuf:"bytes,4,opt,name=conversation_key,json=conversationKey,proto3" json:"conversation_key,omitempty"`
	MessageKey               string                 `protobuf:"bytes,5,opt,name=message_key,json=messageKey,proto3" json:"message_key,omitempty"`
	Action                   string                 `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`
	MessageIdPresent         bool                   `protobuf:"varint,7,opt,name=message_id_present,json=messageIdPresent,proto3" json:"message_id_present,omitempty"`
	DirectPeerContextPresent bool                   `protobuf:"varint,8,opt,name=direct_peer_context_present,json=directPeerContextPresent,proto3" json:"direct_peer_context_present,omitempty"`
	DirectPeerKey            string                 `protobuf:"bytes,9,opt,name=direct_peer_key,json=directPeerKey,proto3" json:"direct_peer_key,omitempty"`
	Allowed                  bool                   `protobuf:"varint,10,opt,name=allowed,proto3" json:"allowed,omitempty"`
	PermissionVersion        int64                  `protobuf:"varint,11,opt,name=permission_version,json=permissionVersion,proto3" json:"permission_version,omitempty"`
	Classification           string                 `protobuf:"bytes,12,opt,name=classification,proto3" json:"classification,omitempty"`
	ReasonCode               string                 `protobuf:"bytes,13,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	DecidedAt                *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=decided_at,json=decidedAt,proto3" json:"decided_at,omitempty"`
	DecisionSource           string                 `protobuf:"bytes,15,opt,name=decision_source,json=decisionSource,proto3" json:"decision_source,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *PolicyMessageActionDecisionV1) Reset() {
	*x = PolicyMessageActionDecisionV1{}
	mi := &file_policy_v1_im_policy_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyMessageActionDecisionV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyMessageActionDecisionV1) ProtoMessage() {}

func (x *PolicyMessageActionDecisionV1) ProtoReflect() protoreflect.Message {
	mi := &file_policy_v1_im_policy_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyMessageActionDecisionV1.ProtoReflect.Descriptor instead.
func (*PolicyMessageActionDecisionV1) Descriptor() ([]byte, []int) {
	return file_policy_v1_im_policy_events_proto_rawDescGZIP(), []int{1}
}

func (x *PolicyMessageActionDecisionV1) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PolicyMessageActionDecisionV1) GetActorUserKey() string {
	if x != nil {
		return x.ActorUserKey
	}
	return ""
}

func (x *PolicyMessageActionDecisionV1) GetDeviceKey() string {
	if x != nil {
		return x.DeviceKey
	}
	return ""
}

func (x *PolicyMessageActionDecisionV1) GetConversationKey() string {
	if x != nil {
		return x.ConversationKey
	}
	return ""
}

func (x *PolicyMessageActionDecisionV1) GetMessageKey() string {
	if x != nil {
		return x.MessageKey
	}
	return ""
}

func (x *PolicyMessageActionDecisionV1) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PolicyMessageActionDecisionV1) GetMessageIdPresent() bool {
	if x != nil {
		return x.MessageIdPresent
	}
	return false
}

func (x *PolicyMessageActionDecisionV1) GetDirectPeerContextPresent() bool {
	if x != nil {
		return x.DirectPeerContextPresent
	}
	return false
}

func (x *PolicyMessageActionDecisionV1) GetDirectPeerKey() string {
	if x != nil {
		return x.DirectPeerKey
	}
	return ""
}

func (x *PolicyMessageActionDecisionV1) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *PolicyMessageActionDecisionV1) GetPermissionVersion() int64 {
	if x != nil {
		return x.PermissionVersion
	}
	return 0
}

func (x *PolicyMessageActionDecisionV1) GetClassification() string {
	if x != nil {
		return x.Classification
	}
	return ""
}

func (x *PolicyMessageActionDecisionV1) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *PolicyMessageActionDecisionV1) GetDecidedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DecidedAt
	}
	return nil
}

func (x *PolicyMessageActionDecisionV1) GetDecisionSource() string {
	if x != nil {
		return x.DecisionSource
	}
	return ""
}

var File_policy_v1_im_policy_events_proto protoreflect.FileDescriptor

const file_policy_v1_im_policy_events_proto_rawDesc = "" +
	"\n" +
	" policy/v1/im.policy.events.proto\x12\x18nexusim.policy.events.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x05\n" +
	"\vPolicyEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12#\n" +
	"\revent_version\x18\x03 \x01(\tR\feventVersion\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12%\n" +
	"\x0eaggregate_type\x18\x05 \x01(\tR\raggregateType\x12!\n" +
	"\faggregate_id\x18\x06 \x01(\tR\vaggregateId\x12+\n" +
	"\x11aggregate_version\x18\a \x01(\x03R\x10aggregateVersion\x12#\n" +
	"\rpartition_key\x18\b \x01(\tR\fpartitionKey\x12'\n" +
	"\x0fmapping_version\x18\t \x01(\x03R\x0emappingVersion\x12\x19\n" +
	"\btrace_id\x18\n" +
	" \x01(\tR\atraceId\x12%\n" +
	"\x0ecorrelation_id\x18\v \x01(\tR\rcorrelationId\x12!\n" +
	"\fcausation_id\x18\f \x01(\tR\vcausationId\x12\x1a\n" +
	"\bproducer\x18\r \x01(\tR\bproducer\x12;\n" +
	"\voccurred_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12q\n" +
	"\x17message_action_decision\x18\x14 \x01(\v27.nexusim.policy.events.v1.PolicyMessageActionDecisionV1H\x00R\x15messageActionDecisionB\t\n" +
	"\apayload\"\xf0\x04\n" +
	"\x1dPolicyMessageActionDecisionV1\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12$\n" +
	"\x0eactor_user_key\x18\x02 \x01(\tR\factorUserKey\x12\x1d\n" +
	"\n" +
	"device_key\x18\x03 \x01(\tR\tdeviceKey\x12)\n" +
	"\x10conversation_key\x18\x04 \x01(\tR\x0fconversationKey\x12\x1f\n" +
	"\vmessage_key\x18\x05 \x01(\tR\n" +
	"messageKey\x12\x16\n" +
	"\x06action\x18\x06 \x01(\tR\x06action\x12,\n" +
	"\x12message_id_present\x18\a \x01(\bR\x10messageIdPresent\x12=\n" +
	"\x1bdirect_peer_context_present\x18\b \x01(\bR\x18directPeerContextPresent\x12&\n" +
	"\x0fdirect_peer_key\x18\t \x01(\tR\rdirectPeerKey\x12\x18\n" +
	"\aallowed\x18\n" +
	" \x01(\bR\aallowed\x12-\n" +
	"\x12permission_version\x18\v \x01(\x03R\x11permissionVersion\x12&\n" +
	"\x0eclassification\x18\f \x01(\tR\x0eclassification\x12\x1f\n" +
	"\vreason_code\x18\r \x01(\tR\n" +
	"reasonCode\x129\n" +
	"\n" +
	"decided_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tdecidedAt\x12'\n" +
	"\x0fdecision_source\x18\x0f \x01(\tR\x0edecisionSourceB?Z=github.com/qsyy0921/IM/schemas/kafka/policy/v1;policyeventsv1b\x06proto3"

var (
	file_policy_v1_im_policy_events_proto_rawDescOnce sync.Once
	file_policy_v1_im_policy_events_proto_rawDescData []byte
)

func file_policy_v1_im_policy_events_proto_rawDescGZIP() []byte {
	file_policy_v1_im_policy_events_proto_rawDescOnce.Do(func() {
		file_policy_v1_im_policy_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_policy_v1_im_policy_events_proto_rawDesc), len(file_policy_v1_im_policy_events_proto_rawDesc)))
	})
	return file_policy_v1_im_policy_events_proto_rawDescData
}

var file_policy_v1_im_policy_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_policy_v1_im_policy_events_proto_goTypes = []any{
	(*PolicyEvent)(nil),                   // 0: nexusim.policy.events.v1.PolicyEvent
	(*PolicyMessageActionDecisionV1)(nil), // 1: nexusim.policy.events.v1.PolicyMessageActionDecisionV1
	(*timestamppb.Timestamp)(nil),         // 2: google.protobuf.Timestamp
}
var file_policy_v1_im_policy_events_proto_depIdxs = []int32{
	2, // 0: nexusim.policy.events.v1.PolicyEvent.occurred_at:type_name -> google.protobuf.Timestamp
	1, // 1: nexusim.policy.events.v1.PolicyEvent.message_action_decision:type_name -> nexusim.policy.events.v1.PolicyMessageActionDecisionV1
	2, // 2: nexusim.policy.events.v1.PolicyMessageActionDecisionV1.decided_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_policy_v1_im_policy_events_proto_init() }
func file_policy_v1_im_policy_events_proto_init() {
	if File_policy_v1_im_policy_events_proto != nil {
		return
	}
	file_policy_v1_im_policy_events_proto_msgTypes[0].OneofWrappers = []any{
		(*PolicyEvent_MessageActionDecision)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_policy_v1_im_policy_events_proto_rawDesc), len(file_policy_v1_im_policy_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_policy_v1_im_policy_events_proto_goTypes,
		DependencyIndexes: file_policy_v1_im_policy_events_proto_depIdxs,
		MessageInfos:      file_policy_v1_im_policy_events_proto_msgTypes,
	}.Build()
	File_policy_v1_im_policy_events_proto = out.File
	file_policy_v1_im_policy_events_proto_goTypes = nil
	file_policy_v1_im_policy_events_proto_depIdxs = nil
}
