global:
  resolve_timeout: 5m

route:
  receiver: local-null
  group_by:
    - alertname
    - service
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 4h

receivers:
  - name: local-null

templates: []
