name: nexusim-local

services:
  postgres:
    command:
      - postgres
      - -c
      - max_connections=${NEXUSIM_POSTGRES_MAX_CONNECTIONS:-600}
      - -c
      - shared_buffers=1GB
      - -c
      - effective_cache_size=8GB
      - -c
      - work_mem=16MB
      - -c
      - maintenance_work_mem=512MB
      - -c
      - wal_buffers=16MB
      - -c
      - max_wal_size=4GB
      - -c
      - checkpoint_timeout=15min
      - -c
      - checkpoint_completion_target=0.9
      - -c
      - autovacuum_vacuum_scale_factor=0.02
      - -c
      - autovacuum_analyze_scale_factor=0.02
      - -c
      - autovacuum_vacuum_threshold=1000
      - -c
      - autovacuum_analyze_threshold=1000
