apiVersion: 1

datasources:
  - name: NexusIM Prometheus
    type: prometheus
    access: proxy
    url: http://host.docker.internal:19091
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
