// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: nexusim/knowledge/v1/knowledge_ingestion_service.proto

package knowledgev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KnowledgeIngestionService_CreateKnowledgeSource_FullMethodName = "/nexusim.knowledge.v1.KnowledgeIngestionService/CreateKnowledgeSource"
	KnowledgeIngestionService_SubmitIngestionJob_FullMethodName    = "/nexusim.knowledge.v1.KnowledgeIngestionService/SubmitIngestionJob"
	KnowledgeIngestionService_GetIngestionJob_FullMethodName       = "/nexusim.knowledge.v1.KnowledgeIngestionService/GetIngestionJob"
	KnowledgeIngestionService_ListKnowledgeChunks_FullMethodName   = "/nexusim.knowledge.v1.KnowledgeIngestionService/ListKnowledgeChunks"
)

// KnowledgeIngestionServiceClient is the client API for KnowledgeIngestionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KnowledgeIngestionServiceClient interface {
	CreateKnowledgeSource(ctx context.Context, in *CreateKnowledgeSourceRequest, opts ...grpc.CallOption) (*CreateKnowledgeSourceResponse, error)
	SubmitIngestionJob(ctx context.Context, in *SubmitIngestionJobRequest, opts ...grpc.CallOption) (*SubmitIngestionJobResponse, error)
	GetIngestionJob(ctx context.Context, in *GetIngestionJobRequest, opts ...grpc.CallOption) (*GetIngestionJobResponse, error)
	ListKnowledgeChunks(ctx context.Context, in *ListKnowledgeChunksRequest, opts ...grpc.CallOption) (*ListKnowledgeChunksResponse, error)
}

type knowledgeIngestionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKnowledgeIngestionServiceClient(cc grpc.ClientConnInterface) KnowledgeIngestionServiceClient {
	return &knowledgeIngestionServiceClient{cc}
}

func (c *knowledgeIngestionServiceClient) CreateKnowledgeSource(ctx context.Context, in *CreateKnowledgeSourceRequest, opts ...grpc.CallOption) (*CreateKnowledgeSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKnowledgeSourceResponse)
	err := c.cc.Invoke(ctx, KnowledgeIngestionService_CreateKnowledgeSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeIngestionServiceClient) SubmitIngestionJob(ctx context.Context, in *SubmitIngestionJobRequest, opts ...grpc.CallOption) (*SubmitIngestionJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitIngestionJobResponse)
	err := c.cc.Invoke(ctx, KnowledgeIngestionService_SubmitIngestionJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeIngestionServiceClient) GetIngestionJob(ctx context.Context, in *GetIngestionJobRequest, opts ...grpc.CallOption) (*GetIngestionJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIngestionJobResponse)
	err := c.cc.Invoke(ctx, KnowledgeIngestionService_GetIngestionJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeIngestionServiceClient) ListKnowledgeChunks(ctx context.Context, in *ListKnowledgeChunksRequest, opts ...grpc.CallOption) (*ListKnowledgeChunksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListKnowledgeChunksResponse)
	err := c.cc.Invoke(ctx, KnowledgeIngestionService_ListKnowledgeChunks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KnowledgeIngestionServiceServer is the server API for KnowledgeIngestionService service.
// All implementations must embed UnimplementedKnowledgeIngestionServiceServer
// for forward compatibility.
type KnowledgeIngestionServiceServer interface {
	CreateKnowledgeSource(context.Context, *CreateKnowledgeSourceRequest) (*CreateKnowledgeSourceResponse, error)
	SubmitIngestionJob(context.Context, *SubmitIngestionJobRequest) (*SubmitIngestionJobResponse, error)
	GetIngestionJob(context.Context, *GetIngestionJobRequest) (*GetIngestionJobResponse, error)
	ListKnowledgeChunks(context.Context, *ListKnowledgeChunksRequest) (*ListKnowledgeChunksResponse, error)
	mustEmbedUnimplementedKnowledgeIngestionServiceServer()
}

// UnimplementedKnowledgeIngestionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKnowledgeIngestionServiceServer struct{}

func (UnimplementedKnowledgeIngestionServiceServer) CreateKnowledgeSource(context.Context, *CreateKnowledgeSourceRequest) (*CreateKnowledgeSourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateKnowledgeSource not implemented")
}
func (UnimplementedKnowledgeIngestionServiceServer) SubmitIngestionJob(context.Context, *SubmitIngestionJobRequest) (*SubmitIngestionJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitIngestionJob not implemented")
}
func (UnimplementedKnowledgeIngestionServiceServer) GetIngestionJob(context.Context, *GetIngestionJobRequest) (*GetIngestionJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIngestionJob not implemented")
}
func (UnimplementedKnowledgeIngestionServiceServer) ListKnowledgeChunks(context.Context, *ListKnowledgeChunksRequest) (*ListKnowledgeChunksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListKnowledgeChunks not implemented")
}
func (UnimplementedKnowledgeIngestionServiceServer) mustEmbedUnimplementedKnowledgeIngestionServiceServer() {
}
func (UnimplementedKnowledgeIngestionServiceServer) testEmbeddedByValue() {}

// UnsafeKnowledgeIngestionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KnowledgeIngestionServiceServer will
// result in compilation errors.
type UnsafeKnowledgeIngestionServiceServer interface {
	mustEmbedUnimplementedKnowledgeIngestionServiceServer()
}

func RegisterKnowledgeIngestionServiceServer(s grpc.ServiceRegistrar, srv KnowledgeIngestionServiceServer) {
	// If the following call panics, it indicates UnimplementedKnowledgeIngestionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KnowledgeIngestionService_ServiceDesc, srv)
}

func _KnowledgeIngestionService_CreateKnowledgeSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKnowledgeSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeIngestionServiceServer).CreateKnowledgeSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeIngestionService_CreateKnowledgeSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeIngestionServiceServer).CreateKnowledgeSource(ctx, req.(*CreateKnowledgeSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeIngestionService_SubmitIngestionJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitIngestionJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeIngestionServiceServer).SubmitIngestionJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeIngestionService_SubmitIngestionJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeIngestionServiceServer).SubmitIngestionJob(ctx, req.(*SubmitIngestionJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeIngestionService_GetIngestionJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIngestionJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeIngestionServiceServer).GetIngestionJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeIngestionService_GetIngestionJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeIngestionServiceServer).GetIngestionJob(ctx, req.(*GetIngestionJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeIngestionService_ListKnowledgeChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKnowledgeChunksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeIngestionServiceServer).ListKnowledgeChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeIngestionService_ListKnowledgeChunks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeIngestionServiceServer).ListKnowledgeChunks(ctx, req.(*ListKnowledgeChunksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KnowledgeIngestionService_ServiceDesc is the grpc.ServiceDesc for KnowledgeIngestionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KnowledgeIngestionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexusim.knowledge.v1.KnowledgeIngestionService",
	HandlerType: (*KnowledgeIngestionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateKnowledgeSource",
			Handler:    _KnowledgeIngestionService_CreateKnowledgeSource_Handler,
		},
		{
			MethodName: "SubmitIngestionJob",
			Handler:    _KnowledgeIngestionService_SubmitIngestionJob_Handler,
		},
		{
			MethodName: "GetIngestionJob",
			Handler:    _KnowledgeIngestionService_GetIngestionJob_Handler,
		},
		{
			MethodName: "ListKnowledgeChunks",
			Handler:    _KnowledgeIngestionService_ListKnowledgeChunks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nexusim/knowledge/v1/knowledge_ingestion_service.proto",
}
