// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: nexusim/receipt/v1/receipt_service.proto

package receiptv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReceiptVisibilityMode int32

const (
	ReceiptVisibilityMode_RECEIPT_VISIBILITY_MODE_UNSPECIFIED ReceiptVisibilityMode = 0
	ReceiptVisibilityMode_RECEIPT_VISIBILITY_MODE_DETAILED    ReceiptVisibilityMode = 1
	ReceiptVisibilityMode_RECEIPT_VISIBILITY_MODE_COUNT_ONLY  ReceiptVisibilityMode = 2
	ReceiptVisibilityMode_RECEIPT_VISIBILITY_MODE_HIDDEN      ReceiptVisibilityMode = 3
)

// Enum value maps for ReceiptVisibilityMode.
var (
	ReceiptVisibilityMode_name = map[int32]string{
		0: "RECEIPT_VISIBILITY_MODE_UNSPECIFIED",
		1: "RECEIPT_VISIBILITY_MODE_DETAILED",
		2: "RECEIPT_VISIBILITY_MODE_COUNT_ONLY",
		3: "RECEIPT_VISIBILITY_MODE_HIDDEN",
	}
	ReceiptVisibilityMode_value = map[string]int32{
		"RECEIPT_VISIBILITY_MODE_UNSPECIFIED": 0,
		"RECEIPT_VISIBILITY_MODE_DETAILED":    1,
		"RECEIPT_VISIBILITY_MODE_COUNT_ONLY":  2,
		"RECEIPT_VISIBILITY_MODE_HIDDEN":      3,
	}
)

func (x ReceiptVisibilityMode) Enum() *ReceiptVisibilityMode {
	p := new(ReceiptVisibilityMode)
	*p = x
	return p
}

func (x ReceiptVisibilityMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReceiptVisibilityMode) Descriptor() protoreflect.EnumDescriptor {
	return file_nexusim_receipt_v1_receipt_service_proto_enumTypes[0].Descriptor()
}

func (ReceiptVisibilityMode) Type() protoreflect.EnumType {
	return &file_nexusim_receipt_v1_receipt_service_proto_enumTypes[0]
}

func (x ReceiptVisibilityMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReceiptVisibilityMode.Descriptor instead.
func (ReceiptVisibilityMode) EnumDescriptor() ([]byte, []int) {
	return file_nexusim_receipt_v1_receipt_service_proto_rawDescGZIP(), []int{0}
}

type AuthContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthContext) Reset() {
	*x = AuthContext{}
	mi := &file_nexusim_receipt_v1_receipt_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthContext) ProtoMessage() {}

func (x *AuthContext) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_receipt_v1_receipt_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthContext.ProtoReflect.Descriptor instead.
func (*AuthContext) Descriptor() ([]byte, []int) {
	return file_nexusim_receipt_v1_receipt_service_proto_rawDescGZIP(), []int{0}
}

func (x *AuthContext) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AuthContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthContext) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AuthContext) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AuthContext) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *AuthContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type MarkReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AuthContext    *AuthContext           `protobuf:"bytes,1,opt,name=auth_context,json=authContext,proto3" json:"auth_context,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ReadSeq        int64                  `protobuf:"varint,3,opt,name=read_seq,json=readSeq,proto3" json:"read_seq,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkReadRequest) Reset() {
	*x = MarkReadRequest{}
	mi := &file_nexusim_receipt_v1_receipt_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadRequest) ProtoMessage() {}

func (x *MarkReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_receipt_v1_receipt_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadRequest.ProtoReflect.Descriptor instead.
func (*MarkReadRequest) Descriptor() ([]byte, []int) {
	return file_nexusim_receipt_v1_receipt_service_proto_rawDescGZIP(), []int{1}
}

func (x *MarkReadRequest) GetAuthContext() *AuthContext {
	if x != nil {
		return x.AuthContext
	}
	return nil
}

func (x *MarkReadRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MarkReadRequest) GetReadSeq() int64 {
	if x != nil {
		return x.ReadSeq
	}
	return 0
}

type MarkReadResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	LastReadSeq    int64                  `protobuf:"varint,4,opt,name=last_read_seq,json=lastReadSeq,proto3" json:"last_read_seq,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkReadResponse) Reset() {
	*x = MarkReadResponse{}
	mi := &file_nexusim_receipt_v1_receipt_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadResponse) ProtoMessage() {}

func (x *MarkReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_receipt_v1_receipt_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadResponse.ProtoReflect.Descriptor instead.
func (*MarkReadResponse) Descriptor() ([]byte, []int) {
	return file_nexusim_receipt_v1_receipt_service_proto_rawDescGZIP(), []int{2}
}

func (x *MarkReadResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *MarkReadResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MarkReadResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MarkReadResponse) GetLastReadSeq() int64 {
	if x != nil {
		return x.LastReadSeq
	}
	return 0
}

type GetReceiptStateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AuthContext     *AuthContext           `protobuf:"bytes,1,opt,name=auth_context,json=authContext,proto3" json:"auth_context,omitempty"`
	ConversationId  string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	MessageId       string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ConversationSeq int64                  `protobuf:"varint,4,opt,name=conversation_seq,json=conversationSeq,proto3" json:"conversation_seq,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetReceiptStateRequest) Reset() {
	*x = GetReceiptStateRequest{}
	mi := &file_nexusim_receipt_v1_receipt_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReceiptStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiptStateRequest) ProtoMessage() {}

func (x *GetReceiptStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_receipt_v1_receipt_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiptStateRequest.ProtoReflect.Descriptor instead.
func (*GetReceiptStateRequest) Descriptor() ([]byte, []int) {
	return file_nexusim_receipt_v1_receipt_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetReceiptStateRequest) GetAuthContext() *AuthContext {
	if x != nil {
		return x.AuthContext
	}
	return nil
}

func (x *GetReceiptStateRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetReceiptStateRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GetReceiptStateRequest) GetConversationSeq() int64 {
	if x != nil {
		return x.ConversationSeq
	}
	return 0
}

type ReceiptUserState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReceivedSeq      int64                  `protobuf:"varint,2,opt,name=received_seq,json=receivedSeq,proto3" json:"received_seq,omitempty"`
	ReceivedAtUnixMs int64                  `protobuf:"varint,3,opt,name=received_at_unix_ms,json=receivedAtUnixMs,proto3" json:"received_at_unix_ms,omitempty"`
	ReadSeq          int64                  `protobuf:"varint,4,opt,name=read_seq,json=readSeq,proto3" json:"read_seq,omitempty"`
	ReadAtUnixMs     int64                  `protobuf:"varint,5,opt,name=read_at_unix_ms,json=readAtUnixMs,proto3" json:"read_at_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReceiptUserState) Reset() {
	*x = ReceiptUserState{}
	mi := &file_nexusim_receipt_v1_receipt_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiptUserState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptUserState) ProtoMessage() {}

func (x *ReceiptUserState) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_receipt_v1_receipt_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptUserState.ProtoReflect.Descriptor instead.
func (*ReceiptUserState) Descriptor() ([]byte, []int) {
	return file_nexusim_receipt_v1_receipt_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReceiptUserState) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReceiptUserState) GetReceivedSeq() int64 {
	if x != nil {
		return x.ReceivedSeq
	}
	return 0
}

func (x *ReceiptUserState) GetReceivedAtUnixMs() int64 {
	if x != nil {
		return x.ReceivedAtUnixMs
	}
	return 0
}

func (x *ReceiptUserState) GetReadSeq() int64 {
	if x != nil {
		return x.ReadSeq
	}
	return 0
}

func (x *ReceiptUserState) GetReadAtUnixMs() int64 {
	if x != nil {
		return x.ReadAtUnixMs
	}
	return 0
}

type GetReceiptStateResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConversationId    string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ConversationSeq   int64                  `protobuf:"varint,2,opt,name=conversation_seq,json=conversationSeq,proto3" json:"conversation_seq,omitempty"`
	MessageId         string                 `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ReceivedUserCount int32                  `protobuf:"varint,4,opt,name=received_user_count,json=receivedUserCount,proto3" json:"received_user_count,omitempty"`
	ReadUserCount     int32                  `protobuf:"varint,5,opt,name=read_user_count,json=readUserCount,proto3" json:"read_user_count,omitempty"`
	VisibilityMode    ReceiptVisibilityMode  `protobuf:"varint,6,opt,name=visibility_mode,json=visibilityMode,proto3,enum=nexusim.receipt.v1.ReceiptVisibilityMode" json:"visibility_mode,omitempty"`
	Receivers         []*ReceiptUserState    `protobuf:"bytes,7,rep,name=receivers,proto3" json:"receivers,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetReceiptStateResponse) Reset() {
	*x = GetReceiptStateResponse{}
	mi := &file_nexusim_receipt_v1_receipt_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReceiptStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReceiptStateResponse) ProtoMessage() {}

func (x *GetReceiptStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_receipt_v1_receipt_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReceiptStateResponse.ProtoReflect.Descriptor instead.
func (*GetReceiptStateResponse) Descriptor() ([]byte, []int) {
	return file_nexusim_receipt_v1_receipt_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetReceiptStateResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetReceiptStateResponse) GetConversationSeq() int64 {
	if x != nil {
		return x.ConversationSeq
	}
	return 0
}

func (x *GetReceiptStateResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GetReceiptStateResponse) GetReceivedUserCount() int32 {
	if x != nil {
		return x.ReceivedUserCount
	}
	return 0
}

func (x *GetReceiptStateResponse) GetReadUserCount() int32 {
	if x != nil {
		return x.ReadUserCount
	}
	return 0
}

func (x *GetReceiptStateResponse) GetVisibilityMode() ReceiptVisibilityMode {
	if x != nil {
		return x.VisibilityMode
	}
	return ReceiptVisibilityMode_RECEIPT_VISIBILITY_MODE_UNSPECIFIED
}

func (x *GetReceiptStateResponse) GetReceivers() []*ReceiptUserState {
	if x != nil {
		return x.Receivers
	}
	return nil
}

type ListConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthContext   *AuthContext           `protobuf:"bytes,1,opt,name=auth_context,json=authContext,proto3" json:"auth_context,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	PageCursor    string                 `protobuf:"bytes,3,opt,name=page_cursor,json=pageCursor,proto3" json:"page_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsRequest) Reset() {
	*x = ListConversationsRequest{}
	mi := &file_nexusim_receipt_v1_receipt_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsRequest) ProtoMessage() {}

func (x *ListConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_receipt_v1_receipt_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsRequest.ProtoReflect.Descriptor instead.
func (*ListConversationsRequest) Descriptor() ([]byte, []int) {
	return file_nexusim_receipt_v1_receipt_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListConversationsRequest) GetAuthContext() *AuthContext {
	if x != nil {
		return x.AuthContext
	}
	return nil
}

func (x *ListConversationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListConversationsRequest) GetPageCursor() string {
	if x != nil {
		return x.PageCursor
	}
	return ""
}

type ProjectionWatermark struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Source          string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	OffsetValue     int64                  `protobuf:"varint,2,opt,name=offset_value,json=offsetValue,proto3" json:"offset_value,omitempty"`
	UpdatedAtUnixMs int64                  `protobuf:"varint,3,opt,name=updated_at_unix_ms,json=updatedAtUnixMs,proto3" json:"updated_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProjectionWatermark) Reset() {
	*x = ProjectionWatermark{}
	mi := &file_nexusim_receipt_v1_receipt_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectionWatermark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectionWatermark) ProtoMessage() {}

func (x *ProjectionWatermark) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_receipt_v1_receipt_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectionWatermark.ProtoReflect.Descriptor instead.
func (*ProjectionWatermark) Descriptor() ([]byte, []int) {
	return file_nexusim_receipt_v1_receipt_service_proto_rawDescGZIP(), []int{7}
}

func (x *ProjectionWatermark) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ProjectionWatermark) GetOffsetValue() int64 {
	if x != nil {
		return x.OffsetValue
	}
	return 0
}

func (x *ProjectionWatermark) GetUpdatedAtUnixMs() int64 {
	if x != nil {
		return x.UpdatedAtUnixMs
	}
	return 0
}

type ConversationSummary struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ConversationId      string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	LastVisibleSeq      int64                  `protobuf:"varint,2,opt,name=last_visible_seq,json=lastVisibleSeq,proto3" json:"last_visible_seq,omitempty"`
	LastMessageId       string                 `protobuf:"bytes,3,opt,name=last_message_id,json=lastMessageId,proto3" json:"last_message_id,omitempty"`
	LastSenderId        string                 `protobuf:"bytes,4,opt,name=last_sender_id,json=lastSenderId,proto3" json:"last_sender_id,omitempty"`
	UnreadCount         int64                  `protobuf:"varint,5,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	LastReadSeq         int64                  `protobuf:"varint,6,opt,name=last_read_seq,json=lastReadSeq,proto3" json:"last_read_seq,omitempty"`
	UpdatedAtUnixMs     int64                  `protobuf:"varint,7,opt,name=updated_at_unix_ms,json=updatedAtUnixMs,proto3" json:"updated_at_unix_ms,omitempty"`
	LastSourceEventType string                 `protobuf:"bytes,8,opt,name=last_source_event_type,json=lastSourceEventType,proto3" json:"last_source_event_type,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConversationSummary) Reset() {
	*x = ConversationSummary{}
	mi := &file_nexusim_receipt_v1_receipt_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationSummary) ProtoMessage() {}

func (x *ConversationSummary) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_receipt_v1_receipt_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationSummary.ProtoReflect.Descriptor instead.
func (*ConversationSummary) Descriptor() ([]byte, []int) {
	return file_nexusim_receipt_v1_receipt_service_proto_rawDescGZIP(), []int{8}
}

func (x *ConversationSummary) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationSummary) GetLastVisibleSeq() int64 {
	if x != nil {
		return x.LastVisibleSeq
	}
	return 0
}

func (x *ConversationSummary) GetLastMessageId() string {
	if x != nil {
		return x.LastMessageId
	}
	return ""
}

func (x *ConversationSummary) GetLastSenderId() string {
	if x != nil {
		return x.LastSenderId
	}
	return ""
}

func (x *ConversationSummary) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *ConversationSummary) GetLastReadSeq() int64 {
	if x != nil {
		return x.LastReadSeq
	}
	return 0
}

func (x *ConversationSummary) GetUpdatedAtUnixMs() int64 {
	if x != nil {
		return x.UpdatedAtUnixMs
	}
	return 0
}

func (x *ConversationSummary) GetLastSourceEventType() string {
	if x != nil {
		return x.LastSourceEventType
	}
	return ""
}

type ListConversationsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Items               []*ConversationSummary `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextPageCursor      string                 `protobuf:"bytes,2,opt,name=next_page_cursor,json=nextPageCursor,proto3" json:"next_page_cursor,omitempty"`
	ProjectionWatermark *ProjectionWatermark   `protobuf:"bytes,3,opt,name=projection_watermark,json=projectionWatermark,proto3" json:"projection_watermark,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListConversationsResponse) Reset() {
	*x = ListConversationsResponse{}
	mi := &file_nexusim_receipt_v1_receipt_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsResponse) ProtoMessage() {}

func (x *ListConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_receipt_v1_receipt_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsResponse.ProtoReflect.Descriptor instead.
func (*ListConversationsResponse) Descriptor() ([]byte, []int) {
	return file_nexusim_receipt_v1_receipt_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListConversationsResponse) GetItems() []*ConversationSummary {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListConversationsResponse) GetNextPageCursor() string {
	if x != nil {
		return x.NextPageCursor
	}
	return ""
}

func (x *ListConversationsResponse) GetProjectionWatermark() *ProjectionWatermark {
	if x != nil {
		return x.ProjectionWatermark
	}
	return nil
}

var File_nexusim_receipt_v1_receipt_service_proto protoreflect.FileDescriptor

const file_nexusim_receipt_v1_receipt_service_proto_rawDesc = "" +
	"\n" +
	"(nexusim/receipt/v1/receipt_service.proto\x12\x12nexusim.receipt.v1\"\xb9\x01\n" +
	"\vAuthContext\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\"\x99\x01\n" +
	"\x0fMarkReadRequest\x12B\n" +
	"\fauth_context\x18\x01 \x01(\v2\x1f.nexusim.receipt.v1.AuthContextR\vauthContext\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x19\n" +
	"\bread_seq\x18\x03 \x01(\x03R\areadSeq\"\x95\x01\n" +
	"\x10MarkReadResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\tR\x0econversationId\x12\"\n" +
	"\rlast_read_seq\x18\x04 \x01(\x03R\vlastReadSeq\"\xcf\x01\n" +
	"\x16GetReceiptStateRequest\x12B\n" +
	"\fauth_context\x18\x01 \x01(\v2\x1f.nexusim.receipt.v1.AuthContextR\vauthContext\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12)\n" +
	"\x10conversation_seq\x18\x04 \x01(\x03R\x0fconversationSeq\"\xbf\x01\n" +
	"\x10ReceiptUserState\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\freceived_seq\x18\x02 \x01(\x03R\vreceivedSeq\x12-\n" +
	"\x13received_at_unix_ms\x18\x03 \x01(\x03R\x10receivedAtUnixMs\x12\x19\n" +
	"\bread_seq\x18\x04 \x01(\x03R\areadSeq\x12%\n" +
	"\x0fread_at_unix_ms\x18\x05 \x01(\x03R\freadAtUnixMs\"\xfc\x02\n" +
	"\x17GetReceiptStateResponse\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12)\n" +
	"\x10conversation_seq\x18\x02 \x01(\x03R\x0fconversationSeq\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12.\n" +
	"\x13received_user_count\x18\x04 \x01(\x05R\x11receivedUserCount\x12&\n" +
	"\x0fread_user_count\x18\x05 \x01(\x05R\rreadUserCount\x12R\n" +
	"\x0fvisibility_mode\x18\x06 \x01(\x0e2).nexusim.receipt.v1.ReceiptVisibilityModeR\x0evisibilityMode\x12B\n" +
	"\treceivers\x18\a \x03(\v2$.nexusim.receipt.v1.ReceiptUserStateR\treceivers\"\x95\x01\n" +
	"\x18ListConversationsRequest\x12B\n" +
	"\fauth_context\x18\x01 \x01(\v2\x1f.nexusim.receipt.v1.AuthContextR\vauthContext\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vpage_cursor\x18\x03 \x01(\tR\n" +
	"pageCursor\"}\n" +
	"\x13ProjectionWatermark\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12!\n" +
	"\foffset_value\x18\x02 \x01(\x03R\voffsetValue\x12+\n" +
	"\x12updated_at_unix_ms\x18\x03 \x01(\x03R\x0fupdatedAtUnixMs\"\xdf\x02\n" +
	"\x13ConversationSummary\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12(\n" +
	"\x10last_visible_seq\x18\x02 \x01(\x03R\x0elastVisibleSeq\x12&\n" +
	"\x0flast_message_id\x18\x03 \x01(\tR\rlastMessageId\x12$\n" +
	"\x0elast_sender_id\x18\x04 \x01(\tR\flastSenderId\x12!\n" +
	"\funread_count\x18\x05 \x01(\x03R\vunreadCount\x12\"\n" +
	"\rlast_read_seq\x18\x06 \x01(\x03R\vlastReadSeq\x12+\n" +
	"\x12updated_at_unix_ms\x18\a \x01(\x03R\x0fupdatedAtUnixMs\x123\n" +
	"\x16last_source_event_type\x18\b \x01(\tR\x13lastSourceEventType\"\xe0\x01\n" +
	"\x19ListConversationsResponse\x12=\n" +
	"\x05items\x18\x01 \x03(\v2'.nexusim.receipt.v1.ConversationSummaryR\x05items\x12(\n" +
	"\x10next_page_cursor\x18\x02 \x01(\tR\x0enextPageCursor\x12Z\n" +
	"\x14projection_watermark\x18\x03 \x01(\v2'.nexusim.receipt.v1.ProjectionWatermarkR\x13projectionWatermark*\xb2\x01\n" +
	"\x15ReceiptVisibilityMode\x12'\n" +
	"#RECEIPT_VISIBILITY_MODE_UNSPECIFIED\x10\x00\x12$\n" +
	" RECEIPT_VISIBILITY_MODE_DETAILED\x10\x01\x12&\n" +
	"\"RECEIPT_VISIBILITY_MODE_COUNT_ONLY\x10\x02\x12\"\n" +
	"\x1eRECEIPT_VISIBILITY_MODE_HIDDEN\x10\x032\xc5\x02\n" +
	"\x0eReceiptService\x12U\n" +
	"\bMarkRead\x12#.nexusim.receipt.v1.MarkReadRequest\x1a$.nexusim.receipt.v1.MarkReadResponse\x12j\n" +
	"\x0fGetReceiptState\x12*.nexusim.receipt.v1.GetReceiptStateRequest\x1a+.nexusim.receipt.v1.GetReceiptStateResponse\x12p\n" +
	"\x11ListConversations\x12,.nexusim.receipt.v1.ListConversationsRequest\x1a-.nexusim.receipt.v1.ListConversationsResponseB?Z=github.com/qsyy0921/IM/api/proto/nexusim/receipt/v1;receiptv1b\x06proto3"

var (
	file_nexusim_receipt_v1_receipt_service_proto_rawDescOnce sync.Once
	file_nexusim_receipt_v1_receipt_service_proto_rawDescData []byte
)

func file_nexusim_receipt_v1_receipt_service_proto_rawDescGZIP() []byte {
	file_nexusim_receipt_v1_receipt_service_proto_rawDescOnce.Do(func() {
		file_nexusim_receipt_v1_receipt_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nexusim_receipt_v1_receipt_service_proto_rawDesc), len(file_nexusim_receipt_v1_receipt_service_proto_rawDesc)))
	})
	return file_nexusim_receipt_v1_receipt_service_proto_rawDescData
}

var file_nexusim_receipt_v1_receipt_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nexusim_receipt_v1_receipt_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_nexusim_receipt_v1_receipt_service_proto_goTypes = []any{
	(ReceiptVisibilityMode)(0),        // 0: nexusim.receipt.v1.ReceiptVisibilityMode
	(*AuthContext)(nil),               // 1: nexusim.receipt.v1.AuthContext
	(*MarkReadRequest)(nil),           // 2: nexusim.receipt.v1.MarkReadRequest
	(*MarkReadResponse)(nil),          // 3: nexusim.receipt.v1.MarkReadResponse
	(*GetReceiptStateRequest)(nil),    // 4: nexusim.receipt.v1.GetReceiptStateRequest
	(*ReceiptUserState)(nil),          // 5: nexusim.receipt.v1.ReceiptUserState
	(*GetReceiptStateResponse)(nil),   // 6: nexusim.receipt.v1.GetReceiptStateResponse
	(*ListConversationsRequest)(nil),  // 7: nexusim.receipt.v1.ListConversationsRequest
	(*ProjectionWatermark)(nil),       // 8: nexusim.receipt.v1.ProjectionWatermark
	(*ConversationSummary)(nil),       // 9: nexusim.receipt.v1.ConversationSummary
	(*ListConversationsResponse)(nil), // 10: nexusim.receipt.v1.ListConversationsResponse
}
var file_nexusim_receipt_v1_receipt_service_proto_depIdxs = []int32{
	1,  // 0: nexusim.receipt.v1.MarkReadRequest.auth_context:type_name -> nexusim.receipt.v1.AuthContext
	1,  // 1: nexusim.receipt.v1.GetReceiptStateRequest.auth_context:type_name -> nexusim.receipt.v1.AuthContext
	0,  // 2: nexusim.receipt.v1.GetReceiptStateResponse.visibility_mode:type_name -> nexusim.receipt.v1.ReceiptVisibilityMode
	5,  // 3: nexusim.receipt.v1.GetReceiptStateResponse.receivers:type_name -> nexusim.receipt.v1.ReceiptUserState
	1,  // 4: nexusim.receipt.v1.ListConversationsRequest.auth_context:type_name -> nexusim.receipt.v1.AuthContext
	9,  // 5: nexusim.receipt.v1.ListConversationsResponse.items:type_name -> nexusim.receipt.v1.ConversationSummary
	8,  // 6: nexusim.receipt.v1.ListConversationsResponse.projection_watermark:type_name -> nexusim.receipt.v1.ProjectionWatermark
	2,  // 7: nexusim.receipt.v1.ReceiptService.MarkRead:input_type -> nexusim.receipt.v1.MarkReadRequest
	4,  // 8: nexusim.receipt.v1.ReceiptService.GetReceiptState:input_type -> nexusim.receipt.v1.GetReceiptStateRequest
	7,  // 9: nexusim.receipt.v1.ReceiptService.ListConversations:input_type -> nexusim.receipt.v1.ListConversationsRequest
	3,  // 10: nexusim.receipt.v1.ReceiptService.MarkRead:output_type -> nexusim.receipt.v1.MarkReadResponse
	6,  // 11: nexusim.receipt.v1.ReceiptService.GetReceiptState:output_type -> nexusim.receipt.v1.GetReceiptStateResponse
	10, // 12: nexusim.receipt.v1.ReceiptService.ListConversations:output_type -> nexusim.receipt.v1.ListConversationsResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_nexusim_receipt_v1_receipt_service_proto_init() }
func file_nexusim_receipt_v1_receipt_service_proto_init() {
	if File_nexusim_receipt_v1_receipt_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nexusim_receipt_v1_receipt_service_proto_rawDesc), len(file_nexusim_receipt_v1_receipt_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nexusim_receipt_v1_receipt_service_proto_goTypes,
		DependencyIndexes: file_nexusim_receipt_v1_receipt_service_proto_depIdxs,
		EnumInfos:         file_nexusim_receipt_v1_receipt_service_proto_enumTypes,
		MessageInfos:      file_nexusim_receipt_v1_receipt_service_proto_msgTypes,
	}.Build()
	File_nexusim_receipt_v1_receipt_service_proto = out.File
	file_nexusim_receipt_v1_receipt_service_proto_goTypes = nil
	file_nexusim_receipt_v1_receipt_service_proto_depIdxs = nil
}
