// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: identity/v1/im.identity.events.proto

package identityeventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Topic: im.identity.events
// Partition key: tenant_id + ":" + user_id + ":" + device_id.
// Producer: identity-service outbox relay.
type IdentityEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventId          string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType        string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventVersion     string                 `protobuf:"bytes,3,opt,name=event_version,json=eventVersion,proto3" json:"event_version,omitempty"`
	TenantId         string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AggregateType    string                 `protobuf:"bytes,5,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	AggregateId      string                 `protobuf:"bytes,6,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	AggregateVersion int64                  `protobuf:"varint,7,opt,name=aggregate_version,json=aggregateVersion,proto3" json:"aggregate_version,omitempty"`
	PartitionKey     string                 `protobuf:"bytes,8,opt,name=partition_key,json=partitionKey,proto3" json:"partition_key,omitempty"`
	MappingVersion   int64                  `protobuf:"varint,9,opt,name=mapping_version,json=mappingVersion,proto3" json:"mapping_version,omitempty"`
	TraceId          string                 `protobuf:"bytes,10,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	CorrelationId    string                 `protobuf:"bytes,11,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	CausationId      string                 `protobuf:"bytes,12,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	Producer         string                 `protobuf:"bytes,13,opt,name=producer,proto3" json:"producer,omitempty"`
	OccurredAt       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*IdentityEvent_DeviceRevoked
	//	*IdentityEvent_SessionRevoked
	Payload       isIdentityEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityEvent) Reset() {
	*x = IdentityEvent{}
	mi := &file_identity_v1_im_identity_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityEvent) ProtoMessage() {}

func (x *IdentityEvent) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_im_identity_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityEvent.ProtoReflect.Descriptor instead.
func (*IdentityEvent) Descriptor() ([]byte, []int) {
	return file_identity_v1_im_identity_events_proto_rawDescGZIP(), []int{0}
}

func (x *IdentityEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *IdentityEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *IdentityEvent) GetEventVersion() string {
	if x != nil {
		return x.EventVersion
	}
	return ""
}

func (x *IdentityEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *IdentityEvent) GetAggregateType() string {
	if x != nil {
		return x.AggregateType
	}
	return ""
}

func (x *IdentityEvent) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *IdentityEvent) GetAggregateVersion() int64 {
	if x != nil {
		return x.AggregateVersion
	}
	return 0
}

func (x *IdentityEvent) GetPartitionKey() string {
	if x != nil {
		return x.PartitionKey
	}
	return ""
}

func (x *IdentityEvent) GetMappingVersion() int64 {
	if x != nil {
		return x.MappingVersion
	}
	return 0
}

func (x *IdentityEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *IdentityEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *IdentityEvent) GetCausationId() string {
	if x != nil {
		return x.CausationId
	}
	return ""
}

func (x *IdentityEvent) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *IdentityEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *IdentityEvent) GetPayload() isIdentityEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *IdentityEvent) GetDeviceRevoked() *IdentityDeviceRevokedV1 {
	if x != nil {
		if x, ok := x.Payload.(*IdentityEvent_DeviceRevoked); ok {
			return x.DeviceRevoked
		}
	}
	return nil
}

func (x *IdentityEvent) GetSessionRevoked() *IdentitySessionRevokedV1 {
	if x != nil {
		if x, ok := x.Payload.(*IdentityEvent_SessionRevoked); ok {
			return x.SessionRevoked
		}
	}
	return nil
}

type isIdentityEvent_Payload interface {
	isIdentityEvent_Payload()
}

type IdentityEvent_DeviceRevoked struct {
	DeviceRevoked *IdentityDeviceRevokedV1 `protobuf:"bytes,20,opt,name=device_revoked,json=deviceRevoked,proto3,oneof"`
}

type IdentityEvent_SessionRevoked struct {
	SessionRevoked *IdentitySessionRevokedV1 `protobuf:"bytes,21,opt,name=session_revoked,json=sessionRevoked,proto3,oneof"`
}

func (*IdentityEvent_DeviceRevoked) isIdentityEvent_Payload() {}

func (*IdentityEvent_SessionRevoked) isIdentityEvent_Payload() {}

type IdentityDeviceRevokedV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	RevokedBy     string                 `protobuf:"bytes,5,opt,name=revoked_by,json=revokedBy,proto3" json:"revoked_by,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	RevokedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityDeviceRevokedV1) Reset() {
	*x = IdentityDeviceRevokedV1{}
	mi := &file_identity_v1_im_identity_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityDeviceRevokedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityDeviceRevokedV1) ProtoMessage() {}

func (x *IdentityDeviceRevokedV1) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_im_identity_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityDeviceRevokedV1.ProtoReflect.Descriptor instead.
func (*IdentityDeviceRevokedV1) Descriptor() ([]byte, []int) {
	return file_identity_v1_im_identity_events_proto_rawDescGZIP(), []int{1}
}

func (x *IdentityDeviceRevokedV1) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *IdentityDeviceRevokedV1) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IdentityDeviceRevokedV1) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *IdentityDeviceRevokedV1) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IdentityDeviceRevokedV1) GetRevokedBy() string {
	if x != nil {
		return x.RevokedBy
	}
	return ""
}

func (x *IdentityDeviceRevokedV1) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *IdentityDeviceRevokedV1) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

type IdentitySessionRevokedV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	RevokedBy     string                 `protobuf:"bytes,6,opt,name=revoked_by,json=revokedBy,proto3" json:"revoked_by,omitempty"`
	Reason        string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	RevokedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentitySessionRevokedV1) Reset() {
	*x = IdentitySessionRevokedV1{}
	mi := &file_identity_v1_im_identity_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentitySessionRevokedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentitySessionRevokedV1) ProtoMessage() {}

func (x *IdentitySessionRevokedV1) ProtoReflect() protoreflect.Message {
	mi := &file_identity_v1_im_identity_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentitySessionRevokedV1.ProtoReflect.Descriptor instead.
func (*IdentitySessionRevokedV1) Descriptor() ([]byte, []int) {
	return file_identity_v1_im_identity_events_proto_rawDescGZIP(), []int{2}
}

func (x *IdentitySessionRevokedV1) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *IdentitySessionRevokedV1) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IdentitySessionRevokedV1) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *IdentitySessionRevokedV1) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *IdentitySessionRevokedV1) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IdentitySessionRevokedV1) GetRevokedBy() string {
	if x != nil {
		return x.RevokedBy
	}
	return ""
}

func (x *IdentitySessionRevokedV1) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *IdentitySessionRevokedV1) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

var File_identity_v1_im_identity_events_proto protoreflect.FileDescriptor

const file_identity_v1_im_identity_events_proto_rawDesc = "" +
	"\n" +
	"$identity/v1/im.identity.events.proto\x12\x1anexusim.identity.events.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd8\x05\n" +
	"\rIdentityEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12#\n" +
	"\revent_version\x18\x03 \x01(\tR\feventVersion\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12%\n" +
	"\x0eaggregate_type\x18\x05 \x01(\tR\raggregateType\x12!\n" +
	"\faggregate_id\x18\x06 \x01(\tR\vaggregateId\x12+\n" +
	"\x11aggregate_version\x18\a \x01(\x03R\x10aggregateVersion\x12#\n" +
	"\rpartition_key\x18\b \x01(\tR\fpartitionKey\x12'\n" +
	"\x0fmapping_version\x18\t \x01(\x03R\x0emappingVersion\x12\x19\n" +
	"\btrace_id\x18\n" +
	" \x01(\tR\atraceId\x12%\n" +
	"\x0ecorrelation_id\x18\v \x01(\tR\rcorrelationId\x12!\n" +
	"\fcausation_id\x18\f \x01(\tR\vcausationId\x12\x1a\n" +
	"\bproducer\x18\r \x01(\tR\bproducer\x12;\n" +
	"\voccurred_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\\\n" +
	"\x0edevice_revoked\x18\x14 \x01(\v23.nexusim.identity.events.v1.IdentityDeviceRevokedV1H\x00R\rdeviceRevoked\x12_\n" +
	"\x0fsession_revoked\x18\x15 \x01(\v24.nexusim.identity.events.v1.IdentitySessionRevokedV1H\x00R\x0esessionRevokedB\t\n" +
	"\apayload\"\xf6\x01\n" +
	"\x17IdentityDeviceRevokedV1\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"revoked_by\x18\x05 \x01(\tR\trevokedBy\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x129\n" +
	"\n" +
	"revoked_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\"\x96\x02\n" +
	"\x18IdentitySessionRevokedV1\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"revoked_by\x18\x06 \x01(\tR\trevokedBy\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x129\n" +
	"\n" +
	"revoked_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAtBCZAgithub.com/qsyy0921/IM/schemas/kafka/identity/v1;identityeventsv1b\x06proto3"

var (
	file_identity_v1_im_identity_events_proto_rawDescOnce sync.Once
	file_identity_v1_im_identity_events_proto_rawDescData []byte
)

func file_identity_v1_im_identity_events_proto_rawDescGZIP() []byte {
	file_identity_v1_im_identity_events_proto_rawDescOnce.Do(func() {
		file_identity_v1_im_identity_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_v1_im_identity_events_proto_rawDesc), len(file_identity_v1_im_identity_events_proto_rawDesc)))
	})
	return file_identity_v1_im_identity_events_proto_rawDescData
}

var file_identity_v1_im_identity_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_identity_v1_im_identity_events_proto_goTypes = []any{
	(*IdentityEvent)(nil),            // 0: nexusim.identity.events.v1.IdentityEvent
	(*IdentityDeviceRevokedV1)(nil),  // 1: nexusim.identity.events.v1.IdentityDeviceRevokedV1
	(*IdentitySessionRevokedV1)(nil), // 2: nexusim.identity.events.v1.IdentitySessionRevokedV1
	(*timestamppb.Timestamp)(nil),    // 3: google.protobuf.Timestamp
}
var file_identity_v1_im_identity_events_proto_depIdxs = []int32{
	3, // 0: nexusim.identity.events.v1.IdentityEvent.occurred_at:type_name -> google.protobuf.Timestamp
	1, // 1: nexusim.identity.events.v1.IdentityEvent.device_revoked:type_name -> nexusim.identity.events.v1.IdentityDeviceRevokedV1
	2, // 2: nexusim.identity.events.v1.IdentityEvent.session_revoked:type_name -> nexusim.identity.events.v1.IdentitySessionRevokedV1
	3, // 3: nexusim.identity.events.v1.IdentityDeviceRevokedV1.revoked_at:type_name -> google.protobuf.Timestamp
	3, // 4: nexusim.identity.events.v1.IdentitySessionRevokedV1.revoked_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_identity_v1_im_identity_events_proto_init() }
func file_identity_v1_im_identity_events_proto_init() {
	if File_identity_v1_im_identity_events_proto != nil {
		return
	}
	file_identity_v1_im_identity_events_proto_msgTypes[0].OneofWrappers = []any{
		(*IdentityEvent_DeviceRevoked)(nil),
		(*IdentityEvent_SessionRevoked)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_v1_im_identity_events_proto_rawDesc), len(file_identity_v1_im_identity_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_identity_v1_im_identity_events_proto_goTypes,
		DependencyIndexes: file_identity_v1_im_identity_events_proto_depIdxs,
		MessageInfos:      file_identity_v1_im_identity_events_proto_msgTypes,
	}.Build()
	File_identity_v1_im_identity_events_proto = out.File
	file_identity_v1_im_identity_events_proto_goTypes = nil
	file_identity_v1_im_identity_events_proto_depIdxs = nil
}
