// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: nexusim/conversation/v1/conversation_service.proto

package conversationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConversationMode int32

const (
	ConversationMode_CONVERSATION_MODE_UNSPECIFIED     ConversationMode = 0
	ConversationMode_CONVERSATION_MODE_LOCAL_ROW_LOCK  ConversationMode = 1
	ConversationMode_CONVERSATION_MODE_SEQUENCER_BLOCK ConversationMode = 2
)

// Enum value maps for ConversationMode.
var (
	ConversationMode_name = map[int32]string{
		0: "CONVERSATION_MODE_UNSPECIFIED",
		1: "CONVERSATION_MODE_LOCAL_ROW_LOCK",
		2: "CONVERSATION_MODE_SEQUENCER_BLOCK",
	}
	ConversationMode_value = map[string]int32{
		"CONVERSATION_MODE_UNSPECIFIED":     0,
		"CONVERSATION_MODE_LOCAL_ROW_LOCK":  1,
		"CONVERSATION_MODE_SEQUENCER_BLOCK": 2,
	}
)

func (x ConversationMode) Enum() *ConversationMode {
	p := new(ConversationMode)
	*p = x
	return p
}

func (x ConversationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConversationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_nexusim_conversation_v1_conversation_service_proto_enumTypes[0].Descriptor()
}

func (ConversationMode) Type() protoreflect.EnumType {
	return &file_nexusim_conversation_v1_conversation_service_proto_enumTypes[0]
}

func (x ConversationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConversationMode.Descriptor instead.
func (ConversationMode) EnumDescriptor() ([]byte, []int) {
	return file_nexusim_conversation_v1_conversation_service_proto_rawDescGZIP(), []int{0}
}

type FanoutMode int32

const (
	FanoutMode_FANOUT_MODE_UNSPECIFIED      FanoutMode = 0
	FanoutMode_FANOUT_MODE_WRITE_FANOUT     FanoutMode = 1
	FanoutMode_FANOUT_MODE_HYBRID_FANOUT    FanoutMode = 2
	FanoutMode_FANOUT_MODE_READ_FANOUT      FanoutMode = 3
	FanoutMode_FANOUT_MODE_BROADCAST_SIGNAL FanoutMode = 4
)

// Enum value maps for FanoutMode.
var (
	FanoutMode_name = map[int32]string{
		0: "FANOUT_MODE_UNSPECIFIED",
		1: "FANOUT_MODE_WRITE_FANOUT",
		2: "FANOUT_MODE_HYBRID_FANOUT",
		3: "FANOUT_MODE_READ_FANOUT",
		4: "FANOUT_MODE_BROADCAST_SIGNAL",
	}
	FanoutMode_value = map[string]int32{
		"FANOUT_MODE_UNSPECIFIED":      0,
		"FANOUT_MODE_WRITE_FANOUT":     1,
		"FANOUT_MODE_HYBRID_FANOUT":    2,
		"FANOUT_MODE_READ_FANOUT":      3,
		"FANOUT_MODE_BROADCAST_SIGNAL": 4,
	}
)

func (x FanoutMode) Enum() *FanoutMode {
	p := new(FanoutMode)
	*p = x
	return p
}

func (x FanoutMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FanoutMode) Descriptor() protoreflect.EnumDescriptor {
	return file_nexusim_conversation_v1_conversation_service_proto_enumTypes[1].Descriptor()
}

func (FanoutMode) Type() protoreflect.EnumType {
	return &file_nexusim_conversation_v1_conversation_service_proto_enumTypes[1]
}

func (x FanoutMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FanoutMode.Descriptor instead.
func (FanoutMode) EnumDescriptor() ([]byte, []int) {
	return file_nexusim_conversation_v1_conversation_service_proto_rawDescGZIP(), []int{1}
}

type GetSendContextRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TraceId        string                 `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSendContextRequest) Reset() {
	*x = GetSendContextRequest{}
	mi := &file_nexusim_conversation_v1_conversation_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSendContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSendContextRequest) ProtoMessage() {}

func (x *GetSendContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_conversation_v1_conversation_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSendContextRequest.ProtoReflect.Descriptor instead.
func (*GetSendContextRequest) Descriptor() ([]byte, []int) {
	return file_nexusim_conversation_v1_conversation_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetSendContextRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetSendContextRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetSendContextRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetSendContextRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type GetSendContextResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TenantId            string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ConversationId      string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	MemberVersion       int64                  `protobuf:"varint,3,opt,name=member_version,json=memberVersion,proto3" json:"member_version,omitempty"`
	PermissionVersion   int64                  `protobuf:"varint,4,opt,name=permission_version,json=permissionVersion,proto3" json:"permission_version,omitempty"`
	ConversationMode    ConversationMode       `protobuf:"varint,5,opt,name=conversation_mode,json=conversationMode,proto3,enum=nexusim.conversation.v1.ConversationMode" json:"conversation_mode,omitempty"`
	FanoutMode          FanoutMode             `protobuf:"varint,6,opt,name=fanout_mode,json=fanoutMode,proto3,enum=nexusim.conversation.v1.FanoutMode" json:"fanout_mode,omitempty"`
	FanoutPolicyVersion int64                  `protobuf:"varint,7,opt,name=fanout_policy_version,json=fanoutPolicyVersion,proto3" json:"fanout_policy_version,omitempty"`
	CurrentSeqShard     string                 `protobuf:"bytes,8,opt,name=current_seq_shard,json=currentSeqShard,proto3" json:"current_seq_shard,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetSendContextResponse) Reset() {
	*x = GetSendContextResponse{}
	mi := &file_nexusim_conversation_v1_conversation_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSendContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSendContextResponse) ProtoMessage() {}

func (x *GetSendContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_conversation_v1_conversation_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSendContextResponse.ProtoReflect.Descriptor instead.
func (*GetSendContextResponse) Descriptor() ([]byte, []int) {
	return file_nexusim_conversation_v1_conversation_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetSendContextResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetSendContextResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetSendContextResponse) GetMemberVersion() int64 {
	if x != nil {
		return x.MemberVersion
	}
	return 0
}

func (x *GetSendContextResponse) GetPermissionVersion() int64 {
	if x != nil {
		return x.PermissionVersion
	}
	return 0
}

func (x *GetSendContextResponse) GetConversationMode() ConversationMode {
	if x != nil {
		return x.ConversationMode
	}
	return ConversationMode_CONVERSATION_MODE_UNSPECIFIED
}

func (x *GetSendContextResponse) GetFanoutMode() FanoutMode {
	if x != nil {
		return x.FanoutMode
	}
	return FanoutMode_FANOUT_MODE_UNSPECIFIED
}

func (x *GetSendContextResponse) GetFanoutPolicyVersion() int64 {
	if x != nil {
		return x.FanoutPolicyVersion
	}
	return 0
}

func (x *GetSendContextResponse) GetCurrentSeqShard() string {
	if x != nil {
		return x.CurrentSeqShard
	}
	return ""
}

var File_nexusim_conversation_v1_conversation_service_proto protoreflect.FileDescriptor

const file_nexusim_conversation_v1_conversation_service_proto_rawDesc = "" +
	"\n" +
	"2nexusim/conversation/v1/conversation_service.proto\x12\x17nexusim.conversation.v1\"\x91\x01\n" +
	"\x15GetSendContextRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\"\xb2\x03\n" +
	"\x16GetSendContextResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12%\n" +
	"\x0emember_version\x18\x03 \x01(\x03R\rmemberVersion\x12-\n" +
	"\x12permission_version\x18\x04 \x01(\x03R\x11permissionVersion\x12V\n" +
	"\x11conversation_mode\x18\x05 \x01(\x0e2).nexusim.conversation.v1.ConversationModeR\x10conversationMode\x12D\n" +
	"\vfanout_mode\x18\x06 \x01(\x0e2#.nexusim.conversation.v1.FanoutModeR\n" +
	"fanoutMode\x122\n" +
	"\x15fanout_policy_version\x18\a \x01(\x03R\x13fanoutPolicyVersion\x12*\n" +
	"\x11current_seq_shard\x18\b \x01(\tR\x0fcurrentSeqShard*\x82\x01\n" +
	"\x10ConversationMode\x12!\n" +
	"\x1dCONVERSATION_MODE_UNSPECIFIED\x10\x00\x12$\n" +
	" CONVERSATION_MODE_LOCAL_ROW_LOCK\x10\x01\x12%\n" +
	"!CONVERSATION_MODE_SEQUENCER_BLOCK\x10\x02*\xa5\x01\n" +
	"\n" +
	"FanoutMode\x12\x1b\n" +
	"\x17FANOUT_MODE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18FANOUT_MODE_WRITE_FANOUT\x10\x01\x12\x1d\n" +
	"\x19FANOUT_MODE_HYBRID_FANOUT\x10\x02\x12\x1b\n" +
	"\x17FANOUT_MODE_READ_FANOUT\x10\x03\x12 \n" +
	"\x1cFANOUT_MODE_BROADCAST_SIGNAL\x10\x042\x88\x01\n" +
	"\x13ConversationService\x12q\n" +
	"\x0eGetSendContext\x12..nexusim.conversation.v1.GetSendContextRequest\x1a/.nexusim.conversation.v1.GetSendContextResponseBIZGgithub.com/qsyy0921/IM/api/proto/nexusim/conversation/v1;conversationv1b\x06proto3"

var (
	file_nexusim_conversation_v1_conversation_service_proto_rawDescOnce sync.Once
	file_nexusim_conversation_v1_conversation_service_proto_rawDescData []byte
)

func file_nexusim_conversation_v1_conversation_service_proto_rawDescGZIP() []byte {
	file_nexusim_conversation_v1_conversation_service_proto_rawDescOnce.Do(func() {
		file_nexusim_conversation_v1_conversation_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nexusim_conversation_v1_conversation_service_proto_rawDesc), len(file_nexusim_conversation_v1_conversation_service_proto_rawDesc)))
	})
	return file_nexusim_conversation_v1_conversation_service_proto_rawDescData
}

var file_nexusim_conversation_v1_conversation_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_nexusim_conversation_v1_conversation_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_nexusim_conversation_v1_conversation_service_proto_goTypes = []any{
	(ConversationMode)(0),          // 0: nexusim.conversation.v1.ConversationMode
	(FanoutMode)(0),                // 1: nexusim.conversation.v1.FanoutMode
	(*GetSendContextRequest)(nil),  // 2: nexusim.conversation.v1.GetSendContextRequest
	(*GetSendContextResponse)(nil), // 3: nexusim.conversation.v1.GetSendContextResponse
}
var file_nexusim_conversation_v1_conversation_service_proto_depIdxs = []int32{
	0, // 0: nexusim.conversation.v1.GetSendContextResponse.conversation_mode:type_name -> nexusim.conversation.v1.ConversationMode
	1, // 1: nexusim.conversation.v1.GetSendContextResponse.fanout_mode:type_name -> nexusim.conversation.v1.FanoutMode
	2, // 2: nexusim.conversation.v1.ConversationService.GetSendContext:input_type -> nexusim.conversation.v1.GetSendContextRequest
	3, // 3: nexusim.conversation.v1.ConversationService.GetSendContext:output_type -> nexusim.conversation.v1.GetSendContextResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_nexusim_conversation_v1_conversation_service_proto_init() }
func file_nexusim_conversation_v1_conversation_service_proto_init() {
	if File_nexusim_conversation_v1_conversation_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nexusim_conversation_v1_conversation_service_proto_rawDesc), len(file_nexusim_conversation_v1_conversation_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nexusim_conversation_v1_conversation_service_proto_goTypes,
		DependencyIndexes: file_nexusim_conversation_v1_conversation_service_proto_depIdxs,
		EnumInfos:         file_nexusim_conversation_v1_conversation_service_proto_enumTypes,
		MessageInfos:      file_nexusim_conversation_v1_conversation_service_proto_msgTypes,
	}.Build()
	File_nexusim_conversation_v1_conversation_service_proto = out.File
	file_nexusim_conversation_v1_conversation_service_proto_goTypes = nil
	file_nexusim_conversation_v1_conversation_service_proto_depIdxs = nil
}
