// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: conversation.timeline.events.proto

package conversationtimelinev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageDeleteScope int32

const (
	MessageDeleteScope_MESSAGE_DELETE_SCOPE_UNSPECIFIED          MessageDeleteScope = 0
	MessageDeleteScope_MESSAGE_DELETE_SCOPE_CONVERSATION_VIEW    MessageDeleteScope = 1
	MessageDeleteScope_MESSAGE_DELETE_SCOPE_COMPLIANCE_RETENTION MessageDeleteScope = 2
)

// Enum value maps for MessageDeleteScope.
var (
	MessageDeleteScope_name = map[int32]string{
		0: "MESSAGE_DELETE_SCOPE_UNSPECIFIED",
		1: "MESSAGE_DELETE_SCOPE_CONVERSATION_VIEW",
		2: "MESSAGE_DELETE_SCOPE_COMPLIANCE_RETENTION",
	}
	MessageDeleteScope_value = map[string]int32{
		"MESSAGE_DELETE_SCOPE_UNSPECIFIED":          0,
		"MESSAGE_DELETE_SCOPE_CONVERSATION_VIEW":    1,
		"MESSAGE_DELETE_SCOPE_COMPLIANCE_RETENTION": 2,
	}
)

func (x MessageDeleteScope) Enum() *MessageDeleteScope {
	p := new(MessageDeleteScope)
	*p = x
	return p
}

func (x MessageDeleteScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageDeleteScope) Descriptor() protoreflect.EnumDescriptor {
	return file_conversation_timeline_events_proto_enumTypes[0].Descriptor()
}

func (MessageDeleteScope) Type() protoreflect.EnumType {
	return &file_conversation_timeline_events_proto_enumTypes[0]
}

func (x MessageDeleteScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageDeleteScope.Descriptor instead.
func (MessageDeleteScope) EnumDescriptor() ([]byte, []int) {
	return file_conversation_timeline_events_proto_rawDescGZIP(), []int{0}
}

type ConversationMemberChangeType int32

const (
	ConversationMemberChangeType_CONVERSATION_MEMBER_CHANGE_TYPE_UNSPECIFIED  ConversationMemberChangeType = 0
	ConversationMemberChangeType_CONVERSATION_MEMBER_CHANGE_TYPE_JOIN         ConversationMemberChangeType = 1
	ConversationMemberChangeType_CONVERSATION_MEMBER_CHANGE_TYPE_LEAVE        ConversationMemberChangeType = 2
	ConversationMemberChangeType_CONVERSATION_MEMBER_CHANGE_TYPE_REMOVE       ConversationMemberChangeType = 3
	ConversationMemberChangeType_CONVERSATION_MEMBER_CHANGE_TYPE_ROLE_CHANGED ConversationMemberChangeType = 4
)

// Enum value maps for ConversationMemberChangeType.
var (
	ConversationMemberChangeType_name = map[int32]string{
		0: "CONVERSATION_MEMBER_CHANGE_TYPE_UNSPECIFIED",
		1: "CONVERSATION_MEMBER_CHANGE_TYPE_JOIN",
		2: "CONVERSATION_MEMBER_CHANGE_TYPE_LEAVE",
		3: "CONVERSATION_MEMBER_CHANGE_TYPE_REMOVE",
		4: "CONVERSATION_MEMBER_CHANGE_TYPE_ROLE_CHANGED",
	}
	ConversationMemberChangeType_value = map[string]int32{
		"CONVERSATION_MEMBER_CHANGE_TYPE_UNSPECIFIED":  0,
		"CONVERSATION_MEMBER_CHANGE_TYPE_JOIN":         1,
		"CONVERSATION_MEMBER_CHANGE_TYPE_LEAVE":        2,
		"CONVERSATION_MEMBER_CHANGE_TYPE_REMOVE":       3,
		"CONVERSATION_MEMBER_CHANGE_TYPE_ROLE_CHANGED": 4,
	}
)

func (x ConversationMemberChangeType) Enum() *ConversationMemberChangeType {
	p := new(ConversationMemberChangeType)
	*p = x
	return p
}

func (x ConversationMemberChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConversationMemberChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_conversation_timeline_events_proto_enumTypes[1].Descriptor()
}

func (ConversationMemberChangeType) Type() protoreflect.EnumType {
	return &file_conversation_timeline_events_proto_enumTypes[1]
}

func (x ConversationMemberChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConversationMemberChangeType.Descriptor instead.
func (ConversationMemberChangeType) EnumDescriptor() ([]byte, []int) {
	return file_conversation_timeline_events_proto_rawDescGZIP(), []int{1}
}

type ConversationMemberRole int32

const (
	ConversationMemberRole_CONVERSATION_MEMBER_ROLE_UNSPECIFIED ConversationMemberRole = 0
	ConversationMemberRole_CONVERSATION_MEMBER_ROLE_OWNER       ConversationMemberRole = 1
	ConversationMemberRole_CONVERSATION_MEMBER_ROLE_ADMIN       ConversationMemberRole = 2
	ConversationMemberRole_CONVERSATION_MEMBER_ROLE_MEMBER      ConversationMemberRole = 3
)

// Enum value maps for ConversationMemberRole.
var (
	ConversationMemberRole_name = map[int32]string{
		0: "CONVERSATION_MEMBER_ROLE_UNSPECIFIED",
		1: "CONVERSATION_MEMBER_ROLE_OWNER",
		2: "CONVERSATION_MEMBER_ROLE_ADMIN",
		3: "CONVERSATION_MEMBER_ROLE_MEMBER",
	}
	ConversationMemberRole_value = map[string]int32{
		"CONVERSATION_MEMBER_ROLE_UNSPECIFIED": 0,
		"CONVERSATION_MEMBER_ROLE_OWNER":       1,
		"CONVERSATION_MEMBER_ROLE_ADMIN":       2,
		"CONVERSATION_MEMBER_ROLE_MEMBER":      3,
	}
)

func (x ConversationMemberRole) Enum() *ConversationMemberRole {
	p := new(ConversationMemberRole)
	*p = x
	return p
}

func (x ConversationMemberRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConversationMemberRole) Descriptor() protoreflect.EnumDescriptor {
	return file_conversation_timeline_events_proto_enumTypes[2].Descriptor()
}

func (ConversationMemberRole) Type() protoreflect.EnumType {
	return &file_conversation_timeline_events_proto_enumTypes[2]
}

func (x ConversationMemberRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConversationMemberRole.Descriptor instead.
func (ConversationMemberRole) EnumDescriptor() ([]byte, []int) {
	return file_conversation_timeline_events_proto_rawDescGZIP(), []int{2}
}

type ConversationMemberStatus int32

const (
	ConversationMemberStatus_CONVERSATION_MEMBER_STATUS_UNSPECIFIED ConversationMemberStatus = 0
	ConversationMemberStatus_CONVERSATION_MEMBER_STATUS_ACTIVE      ConversationMemberStatus = 1
	ConversationMemberStatus_CONVERSATION_MEMBER_STATUS_LEFT        ConversationMemberStatus = 2
	ConversationMemberStatus_CONVERSATION_MEMBER_STATUS_BANNED      ConversationMemberStatus = 3
)

// Enum value maps for ConversationMemberStatus.
var (
	ConversationMemberStatus_name = map[int32]string{
		0: "CONVERSATION_MEMBER_STATUS_UNSPECIFIED",
		1: "CONVERSATION_MEMBER_STATUS_ACTIVE",
		2: "CONVERSATION_MEMBER_STATUS_LEFT",
		3: "CONVERSATION_MEMBER_STATUS_BANNED",
	}
	ConversationMemberStatus_value = map[string]int32{
		"CONVERSATION_MEMBER_STATUS_UNSPECIFIED": 0,
		"CONVERSATION_MEMBER_STATUS_ACTIVE":      1,
		"CONVERSATION_MEMBER_STATUS_LEFT":        2,
		"CONVERSATION_MEMBER_STATUS_BANNED":      3,
	}
)

func (x ConversationMemberStatus) Enum() *ConversationMemberStatus {
	p := new(ConversationMemberStatus)
	*p = x
	return p
}

func (x ConversationMemberStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConversationMemberStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_conversation_timeline_events_proto_enumTypes[3].Descriptor()
}

func (ConversationMemberStatus) Type() protoreflect.EnumType {
	return &file_conversation_timeline_events_proto_enumTypes[3]
}

func (x ConversationMemberStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConversationMemberStatus.Descriptor instead.
func (ConversationMemberStatus) EnumDescriptor() ([]byte, []int) {
	return file_conversation_timeline_events_proto_rawDescGZIP(), []int{3}
}

// Topic: conversation.timeline.events
// Partition key: tenant_id + ":" + conversation_id
// Ordering key: tenant_id + conversation_id + aggregate_version
// Producer: message-service outbox relay for first phase message events.
type ConversationTimelineEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventId          string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType        string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventVersion     string                 `protobuf:"bytes,3,opt,name=event_version,json=eventVersion,proto3" json:"event_version,omitempty"`
	TenantId         string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AggregateType    string                 `protobuf:"bytes,5,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`           // "conversation"
	AggregateId      string                 `protobuf:"bytes,6,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`                 // conversation_id
	AggregateVersion int64                  `protobuf:"varint,7,opt,name=aggregate_version,json=aggregateVersion,proto3" json:"aggregate_version,omitempty"` // conversation_seq
	PartitionKey     string                 `protobuf:"bytes,8,opt,name=partition_key,json=partitionKey,proto3" json:"partition_key,omitempty"`
	MappingVersion   string                 `protobuf:"bytes,9,opt,name=mapping_version,json=mappingVersion,proto3" json:"mapping_version,omitempty"`
	TraceId          string                 `protobuf:"bytes,10,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	CorrelationId    string                 `protobuf:"bytes,11,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	CausationId      string                 `protobuf:"bytes,12,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	Producer         string                 `protobuf:"bytes,13,opt,name=producer,proto3" json:"producer,omitempty"`
	OccurredAt       *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Metadata         *TimelineMetadata      `protobuf:"bytes,15,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ConversationTimelineEvent_MessagePersisted
	//	*ConversationTimelineEvent_MessageEdited
	//	*ConversationTimelineEvent_MessageRevoked
	//	*ConversationTimelineEvent_MessageDeleted
	//	*ConversationTimelineEvent_ConversationMemberJoined
	//	*ConversationTimelineEvent_ConversationMemberLeft
	//	*ConversationTimelineEvent_ConversationMemberRemoved
	//	*ConversationTimelineEvent_ConversationMemberRoleChanged
	//	*ConversationTimelineEvent_ConversationMemberBoundaryCancelled
	Payload       isConversationTimelineEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationTimelineEvent) Reset() {
	*x = ConversationTimelineEvent{}
	mi := &file_conversation_timeline_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationTimelineEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationTimelineEvent) ProtoMessage() {}

func (x *ConversationTimelineEvent) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_timeline_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationTimelineEvent.ProtoReflect.Descriptor instead.
func (*ConversationTimelineEvent) Descriptor() ([]byte, []int) {
	return file_conversation_timeline_events_proto_rawDescGZIP(), []int{0}
}

func (x *ConversationTimelineEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ConversationTimelineEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ConversationTimelineEvent) GetEventVersion() string {
	if x != nil {
		return x.EventVersion
	}
	return ""
}

func (x *ConversationTimelineEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ConversationTimelineEvent) GetAggregateType() string {
	if x != nil {
		return x.AggregateType
	}
	return ""
}

func (x *ConversationTimelineEvent) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *ConversationTimelineEvent) GetAggregateVersion() int64 {
	if x != nil {
		return x.AggregateVersion
	}
	return 0
}

func (x *ConversationTimelineEvent) GetPartitionKey() string {
	if x != nil {
		return x.PartitionKey
	}
	return ""
}

func (x *ConversationTimelineEvent) GetMappingVersion() string {
	if x != nil {
		return x.MappingVersion
	}
	return ""
}

func (x *ConversationTimelineEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ConversationTimelineEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ConversationTimelineEvent) GetCausationId() string {
	if x != nil {
		return x.CausationId
	}
	return ""
}

func (x *ConversationTimelineEvent) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *ConversationTimelineEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *ConversationTimelineEvent) GetMetadata() *TimelineMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ConversationTimelineEvent) GetPayload() isConversationTimelineEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ConversationTimelineEvent) GetMessagePersisted() *MessagePersistedV1 {
	if x != nil {
		if x, ok := x.Payload.(*ConversationTimelineEvent_MessagePersisted); ok {
			return x.MessagePersisted
		}
	}
	return nil
}

func (x *ConversationTimelineEvent) GetMessageEdited() *MessageEditedV1 {
	if x != nil {
		if x, ok := x.Payload.(*ConversationTimelineEvent_MessageEdited); ok {
			return x.MessageEdited
		}
	}
	return nil
}

func (x *ConversationTimelineEvent) GetMessageRevoked() *MessageRevokedV1 {
	if x != nil {
		if x, ok := x.Payload.(*ConversationTimelineEvent_MessageRevoked); ok {
			return x.MessageRevoked
		}
	}
	return nil
}

func (x *ConversationTimelineEvent) GetMessageDeleted() *MessageDeletedV1 {
	if x != nil {
		if x, ok := x.Payload.(*ConversationTimelineEvent_MessageDeleted); ok {
			return x.MessageDeleted
		}
	}
	return nil
}

func (x *ConversationTimelineEvent) GetConversationMemberJoined() *ConversationMemberJoinedV1 {
	if x != nil {
		if x, ok := x.Payload.(*ConversationTimelineEvent_ConversationMemberJoined); ok {
			return x.ConversationMemberJoined
		}
	}
	return nil
}

func (x *ConversationTimelineEvent) GetConversationMemberLeft() *ConversationMemberLeftV1 {
	if x != nil {
		if x, ok := x.Payload.(*ConversationTimelineEvent_ConversationMemberLeft); ok {
			return x.ConversationMemberLeft
		}
	}
	return nil
}

func (x *ConversationTimelineEvent) GetConversationMemberRemoved() *ConversationMemberRemovedV1 {
	if x != nil {
		if x, ok := x.Payload.(*ConversationTimelineEvent_ConversationMemberRemoved); ok {
			return x.ConversationMemberRemoved
		}
	}
	return nil
}

func (x *ConversationTimelineEvent) GetConversationMemberRoleChanged() *ConversationMemberRoleChangedV1 {
	if x != nil {
		if x, ok := x.Payload.(*ConversationTimelineEvent_ConversationMemberRoleChanged); ok {
			return x.ConversationMemberRoleChanged
		}
	}
	return nil
}

func (x *ConversationTimelineEvent) GetConversationMemberBoundaryCancelled() *ConversationMemberBoundaryCancelledV1 {
	if x != nil {
		if x, ok := x.Payload.(*ConversationTimelineEvent_ConversationMemberBoundaryCancelled); ok {
			return x.ConversationMemberBoundaryCancelled
		}
	}
	return nil
}

type isConversationTimelineEvent_Payload interface {
	isConversationTimelineEvent_Payload()
}

type ConversationTimelineEvent_MessagePersisted struct {
	MessagePersisted *MessagePersistedV1 `protobuf:"bytes,16,opt,name=message_persisted,json=messagePersisted,proto3,oneof"`
}

type ConversationTimelineEvent_MessageEdited struct {
	MessageEdited *MessageEditedV1 `protobuf:"bytes,17,opt,name=message_edited,json=messageEdited,proto3,oneof"`
}

type ConversationTimelineEvent_MessageRevoked struct {
	MessageRevoked *MessageRevokedV1 `protobuf:"bytes,18,opt,name=message_revoked,json=messageRevoked,proto3,oneof"`
}

type ConversationTimelineEvent_MessageDeleted struct {
	MessageDeleted *MessageDeletedV1 `protobuf:"bytes,19,opt,name=message_deleted,json=messageDeleted,proto3,oneof"`
}

type ConversationTimelineEvent_ConversationMemberJoined struct {
	ConversationMemberJoined *ConversationMemberJoinedV1 `protobuf:"bytes,20,opt,name=conversation_member_joined,json=conversationMemberJoined,proto3,oneof"`
}

type ConversationTimelineEvent_ConversationMemberLeft struct {
	ConversationMemberLeft *ConversationMemberLeftV1 `protobuf:"bytes,21,opt,name=conversation_member_left,json=conversationMemberLeft,proto3,oneof"`
}

type ConversationTimelineEvent_ConversationMemberRemoved struct {
	ConversationMemberRemoved *ConversationMemberRemovedV1 `protobuf:"bytes,22,opt,name=conversation_member_removed,json=conversationMemberRemoved,proto3,oneof"`
}

type ConversationTimelineEvent_ConversationMemberRoleChanged struct {
	ConversationMemberRoleChanged *ConversationMemberRoleChangedV1 `protobuf:"bytes,23,opt,name=conversation_member_role_changed,json=conversationMemberRoleChanged,proto3,oneof"`
}

type ConversationTimelineEvent_ConversationMemberBoundaryCancelled struct {
	ConversationMemberBoundaryCancelled *ConversationMemberBoundaryCancelledV1 `protobuf:"bytes,24,opt,name=conversation_member_boundary_cancelled,json=conversationMemberBoundaryCancelled,proto3,oneof"`
}

func (*ConversationTimelineEvent_MessagePersisted) isConversationTimelineEvent_Payload() {}

func (*ConversationTimelineEvent_MessageEdited) isConversationTimelineEvent_Payload() {}

func (*ConversationTimelineEvent_MessageRevoked) isConversationTimelineEvent_Payload() {}

func (*ConversationTimelineEvent_MessageDeleted) isConversationTimelineEvent_Payload() {}

func (*ConversationTimelineEvent_ConversationMemberJoined) isConversationTimelineEvent_Payload() {}

func (*ConversationTimelineEvent_ConversationMemberLeft) isConversationTimelineEvent_Payload() {}

func (*ConversationTimelineEvent_ConversationMemberRemoved) isConversationTimelineEvent_Payload() {}

func (*ConversationTimelineEvent_ConversationMemberRoleChanged) isConversationTimelineEvent_Payload() {
}

func (*ConversationTimelineEvent_ConversationMemberBoundaryCancelled) isConversationTimelineEvent_Payload() {
}

type TimelineMetadata struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	FanoutMode          string                 `protobuf:"bytes,1,opt,name=fanout_mode,json=fanoutMode,proto3" json:"fanout_mode,omitempty"`
	FanoutPolicyVersion int64                  `protobuf:"varint,2,opt,name=fanout_policy_version,json=fanoutPolicyVersion,proto3" json:"fanout_policy_version,omitempty"`
	PermissionVersion   int64                  `protobuf:"varint,3,opt,name=permission_version,json=permissionVersion,proto3" json:"permission_version,omitempty"`
	Classification      string                 `protobuf:"bytes,4,opt,name=classification,proto3" json:"classification,omitempty"`
	MappingVersion      string                 `protobuf:"bytes,5,opt,name=mapping_version,json=mappingVersion,proto3" json:"mapping_version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TimelineMetadata) Reset() {
	*x = TimelineMetadata{}
	mi := &file_conversation_timeline_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineMetadata) ProtoMessage() {}

func (x *TimelineMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_timeline_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineMetadata.ProtoReflect.Descriptor instead.
func (*TimelineMetadata) Descriptor() ([]byte, []int) {
	return file_conversation_timeline_events_proto_rawDescGZIP(), []int{1}
}

func (x *TimelineMetadata) GetFanoutMode() string {
	if x != nil {
		return x.FanoutMode
	}
	return ""
}

func (x *TimelineMetadata) GetFanoutPolicyVersion() int64 {
	if x != nil {
		return x.FanoutPolicyVersion
	}
	return 0
}

func (x *TimelineMetadata) GetPermissionVersion() int64 {
	if x != nil {
		return x.PermissionVersion
	}
	return 0
}

func (x *TimelineMetadata) GetClassification() string {
	if x != nil {
		return x.Classification
	}
	return ""
}

func (x *TimelineMetadata) GetMappingVersion() string {
	if x != nil {
		return x.MappingVersion
	}
	return ""
}

type MessagePersistedV1 struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageId       string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ConversationId  string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ConversationSeq int64                  `protobuf:"varint,3,opt,name=conversation_seq,json=conversationSeq,proto3" json:"conversation_seq,omitempty"`
	SenderId        string                 `protobuf:"bytes,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	DeviceId        string                 `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ClientMsgId     string                 `protobuf:"bytes,6,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	CommandHash     string                 `protobuf:"bytes,7,opt,name=command_hash,json=commandHash,proto3" json:"command_hash,omitempty"`
	MessageType     string                 `protobuf:"bytes,8,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Payload         *structpb.Struct       `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`
	AttachmentIds   []string               `protobuf:"bytes,10,rep,name=attachment_ids,json=attachmentIds,proto3" json:"attachment_ids,omitempty"`
	AcceptedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=accepted_at,json=acceptedAt,proto3" json:"accepted_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessagePersistedV1) Reset() {
	*x = MessagePersistedV1{}
	mi := &file_conversation_timeline_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagePersistedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePersistedV1) ProtoMessage() {}

func (x *MessagePersistedV1) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_timeline_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePersistedV1.ProtoReflect.Descriptor instead.
func (*MessagePersistedV1) Descriptor() ([]byte, []int) {
	return file_conversation_timeline_events_proto_rawDescGZIP(), []int{2}
}

func (x *MessagePersistedV1) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessagePersistedV1) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessagePersistedV1) GetConversationSeq() int64 {
	if x != nil {
		return x.ConversationSeq
	}
	return 0
}

func (x *MessagePersistedV1) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *MessagePersistedV1) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *MessagePersistedV1) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *MessagePersistedV1) GetCommandHash() string {
	if x != nil {
		return x.CommandHash
	}
	return ""
}

func (x *MessagePersistedV1) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *MessagePersistedV1) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MessagePersistedV1) GetAttachmentIds() []string {
	if x != nil {
		return x.AttachmentIds
	}
	return nil
}

func (x *MessagePersistedV1) GetAcceptedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AcceptedAt
	}
	return nil
}

type MessageEditedV1 struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageId       string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ConversationId  string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ConversationSeq int64                  `protobuf:"varint,3,opt,name=conversation_seq,json=conversationSeq,proto3" json:"conversation_seq,omitempty"`
	ChangeVersion   int32                  `protobuf:"varint,4,opt,name=change_version,json=changeVersion,proto3" json:"change_version,omitempty"`
	EditedBy        string                 `protobuf:"bytes,5,opt,name=edited_by,json=editedBy,proto3" json:"edited_by,omitempty"`
	BeforePayload   *structpb.Struct       `protobuf:"bytes,6,opt,name=before_payload,json=beforePayload,proto3" json:"before_payload,omitempty"`
	AfterPayload    *structpb.Struct       `protobuf:"bytes,7,opt,name=after_payload,json=afterPayload,proto3" json:"after_payload,omitempty"`
	Reason          string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	EditedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=edited_at,json=editedAt,proto3" json:"edited_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageEditedV1) Reset() {
	*x = MessageEditedV1{}
	mi := &file_conversation_timeline_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEditedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEditedV1) ProtoMessage() {}

func (x *MessageEditedV1) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_timeline_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEditedV1.ProtoReflect.Descriptor instead.
func (*MessageEditedV1) Descriptor() ([]byte, []int) {
	return file_conversation_timeline_events_proto_rawDescGZIP(), []int{3}
}

func (x *MessageEditedV1) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageEditedV1) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageEditedV1) GetConversationSeq() int64 {
	if x != nil {
		return x.ConversationSeq
	}
	return 0
}

func (x *MessageEditedV1) GetChangeVersion() int32 {
	if x != nil {
		return x.ChangeVersion
	}
	return 0
}

func (x *MessageEditedV1) GetEditedBy() string {
	if x != nil {
		return x.EditedBy
	}
	return ""
}

func (x *MessageEditedV1) GetBeforePayload() *structpb.Struct {
	if x != nil {
		return x.BeforePayload
	}
	return nil
}

func (x *MessageEditedV1) GetAfterPayload() *structpb.Struct {
	if x != nil {
		return x.AfterPayload
	}
	return nil
}

func (x *MessageEditedV1) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MessageEditedV1) GetEditedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EditedAt
	}
	return nil
}

type MessageRevokedV1 struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageId       string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ConversationId  string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ConversationSeq int64                  `protobuf:"varint,3,opt,name=conversation_seq,json=conversationSeq,proto3" json:"conversation_seq,omitempty"`
	ChangeVersion   int32                  `protobuf:"varint,4,opt,name=change_version,json=changeVersion,proto3" json:"change_version,omitempty"`
	RevokedBy       string                 `protobuf:"bytes,5,opt,name=revoked_by,json=revokedBy,proto3" json:"revoked_by,omitempty"`
	Reason          string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	RevokedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageRevokedV1) Reset() {
	*x = MessageRevokedV1{}
	mi := &file_conversation_timeline_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRevokedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRevokedV1) ProtoMessage() {}

func (x *MessageRevokedV1) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_timeline_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRevokedV1.ProtoReflect.Descriptor instead.
func (*MessageRevokedV1) Descriptor() ([]byte, []int) {
	return file_conversation_timeline_events_proto_rawDescGZIP(), []int{4}
}

func (x *MessageRevokedV1) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageRevokedV1) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageRevokedV1) GetConversationSeq() int64 {
	if x != nil {
		return x.ConversationSeq
	}
	return 0
}

func (x *MessageRevokedV1) GetChangeVersion() int32 {
	if x != nil {
		return x.ChangeVersion
	}
	return 0
}

func (x *MessageRevokedV1) GetRevokedBy() string {
	if x != nil {
		return x.RevokedBy
	}
	return ""
}

func (x *MessageRevokedV1) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MessageRevokedV1) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

type MessageDeletedV1 struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageId       string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ConversationId  string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ConversationSeq int64                  `protobuf:"varint,3,opt,name=conversation_seq,json=conversationSeq,proto3" json:"conversation_seq,omitempty"`
	ChangeVersion   int32                  `protobuf:"varint,4,opt,name=change_version,json=changeVersion,proto3" json:"change_version,omitempty"`
	DeletedBy       string                 `protobuf:"bytes,5,opt,name=deleted_by,json=deletedBy,proto3" json:"deleted_by,omitempty"`
	DeleteScope     MessageDeleteScope     `protobuf:"varint,6,opt,name=delete_scope,json=deleteScope,proto3,enum=nexusim.conversation.timeline.v1.MessageDeleteScope" json:"delete_scope,omitempty"`
	Reason          string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	DeletedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageDeletedV1) Reset() {
	*x = MessageDeletedV1{}
	mi := &file_conversation_timeline_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDeletedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDeletedV1) ProtoMessage() {}

func (x *MessageDeletedV1) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_timeline_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDeletedV1.ProtoReflect.Descriptor instead.
func (*MessageDeletedV1) Descriptor() ([]byte, []int) {
	return file_conversation_timeline_events_proto_rawDescGZIP(), []int{5}
}

func (x *MessageDeletedV1) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageDeletedV1) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageDeletedV1) GetConversationSeq() int64 {
	if x != nil {
		return x.ConversationSeq
	}
	return 0
}

func (x *MessageDeletedV1) GetChangeVersion() int32 {
	if x != nil {
		return x.ChangeVersion
	}
	return 0
}

func (x *MessageDeletedV1) GetDeletedBy() string {
	if x != nil {
		return x.DeletedBy
	}
	return ""
}

func (x *MessageDeletedV1) GetDeleteScope() MessageDeleteScope {
	if x != nil {
		return x.DeleteScope
	}
	return MessageDeleteScope_MESSAGE_DELETE_SCOPE_UNSPECIFIED
}

func (x *MessageDeletedV1) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MessageDeletedV1) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ConversationMemberJoinedV1 struct {
	state             protoimpl.MessageState       `protogen:"open.v1"`
	ChangeId          string                       `protobuf:"bytes,1,opt,name=change_id,json=changeId,proto3" json:"change_id,omitempty"`
	ConversationId    string                       `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	BoundarySeq       int64                        `protobuf:"varint,3,opt,name=boundary_seq,json=boundarySeq,proto3" json:"boundary_seq,omitempty"`
	TargetUserId      string                       `protobuf:"bytes,4,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	OperatorUserId    string                       `protobuf:"bytes,5,opt,name=operator_user_id,json=operatorUserId,proto3" json:"operator_user_id,omitempty"`
	ChangeType        ConversationMemberChangeType `protobuf:"varint,6,opt,name=change_type,json=changeType,proto3,enum=nexusim.conversation.timeline.v1.ConversationMemberChangeType" json:"change_type,omitempty"`
	OldRole           ConversationMemberRole       `protobuf:"varint,7,opt,name=old_role,json=oldRole,proto3,enum=nexusim.conversation.timeline.v1.ConversationMemberRole" json:"old_role,omitempty"`
	NewRole           ConversationMemberRole       `protobuf:"varint,8,opt,name=new_role,json=newRole,proto3,enum=nexusim.conversation.timeline.v1.ConversationMemberRole" json:"new_role,omitempty"`
	OldStatus         ConversationMemberStatus     `protobuf:"varint,9,opt,name=old_status,json=oldStatus,proto3,enum=nexusim.conversation.timeline.v1.ConversationMemberStatus" json:"old_status,omitempty"`
	NewStatus         ConversationMemberStatus     `protobuf:"varint,10,opt,name=new_status,json=newStatus,proto3,enum=nexusim.conversation.timeline.v1.ConversationMemberStatus" json:"new_status,omitempty"`
	MemberVersion     int64                        `protobuf:"varint,11,opt,name=member_version,json=memberVersion,proto3" json:"member_version,omitempty"`
	PermissionVersion int64                        `protobuf:"varint,12,opt,name=permission_version,json=permissionVersion,proto3" json:"permission_version,omitempty"`
	Reason            string                       `protobuf:"bytes,13,opt,name=reason,proto3" json:"reason,omitempty"`
	OccurredAt        *timestamppb.Timestamp       `protobuf:"bytes,14,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConversationMemberJoinedV1) Reset() {
	*x = ConversationMemberJoinedV1{}
	mi := &file_conversation_timeline_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationMemberJoinedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationMemberJoinedV1) ProtoMessage() {}

func (x *ConversationMemberJoinedV1) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_timeline_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationMemberJoinedV1.ProtoReflect.Descriptor instead.
func (*ConversationMemberJoinedV1) Descriptor() ([]byte, []int) {
	return file_conversation_timeline_events_proto_rawDescGZIP(), []int{6}
}

func (x *ConversationMemberJoinedV1) GetChangeId() string {
	if x != nil {
		return x.ChangeId
	}
	return ""
}

func (x *ConversationMemberJoinedV1) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationMemberJoinedV1) GetBoundarySeq() int64 {
	if x != nil {
		return x.BoundarySeq
	}
	return 0
}

func (x *ConversationMemberJoinedV1) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *ConversationMemberJoinedV1) GetOperatorUserId() string {
	if x != nil {
		return x.OperatorUserId
	}
	return ""
}

func (x *ConversationMemberJoinedV1) GetChangeType() ConversationMemberChangeType {
	if x != nil {
		return x.ChangeType
	}
	return ConversationMemberChangeType_CONVERSATION_MEMBER_CHANGE_TYPE_UNSPECIFIED
}

func (x *ConversationMemberJoinedV1) GetOldRole() ConversationMemberRole {
	if x != nil {
		return x.OldRole
	}
	return ConversationMemberRole_CONVERSATION_MEMBER_ROLE_UNSPECIFIED
}

func (x *ConversationMemberJoinedV1) GetNewRole() ConversationMemberRole {
	if x != nil {
		return x.NewRole
	}
	return ConversationMemberRole_CONVERSATION_MEMBER_ROLE_UNSPECIFIED
}

func (x *ConversationMemberJoinedV1) GetOldStatus() ConversationMemberStatus {
	if x != nil {
		return x.OldStatus
	}
	return ConversationMemberStatus_CONVERSATION_MEMBER_STATUS_UNSPECIFIED
}

func (x *ConversationMemberJoinedV1) GetNewStatus() ConversationMemberStatus {
	if x != nil {
		return x.NewStatus
	}
	return ConversationMemberStatus_CONVERSATION_MEMBER_STATUS_UNSPECIFIED
}

func (x *ConversationMemberJoinedV1) GetMemberVersion() int64 {
	if x != nil {
		return x.MemberVersion
	}
	return 0
}

func (x *ConversationMemberJoinedV1) GetPermissionVersion() int64 {
	if x != nil {
		return x.PermissionVersion
	}
	return 0
}

func (x *ConversationMemberJoinedV1) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ConversationMemberJoinedV1) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

type ConversationMemberLeftV1 struct {
	state             protoimpl.MessageState       `protogen:"open.v1"`
	ChangeId          string                       `protobuf:"bytes,1,opt,name=change_id,json=changeId,proto3" json:"change_id,omitempty"`
	ConversationId    string                       `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	BoundarySeq       int64                        `protobuf:"varint,3,opt,name=boundary_seq,json=boundarySeq,proto3" json:"boundary_seq,omitempty"`
	TargetUserId      string                       `protobuf:"bytes,4,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	OperatorUserId    string                       `protobuf:"bytes,5,opt,name=operator_user_id,json=operatorUserId,proto3" json:"operator_user_id,omitempty"`
	ChangeType        ConversationMemberChangeType `protobuf:"varint,6,opt,name=change_type,json=changeType,proto3,enum=nexusim.conversation.timeline.v1.ConversationMemberChangeType" json:"change_type,omitempty"`
	OldRole           ConversationMemberRole       `protobuf:"varint,7,opt,name=old_role,json=oldRole,proto3,enum=nexusim.conversation.timeline.v1.ConversationMemberRole" json:"old_role,omitempty"`
	NewRole           ConversationMemberRole       `protobuf:"varint,8,opt,name=new_role,json=newRole,proto3,enum=nexusim.conversation.timeline.v1.ConversationMemberRole" json:"new_role,omitempty"`
	OldStatus         ConversationMemberStatus     `protobuf:"varint,9,opt,name=old_status,json=oldStatus,proto3,enum=nexusim.conversation.timeline.v1.ConversationMemberStatus" json:"old_status,omitempty"`
	NewStatus         ConversationMemberStatus     `protobuf:"varint,10,opt,name=new_status,json=newStatus,proto3,enum=nexusim.conversation.timeline.v1.ConversationMemberStatus" json:"new_status,omitempty"`
	MemberVersion     int64                        `protobuf:"varint,11,opt,name=member_version,json=memberVersion,proto3" json:"member_version,omitempty"`
	PermissionVersion int64                        `protobuf:"varint,12,opt,name=permission_version,json=permissionVersion,proto3" json:"permission_version,omitempty"`
	Reason            string                       `protobuf:"bytes,13,opt,name=reason,proto3" json:"reason,omitempty"`
	OccurredAt        *timestamppb.Timestamp       `protobuf:"bytes,14,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConversationMemberLeftV1) Reset() {
	*x = ConversationMemberLeftV1{}
	mi := &file_conversation_timeline_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationMemberLeftV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationMemberLeftV1) ProtoMessage() {}

func (x *ConversationMemberLeftV1) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_timeline_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationMemberLeftV1.ProtoReflect.Descriptor instead.
func (*ConversationMemberLeftV1) Descriptor() ([]byte, []int) {
	return file_conversation_timeline_events_proto_rawDescGZIP(), []int{7}
}

func (x *ConversationMemberLeftV1) GetChangeId() string {
	if x != nil {
		return x.ChangeId
	}
	return ""
}

func (x *ConversationMemberLeftV1) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationMemberLeftV1) GetBoundarySeq() int64 {
	if x != nil {
		return x.BoundarySeq
	}
	return 0
}

func (x *ConversationMemberLeftV1) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *ConversationMemberLeftV1) GetOperatorUserId() string {
	if x != nil {
		return x.OperatorUserId
	}
	return ""
}

func (x *ConversationMemberLeftV1) GetChangeType() ConversationMemberChangeType {
	if x != nil {
		return x.ChangeType
	}
	return ConversationMemberChangeType_CONVERSATION_MEMBER_CHANGE_TYPE_UNSPECIFIED
}

func (x *ConversationMemberLeftV1) GetOldRole() ConversationMemberRole {
	if x != nil {
		return x.OldRole
	}
	return ConversationMemberRole_CONVERSATION_MEMBER_ROLE_UNSPECIFIED
}

func (x *ConversationMemberLeftV1) GetNewRole() ConversationMemberRole {
	if x != nil {
		return x.NewRole
	}
	return ConversationMemberRole_CONVERSATION_MEMBER_ROLE_UNSPECIFIED
}

func (x *ConversationMemberLeftV1) GetOldStatus() ConversationMemberStatus {
	if x != nil {
		return x.OldStatus
	}
	return ConversationMemberStatus_CONVERSATION_MEMBER_STATUS_UNSPECIFIED
}

func (x *ConversationMemberLeftV1) GetNewStatus() ConversationMemberStatus {
	if x != nil {
		return x.NewStatus
	}
	return ConversationMemberStatus_CONVERSATION_MEMBER_STATUS_UNSPECIFIED
}

func (x *ConversationMemberLeftV1) GetMemberVersion() int64 {
	if x != nil {
		return x.MemberVersion
	}
	return 0
}

func (x *ConversationMemberLeftV1) GetPermissionVersion() int64 {
	if x != nil {
		return x.PermissionVersion
	}
	return 0
}

func (x *ConversationMemberLeftV1) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ConversationMemberLeftV1) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

type ConversationMemberRemovedV1 struct {
	state             protoimpl.MessageState       `protogen:"open.v1"`
	ChangeId          string                       `protobuf:"bytes,1,opt,name=change_id,json=changeId,proto3" json:"change_id,omitempty"`
	ConversationId    string                       `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	BoundarySeq       int64                        `protobuf:"varint,3,opt,name=boundary_seq,json=boundarySeq,proto3" json:"boundary_seq,omitempty"`
	TargetUserId      string                       `protobuf:"bytes,4,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	OperatorUserId    string                       `protobuf:"bytes,5,opt,name=operator_user_id,json=operatorUserId,proto3" json:"operator_user_id,omitempty"`
	ChangeType        ConversationMemberChangeType `protobuf:"varint,6,opt,name=change_type,json=changeType,proto3,enum=nexusim.conversation.timeline.v1.ConversationMemberChangeType" json:"change_type,omitempty"`
	OldRole           ConversationMemberRole       `protobuf:"varint,7,opt,name=old_role,json=oldRole,proto3,enum=nexusim.conversation.timeline.v1.ConversationMemberRole" json:"old_role,omitempty"`
	NewRole           ConversationMemberRole       `protobuf:"varint,8,opt,name=new_role,json=newRole,proto3,enum=nexusim.conversation.timeline.v1.ConversationMemberRole" json:"new_role,omitempty"`
	OldStatus         ConversationMemberStatus     `protobuf:"varint,9,opt,name=old_status,json=oldStatus,proto3,enum=nexusim.conversation.timeline.v1.ConversationMemberStatus" json:"old_status,omitempty"`
	NewStatus         ConversationMemberStatus     `protobuf:"varint,10,opt,name=new_status,json=newStatus,proto3,enum=nexusim.conversation.timeline.v1.ConversationMemberStatus" json:"new_status,omitempty"`
	MemberVersion     int64                        `protobuf:"varint,11,opt,name=member_version,json=memberVersion,proto3" json:"member_version,omitempty"`
	PermissionVersion int64                        `protobuf:"varint,12,opt,name=permission_version,json=permissionVersion,proto3" json:"permission_version,omitempty"`
	Reason            string                       `protobuf:"bytes,13,opt,name=reason,proto3" json:"reason,omitempty"`
	OccurredAt        *timestamppb.Timestamp       `protobuf:"bytes,14,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConversationMemberRemovedV1) Reset() {
	*x = ConversationMemberRemovedV1{}
	mi := &file_conversation_timeline_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationMemberRemovedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationMemberRemovedV1) ProtoMessage() {}

func (x *ConversationMemberRemovedV1) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_timeline_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationMemberRemovedV1.ProtoReflect.Descriptor instead.
func (*ConversationMemberRemovedV1) Descriptor() ([]byte, []int) {
	return file_conversation_timeline_events_proto_rawDescGZIP(), []int{8}
}

func (x *ConversationMemberRemovedV1) GetChangeId() string {
	if x != nil {
		return x.ChangeId
	}
	return ""
}

func (x *ConversationMemberRemovedV1) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationMemberRemovedV1) GetBoundarySeq() int64 {
	if x != nil {
		return x.BoundarySeq
	}
	return 0
}

func (x *ConversationMemberRemovedV1) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *ConversationMemberRemovedV1) GetOperatorUserId() string {
	if x != nil {
		return x.OperatorUserId
	}
	return ""
}

func (x *ConversationMemberRemovedV1) GetChangeType() ConversationMemberChangeType {
	if x != nil {
		return x.ChangeType
	}
	return ConversationMemberChangeType_CONVERSATION_MEMBER_CHANGE_TYPE_UNSPECIFIED
}

func (x *ConversationMemberRemovedV1) GetOldRole() ConversationMemberRole {
	if x != nil {
		return x.OldRole
	}
	return ConversationMemberRole_CONVERSATION_MEMBER_ROLE_UNSPECIFIED
}

func (x *ConversationMemberRemovedV1) GetNewRole() ConversationMemberRole {
	if x != nil {
		return x.NewRole
	}
	return ConversationMemberRole_CONVERSATION_MEMBER_ROLE_UNSPECIFIED
}

func (x *ConversationMemberRemovedV1) GetOldStatus() ConversationMemberStatus {
	if x != nil {
		return x.OldStatus
	}
	return ConversationMemberStatus_CONVERSATION_MEMBER_STATUS_UNSPECIFIED
}

func (x *ConversationMemberRemovedV1) GetNewStatus() ConversationMemberStatus {
	if x != nil {
		return x.NewStatus
	}
	return ConversationMemberStatus_CONVERSATION_MEMBER_STATUS_UNSPECIFIED
}

func (x *ConversationMemberRemovedV1) GetMemberVersion() int64 {
	if x != nil {
		return x.MemberVersion
	}
	return 0
}

func (x *ConversationMemberRemovedV1) GetPermissionVersion() int64 {
	if x != nil {
		return x.PermissionVersion
	}
	return 0
}

func (x *ConversationMemberRemovedV1) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ConversationMemberRemovedV1) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

type ConversationMemberRoleChangedV1 struct {
	state             protoimpl.MessageState       `protogen:"open.v1"`
	ChangeId          string                       `protobuf:"bytes,1,opt,name=change_id,json=changeId,proto3" json:"change_id,omitempty"`
	ConversationId    string                       `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	BoundarySeq       int64                        `protobuf:"varint,3,opt,name=boundary_seq,json=boundarySeq,proto3" json:"boundary_seq,omitempty"`
	TargetUserId      string                       `protobuf:"bytes,4,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	OperatorUserId    string                       `protobuf:"bytes,5,opt,name=operator_user_id,json=operatorUserId,proto3" json:"operator_user_id,omitempty"`
	ChangeType        ConversationMemberChangeType `protobuf:"varint,6,opt,name=change_type,json=changeType,proto3,enum=nexusim.conversation.timeline.v1.ConversationMemberChangeType" json:"change_type,omitempty"`
	OldRole           ConversationMemberRole       `protobuf:"varint,7,opt,name=old_role,json=oldRole,proto3,enum=nexusim.conversation.timeline.v1.ConversationMemberRole" json:"old_role,omitempty"`
	NewRole           ConversationMemberRole       `protobuf:"varint,8,opt,name=new_role,json=newRole,proto3,enum=nexusim.conversation.timeline.v1.ConversationMemberRole" json:"new_role,omitempty"`
	OldStatus         ConversationMemberStatus     `protobuf:"varint,9,opt,name=old_status,json=oldStatus,proto3,enum=nexusim.conversation.timeline.v1.ConversationMemberStatus" json:"old_status,omitempty"`
	NewStatus         ConversationMemberStatus     `protobuf:"varint,10,opt,name=new_status,json=newStatus,proto3,enum=nexusim.conversation.timeline.v1.ConversationMemberStatus" json:"new_status,omitempty"`
	MemberVersion     int64                        `protobuf:"varint,11,opt,name=member_version,json=memberVersion,proto3" json:"member_version,omitempty"`
	PermissionVersion int64                        `protobuf:"varint,12,opt,name=permission_version,json=permissionVersion,proto3" json:"permission_version,omitempty"`
	Reason            string                       `protobuf:"bytes,13,opt,name=reason,proto3" json:"reason,omitempty"`
	OccurredAt        *timestamppb.Timestamp       `protobuf:"bytes,14,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConversationMemberRoleChangedV1) Reset() {
	*x = ConversationMemberRoleChangedV1{}
	mi := &file_conversation_timeline_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationMemberRoleChangedV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationMemberRoleChangedV1) ProtoMessage() {}

func (x *ConversationMemberRoleChangedV1) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_timeline_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationMemberRoleChangedV1.ProtoReflect.Descriptor instead.
func (*ConversationMemberRoleChangedV1) Descriptor() ([]byte, []int) {
	return file_conversation_timeline_events_proto_rawDescGZIP(), []int{9}
}

func (x *ConversationMemberRoleChangedV1) GetChangeId() string {
	if x != nil {
		return x.ChangeId
	}
	return ""
}

func (x *ConversationMemberRoleChangedV1) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationMemberRoleChangedV1) GetBoundarySeq() int64 {
	if x != nil {
		return x.BoundarySeq
	}
	return 0
}

func (x *ConversationMemberRoleChangedV1) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *ConversationMemberRoleChangedV1) GetOperatorUserId() string {
	if x != nil {
		return x.OperatorUserId
	}
	return ""
}

func (x *ConversationMemberRoleChangedV1) GetChangeType() ConversationMemberChangeType {
	if x != nil {
		return x.ChangeType
	}
	return ConversationMemberChangeType_CONVERSATION_MEMBER_CHANGE_TYPE_UNSPECIFIED
}

func (x *ConversationMemberRoleChangedV1) GetOldRole() ConversationMemberRole {
	if x != nil {
		return x.OldRole
	}
	return ConversationMemberRole_CONVERSATION_MEMBER_ROLE_UNSPECIFIED
}

func (x *ConversationMemberRoleChangedV1) GetNewRole() ConversationMemberRole {
	if x != nil {
		return x.NewRole
	}
	return ConversationMemberRole_CONVERSATION_MEMBER_ROLE_UNSPECIFIED
}

func (x *ConversationMemberRoleChangedV1) GetOldStatus() ConversationMemberStatus {
	if x != nil {
		return x.OldStatus
	}
	return ConversationMemberStatus_CONVERSATION_MEMBER_STATUS_UNSPECIFIED
}

func (x *ConversationMemberRoleChangedV1) GetNewStatus() ConversationMemberStatus {
	if x != nil {
		return x.NewStatus
	}
	return ConversationMemberStatus_CONVERSATION_MEMBER_STATUS_UNSPECIFIED
}

func (x *ConversationMemberRoleChangedV1) GetMemberVersion() int64 {
	if x != nil {
		return x.MemberVersion
	}
	return 0
}

func (x *ConversationMemberRoleChangedV1) GetPermissionVersion() int64 {
	if x != nil {
		return x.PermissionVersion
	}
	return 0
}

func (x *ConversationMemberRoleChangedV1) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ConversationMemberRoleChangedV1) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

type ConversationMemberBoundaryCancelledV1 struct {
	state             protoimpl.MessageState       `protogen:"open.v1"`
	ChangeId          string                       `protobuf:"bytes,1,opt,name=change_id,json=changeId,proto3" json:"change_id,omitempty"`
	ConversationId    string                       `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	BoundarySeq       int64                        `protobuf:"varint,3,opt,name=boundary_seq,json=boundarySeq,proto3" json:"boundary_seq,omitempty"`
	TargetUserId      string                       `protobuf:"bytes,4,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	OperatorUserId    string                       `protobuf:"bytes,5,opt,name=operator_user_id,json=operatorUserId,proto3" json:"operator_user_id,omitempty"`
	ChangeType        ConversationMemberChangeType `protobuf:"varint,6,opt,name=change_type,json=changeType,proto3,enum=nexusim.conversation.timeline.v1.ConversationMemberChangeType" json:"change_type,omitempty"`
	OldRole           ConversationMemberRole       `protobuf:"varint,7,opt,name=old_role,json=oldRole,proto3,enum=nexusim.conversation.timeline.v1.ConversationMemberRole" json:"old_role,omitempty"`
	NewRole           ConversationMemberRole       `protobuf:"varint,8,opt,name=new_role,json=newRole,proto3,enum=nexusim.conversation.timeline.v1.ConversationMemberRole" json:"new_role,omitempty"`
	OldStatus         ConversationMemberStatus     `protobuf:"varint,9,opt,name=old_status,json=oldStatus,proto3,enum=nexusim.conversation.timeline.v1.ConversationMemberStatus" json:"old_status,omitempty"`
	NewStatus         ConversationMemberStatus     `protobuf:"varint,10,opt,name=new_status,json=newStatus,proto3,enum=nexusim.conversation.timeline.v1.ConversationMemberStatus" json:"new_status,omitempty"`
	MemberVersion     int64                        `protobuf:"varint,11,opt,name=member_version,json=memberVersion,proto3" json:"member_version,omitempty"`
	PermissionVersion int64                        `protobuf:"varint,12,opt,name=permission_version,json=permissionVersion,proto3" json:"permission_version,omitempty"`
	Reason            string                       `protobuf:"bytes,13,opt,name=reason,proto3" json:"reason,omitempty"`
	OccurredAt        *timestamppb.Timestamp       `protobuf:"bytes,14,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConversationMemberBoundaryCancelledV1) Reset() {
	*x = ConversationMemberBoundaryCancelledV1{}
	mi := &file_conversation_timeline_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationMemberBoundaryCancelledV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationMemberBoundaryCancelledV1) ProtoMessage() {}

func (x *ConversationMemberBoundaryCancelledV1) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_timeline_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationMemberBoundaryCancelledV1.ProtoReflect.Descriptor instead.
func (*ConversationMemberBoundaryCancelledV1) Descriptor() ([]byte, []int) {
	return file_conversation_timeline_events_proto_rawDescGZIP(), []int{10}
}

func (x *ConversationMemberBoundaryCancelledV1) GetChangeId() string {
	if x != nil {
		return x.ChangeId
	}
	return ""
}

func (x *ConversationMemberBoundaryCancelledV1) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationMemberBoundaryCancelledV1) GetBoundarySeq() int64 {
	if x != nil {
		return x.BoundarySeq
	}
	return 0
}

func (x *ConversationMemberBoundaryCancelledV1) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

func (x *ConversationMemberBoundaryCancelledV1) GetOperatorUserId() string {
	if x != nil {
		return x.OperatorUserId
	}
	return ""
}

func (x *ConversationMemberBoundaryCancelledV1) GetChangeType() ConversationMemberChangeType {
	if x != nil {
		return x.ChangeType
	}
	return ConversationMemberChangeType_CONVERSATION_MEMBER_CHANGE_TYPE_UNSPECIFIED
}

func (x *ConversationMemberBoundaryCancelledV1) GetOldRole() ConversationMemberRole {
	if x != nil {
		return x.OldRole
	}
	return ConversationMemberRole_CONVERSATION_MEMBER_ROLE_UNSPECIFIED
}

func (x *ConversationMemberBoundaryCancelledV1) GetNewRole() ConversationMemberRole {
	if x != nil {
		return x.NewRole
	}
	return ConversationMemberRole_CONVERSATION_MEMBER_ROLE_UNSPECIFIED
}

func (x *ConversationMemberBoundaryCancelledV1) GetOldStatus() ConversationMemberStatus {
	if x != nil {
		return x.OldStatus
	}
	return ConversationMemberStatus_CONVERSATION_MEMBER_STATUS_UNSPECIFIED
}

func (x *ConversationMemberBoundaryCancelledV1) GetNewStatus() ConversationMemberStatus {
	if x != nil {
		return x.NewStatus
	}
	return ConversationMemberStatus_CONVERSATION_MEMBER_STATUS_UNSPECIFIED
}

func (x *ConversationMemberBoundaryCancelledV1) GetMemberVersion() int64 {
	if x != nil {
		return x.MemberVersion
	}
	return 0
}

func (x *ConversationMemberBoundaryCancelledV1) GetPermissionVersion() int64 {
	if x != nil {
		return x.PermissionVersion
	}
	return 0
}

func (x *ConversationMemberBoundaryCancelledV1) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ConversationMemberBoundaryCancelledV1) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

var File_conversation_timeline_events_proto protoreflect.FileDescriptor

const file_conversation_timeline_events_proto_rawDesc = "" +
	"\n" +
	"\"conversation.timeline.events.proto\x12 nexusim.conversation.timeline.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\r\n" +
	"\x19ConversationTimelineEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12#\n" +
	"\revent_version\x18\x03 \x01(\tR\feventVersion\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12%\n" +
	"\x0eaggregate_type\x18\x05 \x01(\tR\raggregateType\x12!\n" +
	"\faggregate_id\x18\x06 \x01(\tR\vaggregateId\x12+\n" +
	"\x11aggregate_version\x18\a \x01(\x03R\x10aggregateVersion\x12#\n" +
	"\rpartition_key\x18\b \x01(\tR\fpartitionKey\x12'\n" +
	"\x0fmapping_version\x18\t \x01(\tR\x0emappingVersion\x12\x19\n" +
	"\btrace_id\x18\n" +
	" \x01(\tR\atraceId\x12%\n" +
	"\x0ecorrelation_id\x18\v \x01(\tR\rcorrelationId\x12!\n" +
	"\fcausation_id\x18\f \x01(\tR\vcausationId\x12\x1a\n" +
	"\bproducer\x18\r \x01(\tR\bproducer\x12;\n" +
	"\voccurred_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12N\n" +
	"\bmetadata\x18\x0f \x01(\v22.nexusim.conversation.timeline.v1.TimelineMetadataR\bmetadata\x12c\n" +
	"\x11message_persisted\x18\x10 \x01(\v24.nexusim.conversation.timeline.v1.MessagePersistedV1H\x00R\x10messagePersisted\x12Z\n" +
	"\x0emessage_edited\x18\x11 \x01(\v21.nexusim.conversation.timeline.v1.MessageEditedV1H\x00R\rmessageEdited\x12]\n" +
	"\x0fmessage_revoked\x18\x12 \x01(\v22.nexusim.conversation.timeline.v1.MessageRevokedV1H\x00R\x0emessageRevoked\x12]\n" +
	"\x0fmessage_deleted\x18\x13 \x01(\v22.nexusim.conversation.timeline.v1.MessageDeletedV1H\x00R\x0emessageDeleted\x12|\n" +
	"\x1aconversation_member_joined\x18\x14 \x01(\v2<.nexusim.conversation.timeline.v1.ConversationMemberJoinedV1H\x00R\x18conversationMemberJoined\x12v\n" +
	"\x18conversation_member_left\x18\x15 \x01(\v2:.nexusim.conversation.timeline.v1.ConversationMemberLeftV1H\x00R\x16conversationMemberLeft\x12\x7f\n" +
	"\x1bconversation_member_removed\x18\x16 \x01(\v2=.nexusim.conversation.timeline.v1.ConversationMemberRemovedV1H\x00R\x19conversationMemberRemoved\x12\x8c\x01\n" +
	" conversation_member_role_changed\x18\x17 \x01(\v2A.nexusim.conversation.timeline.v1.ConversationMemberRoleChangedV1H\x00R\x1dconversationMemberRoleChanged\x12\x9e\x01\n" +
	"&conversation_member_boundary_cancelled\x18\x18 \x01(\v2G.nexusim.conversation.timeline.v1.ConversationMemberBoundaryCancelledV1H\x00R#conversationMemberBoundaryCancelledB\t\n" +
	"\apayload\"\xe7\x01\n" +
	"\x10TimelineMetadata\x12\x1f\n" +
	"\vfanout_mode\x18\x01 \x01(\tR\n" +
	"fanoutMode\x122\n" +
	"\x15fanout_policy_version\x18\x02 \x01(\x03R\x13fanoutPolicyVersion\x12-\n" +
	"\x12permission_version\x18\x03 \x01(\x03R\x11permissionVersion\x12&\n" +
	"\x0eclassification\x18\x04 \x01(\tR\x0eclassification\x12'\n" +
	"\x0fmapping_version\x18\x05 \x01(\tR\x0emappingVersion\"\xc2\x03\n" +
	"\x12MessagePersistedV1\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12)\n" +
	"\x10conversation_seq\x18\x03 \x01(\x03R\x0fconversationSeq\x12\x1b\n" +
	"\tsender_id\x18\x04 \x01(\tR\bsenderId\x12\x1b\n" +
	"\tdevice_id\x18\x05 \x01(\tR\bdeviceId\x12\"\n" +
	"\rclient_msg_id\x18\x06 \x01(\tR\vclientMsgId\x12!\n" +
	"\fcommand_hash\x18\a \x01(\tR\vcommandHash\x12!\n" +
	"\fmessage_type\x18\b \x01(\tR\vmessageType\x121\n" +
	"\apayload\x18\t \x01(\v2\x17.google.protobuf.StructR\apayload\x12%\n" +
	"\x0eattachment_ids\x18\n" +
	" \x03(\tR\rattachmentIds\x12;\n" +
	"\vaccepted_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"acceptedAt\"\x97\x03\n" +
	"\x0fMessageEditedV1\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12)\n" +
	"\x10conversation_seq\x18\x03 \x01(\x03R\x0fconversationSeq\x12%\n" +
	"\x0echange_version\x18\x04 \x01(\x05R\rchangeVersion\x12\x1b\n" +
	"\tedited_by\x18\x05 \x01(\tR\beditedBy\x12>\n" +
	"\x0ebefore_payload\x18\x06 \x01(\v2\x17.google.protobuf.StructR\rbeforePayload\x12<\n" +
	"\rafter_payload\x18\a \x01(\v2\x17.google.protobuf.StructR\fafterPayload\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\x127\n" +
	"\tedited_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\beditedAt\"\x9e\x02\n" +
	"\x10MessageRevokedV1\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12)\n" +
	"\x10conversation_seq\x18\x03 \x01(\x03R\x0fconversationSeq\x12%\n" +
	"\x0echange_version\x18\x04 \x01(\x05R\rchangeVersion\x12\x1d\n" +
	"\n" +
	"revoked_by\x18\x05 \x01(\tR\trevokedBy\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x129\n" +
	"\n" +
	"revoked_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\"\xf7\x02\n" +
	"\x10MessageDeletedV1\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12)\n" +
	"\x10conversation_seq\x18\x03 \x01(\x03R\x0fconversationSeq\x12%\n" +
	"\x0echange_version\x18\x04 \x01(\x05R\rchangeVersion\x12\x1d\n" +
	"\n" +
	"deleted_by\x18\x05 \x01(\tR\tdeletedBy\x12W\n" +
	"\fdelete_scope\x18\x06 \x01(\x0e24.nexusim.conversation.timeline.v1.MessageDeleteScopeR\vdeleteScope\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x129\n" +
	"\n" +
	"deleted_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\xc1\x06\n" +
	"\x1aConversationMemberJoinedV1\x12\x1b\n" +
	"\tchange_id\x18\x01 \x01(\tR\bchangeId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12!\n" +
	"\fboundary_seq\x18\x03 \x01(\x03R\vboundarySeq\x12$\n" +
	"\x0etarget_user_id\x18\x04 \x01(\tR\ftargetUserId\x12(\n" +
	"\x10operator_user_id\x18\x05 \x01(\tR\x0eoperatorUserId\x12_\n" +
	"\vchange_type\x18\x06 \x01(\x0e2>.nexusim.conversation.timeline.v1.ConversationMemberChangeTypeR\n" +
	"changeType\x12S\n" +
	"\bold_role\x18\a \x01(\x0e28.nexusim.conversation.timeline.v1.ConversationMemberRoleR\aoldRole\x12S\n" +
	"\bnew_role\x18\b \x01(\x0e28.nexusim.conversation.timeline.v1.ConversationMemberRoleR\anewRole\x12Y\n" +
	"\n" +
	"old_status\x18\t \x01(\x0e2:.nexusim.conversation.timeline.v1.ConversationMemberStatusR\toldStatus\x12Y\n" +
	"\n" +
	"new_status\x18\n" +
	" \x01(\x0e2:.nexusim.conversation.timeline.v1.ConversationMemberStatusR\tnewStatus\x12%\n" +
	"\x0emember_version\x18\v \x01(\x03R\rmemberVersion\x12-\n" +
	"\x12permission_version\x18\f \x01(\x03R\x11permissionVersion\x12\x16\n" +
	"\x06reason\x18\r \x01(\tR\x06reason\x12;\n" +
	"\voccurred_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xbf\x06\n" +
	"\x18ConversationMemberLeftV1\x12\x1b\n" +
	"\tchange_id\x18\x01 \x01(\tR\bchangeId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12!\n" +
	"\fboundary_seq\x18\x03 \x01(\x03R\vboundarySeq\x12$\n" +
	"\x0etarget_user_id\x18\x04 \x01(\tR\ftargetUserId\x12(\n" +
	"\x10operator_user_id\x18\x05 \x01(\tR\x0eoperatorUserId\x12_\n" +
	"\vchange_type\x18\x06 \x01(\x0e2>.nexusim.conversation.timeline.v1.ConversationMemberChangeTypeR\n" +
	"changeType\x12S\n" +
	"\bold_role\x18\a \x01(\x0e28.nexusim.conversation.timeline.v1.ConversationMemberRoleR\aoldRole\x12S\n" +
	"\bnew_role\x18\b \x01(\x0e28.nexusim.conversation.timeline.v1.ConversationMemberRoleR\anewRole\x12Y\n" +
	"\n" +
	"old_status\x18\t \x01(\x0e2:.nexusim.conversation.timeline.v1.ConversationMemberStatusR\toldStatus\x12Y\n" +
	"\n" +
	"new_status\x18\n" +
	" \x01(\x0e2:.nexusim.conversation.timeline.v1.ConversationMemberStatusR\tnewStatus\x12%\n" +
	"\x0emember_version\x18\v \x01(\x03R\rmemberVersion\x12-\n" +
	"\x12permission_version\x18\f \x01(\x03R\x11permissionVersion\x12\x16\n" +
	"\x06reason\x18\r \x01(\tR\x06reason\x12;\n" +
	"\voccurred_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xc2\x06\n" +
	"\x1bConversationMemberRemovedV1\x12\x1b\n" +
	"\tchange_id\x18\x01 \x01(\tR\bchangeId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12!\n" +
	"\fboundary_seq\x18\x03 \x01(\x03R\vboundarySeq\x12$\n" +
	"\x0etarget_user_id\x18\x04 \x01(\tR\ftargetUserId\x12(\n" +
	"\x10operator_user_id\x18\x05 \x01(\tR\x0eoperatorUserId\x12_\n" +
	"\vchange_type\x18\x06 \x01(\x0e2>.nexusim.conversation.timeline.v1.ConversationMemberChangeTypeR\n" +
	"changeType\x12S\n" +
	"\bold_role\x18\a \x01(\x0e28.nexusim.conversation.timeline.v1.ConversationMemberRoleR\aoldRole\x12S\n" +
	"\bnew_role\x18\b \x01(\x0e28.nexusim.conversation.timeline.v1.ConversationMemberRoleR\anewRole\x12Y\n" +
	"\n" +
	"old_status\x18\t \x01(\x0e2:.nexusim.conversation.timeline.v1.ConversationMemberStatusR\toldStatus\x12Y\n" +
	"\n" +
	"new_status\x18\n" +
	" \x01(\x0e2:.nexusim.conversation.timeline.v1.ConversationMemberStatusR\tnewStatus\x12%\n" +
	"\x0emember_version\x18\v \x01(\x03R\rmemberVersion\x12-\n" +
	"\x12permission_version\x18\f \x01(\x03R\x11permissionVersion\x12\x16\n" +
	"\x06reason\x18\r \x01(\tR\x06reason\x12;\n" +
	"\voccurred_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xc6\x06\n" +
	"\x1fConversationMemberRoleChangedV1\x12\x1b\n" +
	"\tchange_id\x18\x01 \x01(\tR\bchangeId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12!\n" +
	"\fboundary_seq\x18\x03 \x01(\x03R\vboundarySeq\x12$\n" +
	"\x0etarget_user_id\x18\x04 \x01(\tR\ftargetUserId\x12(\n" +
	"\x10operator_user_id\x18\x05 \x01(\tR\x0eoperatorUserId\x12_\n" +
	"\vchange_type\x18\x06 \x01(\x0e2>.nexusim.conversation.timeline.v1.ConversationMemberChangeTypeR\n" +
	"changeType\x12S\n" +
	"\bold_role\x18\a \x01(\x0e28.nexusim.conversation.timeline.v1.ConversationMemberRoleR\aoldRole\x12S\n" +
	"\bnew_role\x18\b \x01(\x0e28.nexusim.conversation.timeline.v1.ConversationMemberRoleR\anewRole\x12Y\n" +
	"\n" +
	"old_status\x18\t \x01(\x0e2:.nexusim.conversation.timeline.v1.ConversationMemberStatusR\toldStatus\x12Y\n" +
	"\n" +
	"new_status\x18\n" +
	" \x01(\x0e2:.nexusim.conversation.timeline.v1.ConversationMemberStatusR\tnewStatus\x12%\n" +
	"\x0emember_version\x18\v \x01(\x03R\rmemberVersion\x12-\n" +
	"\x12permission_version\x18\f \x01(\x03R\x11permissionVersion\x12\x16\n" +
	"\x06reason\x18\r \x01(\tR\x06reason\x12;\n" +
	"\voccurred_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\"\xcc\x06\n" +
	"%ConversationMemberBoundaryCancelledV1\x12\x1b\n" +
	"\tchange_id\x18\x01 \x01(\tR\bchangeId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12!\n" +
	"\fboundary_seq\x18\x03 \x01(\x03R\vboundarySeq\x12$\n" +
	"\x0etarget_user_id\x18\x04 \x01(\tR\ftargetUserId\x12(\n" +
	"\x10operator_user_id\x18\x05 \x01(\tR\x0eoperatorUserId\x12_\n" +
	"\vchange_type\x18\x06 \x01(\x0e2>.nexusim.conversation.timeline.v1.ConversationMemberChangeTypeR\n" +
	"changeType\x12S\n" +
	"\bold_role\x18\a \x01(\x0e28.nexusim.conversation.timeline.v1.ConversationMemberRoleR\aoldRole\x12S\n" +
	"\bnew_role\x18\b \x01(\x0e28.nexusim.conversation.timeline.v1.ConversationMemberRoleR\anewRole\x12Y\n" +
	"\n" +
	"old_status\x18\t \x01(\x0e2:.nexusim.conversation.timeline.v1.ConversationMemberStatusR\toldStatus\x12Y\n" +
	"\n" +
	"new_status\x18\n" +
	" \x01(\x0e2:.nexusim.conversation.timeline.v1.ConversationMemberStatusR\tnewStatus\x12%\n" +
	"\x0emember_version\x18\v \x01(\x03R\rmemberVersion\x12-\n" +
	"\x12permission_version\x18\f \x01(\x03R\x11permissionVersion\x12\x16\n" +
	"\x06reason\x18\r \x01(\tR\x06reason\x12;\n" +
	"\voccurred_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt*\x95\x01\n" +
	"\x12MessageDeleteScope\x12$\n" +
	" MESSAGE_DELETE_SCOPE_UNSPECIFIED\x10\x00\x12*\n" +
	"&MESSAGE_DELETE_SCOPE_CONVERSATION_VIEW\x10\x01\x12-\n" +
	")MESSAGE_DELETE_SCOPE_COMPLIANCE_RETENTION\x10\x02*\x82\x02\n" +
	"\x1cConversationMemberChangeType\x12/\n" +
	"+CONVERSATION_MEMBER_CHANGE_TYPE_UNSPECIFIED\x10\x00\x12(\n" +
	"$CONVERSATION_MEMBER_CHANGE_TYPE_JOIN\x10\x01\x12)\n" +
	"%CONVERSATION_MEMBER_CHANGE_TYPE_LEAVE\x10\x02\x12*\n" +
	"&CONVERSATION_MEMBER_CHANGE_TYPE_REMOVE\x10\x03\x120\n" +
	",CONVERSATION_MEMBER_CHANGE_TYPE_ROLE_CHANGED\x10\x04*\xaf\x01\n" +
	"\x16ConversationMemberRole\x12(\n" +
	"$CONVERSATION_MEMBER_ROLE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eCONVERSATION_MEMBER_ROLE_OWNER\x10\x01\x12\"\n" +
	"\x1eCONVERSATION_MEMBER_ROLE_ADMIN\x10\x02\x12#\n" +
	"\x1fCONVERSATION_MEMBER_ROLE_MEMBER\x10\x03*\xb9\x01\n" +
	"\x18ConversationMemberStatus\x12*\n" +
	"&CONVERSATION_MEMBER_STATUS_UNSPECIFIED\x10\x00\x12%\n" +
	"!CONVERSATION_MEMBER_STATUS_ACTIVE\x10\x01\x12#\n" +
	"\x1fCONVERSATION_MEMBER_STATUS_LEFT\x10\x02\x12%\n" +
	"!CONVERSATION_MEMBER_STATUS_BANNED\x10\x03B=Z;github.com/qsyy0921/IM/schemas/kafka;conversationtimelinev1b\x06proto3"

var (
	file_conversation_timeline_events_proto_rawDescOnce sync.Once
	file_conversation_timeline_events_proto_rawDescData []byte
)

func file_conversation_timeline_events_proto_rawDescGZIP() []byte {
	file_conversation_timeline_events_proto_rawDescOnce.Do(func() {
		file_conversation_timeline_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conversation_timeline_events_proto_rawDesc), len(file_conversation_timeline_events_proto_rawDesc)))
	})
	return file_conversation_timeline_events_proto_rawDescData
}

var file_conversation_timeline_events_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_conversation_timeline_events_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_conversation_timeline_events_proto_goTypes = []any{
	(MessageDeleteScope)(0),                       // 0: nexusim.conversation.timeline.v1.MessageDeleteScope
	(ConversationMemberChangeType)(0),             // 1: nexusim.conversation.timeline.v1.ConversationMemberChangeType
	(ConversationMemberRole)(0),                   // 2: nexusim.conversation.timeline.v1.ConversationMemberRole
	(ConversationMemberStatus)(0),                 // 3: nexusim.conversation.timeline.v1.ConversationMemberStatus
	(*ConversationTimelineEvent)(nil),             // 4: nexusim.conversation.timeline.v1.ConversationTimelineEvent
	(*TimelineMetadata)(nil),                      // 5: nexusim.conversation.timeline.v1.TimelineMetadata
	(*MessagePersistedV1)(nil),                    // 6: nexusim.conversation.timeline.v1.MessagePersistedV1
	(*MessageEditedV1)(nil),                       // 7: nexusim.conversation.timeline.v1.MessageEditedV1
	(*MessageRevokedV1)(nil),                      // 8: nexusim.conversation.timeline.v1.MessageRevokedV1
	(*MessageDeletedV1)(nil),                      // 9: nexusim.conversation.timeline.v1.MessageDeletedV1
	(*ConversationMemberJoinedV1)(nil),            // 10: nexusim.conversation.timeline.v1.ConversationMemberJoinedV1
	(*ConversationMemberLeftV1)(nil),              // 11: nexusim.conversation.timeline.v1.ConversationMemberLeftV1
	(*ConversationMemberRemovedV1)(nil),           // 12: nexusim.conversation.timeline.v1.ConversationMemberRemovedV1
	(*ConversationMemberRoleChangedV1)(nil),       // 13: nexusim.conversation.timeline.v1.ConversationMemberRoleChangedV1
	(*ConversationMemberBoundaryCancelledV1)(nil), // 14: nexusim.conversation.timeline.v1.ConversationMemberBoundaryCancelledV1
	(*timestamppb.Timestamp)(nil),                 // 15: google.protobuf.Timestamp
	(*structpb.Struct)(nil),                       // 16: google.protobuf.Struct
}
var file_conversation_timeline_events_proto_depIdxs = []int32{
	15, // 0: nexusim.conversation.timeline.v1.ConversationTimelineEvent.occurred_at:type_name -> google.protobuf.Timestamp
	5,  // 1: nexusim.conversation.timeline.v1.ConversationTimelineEvent.metadata:type_name -> nexusim.conversation.timeline.v1.TimelineMetadata
	6,  // 2: nexusim.conversation.timeline.v1.ConversationTimelineEvent.message_persisted:type_name -> nexusim.conversation.timeline.v1.MessagePersistedV1
	7,  // 3: nexusim.conversation.timeline.v1.ConversationTimelineEvent.message_edited:type_name -> nexusim.conversation.timeline.v1.MessageEditedV1
	8,  // 4: nexusim.conversation.timeline.v1.ConversationTimelineEvent.message_revoked:type_name -> nexusim.conversation.timeline.v1.MessageRevokedV1
	9,  // 5: nexusim.conversation.timeline.v1.ConversationTimelineEvent.message_deleted:type_name -> nexusim.conversation.timeline.v1.MessageDeletedV1
	10, // 6: nexusim.conversation.timeline.v1.ConversationTimelineEvent.conversation_member_joined:type_name -> nexusim.conversation.timeline.v1.ConversationMemberJoinedV1
	11, // 7: nexusim.conversation.timeline.v1.ConversationTimelineEvent.conversation_member_left:type_name -> nexusim.conversation.timeline.v1.ConversationMemberLeftV1
	12, // 8: nexusim.conversation.timeline.v1.ConversationTimelineEvent.conversation_member_removed:type_name -> nexusim.conversation.timeline.v1.ConversationMemberRemovedV1
	13, // 9: nexusim.conversation.timeline.v1.ConversationTimelineEvent.conversation_member_role_changed:type_name -> nexusim.conversation.timeline.v1.ConversationMemberRoleChangedV1
	14, // 10: nexusim.conversation.timeline.v1.ConversationTimelineEvent.conversation_member_boundary_cancelled:type_name -> nexusim.conversation.timeline.v1.ConversationMemberBoundaryCancelledV1
	16, // 11: nexusim.conversation.timeline.v1.MessagePersistedV1.payload:type_name -> google.protobuf.Struct
	15, // 12: nexusim.conversation.timeline.v1.MessagePersistedV1.accepted_at:type_name -> google.protobuf.Timestamp
	16, // 13: nexusim.conversation.timeline.v1.MessageEditedV1.before_payload:type_name -> google.protobuf.Struct
	16, // 14: nexusim.conversation.timeline.v1.MessageEditedV1.after_payload:type_name -> google.protobuf.Struct
	15, // 15: nexusim.conversation.timeline.v1.MessageEditedV1.edited_at:type_name -> google.protobuf.Timestamp
	15, // 16: nexusim.conversation.timeline.v1.MessageRevokedV1.revoked_at:type_name -> google.protobuf.Timestamp
	0,  // 17: nexusim.conversation.timeline.v1.MessageDeletedV1.delete_scope:type_name -> nexusim.conversation.timeline.v1.MessageDeleteScope
	15, // 18: nexusim.conversation.timeline.v1.MessageDeletedV1.deleted_at:type_name -> google.protobuf.Timestamp
	1,  // 19: nexusim.conversation.timeline.v1.ConversationMemberJoinedV1.change_type:type_name -> nexusim.conversation.timeline.v1.ConversationMemberChangeType
	2,  // 20: nexusim.conversation.timeline.v1.ConversationMemberJoinedV1.old_role:type_name -> nexusim.conversation.timeline.v1.ConversationMemberRole
	2,  // 21: nexusim.conversation.timeline.v1.ConversationMemberJoinedV1.new_role:type_name -> nexusim.conversation.timeline.v1.ConversationMemberRole
	3,  // 22: nexusim.conversation.timeline.v1.ConversationMemberJoinedV1.old_status:type_name -> nexusim.conversation.timeline.v1.ConversationMemberStatus
	3,  // 23: nexusim.conversation.timeline.v1.ConversationMemberJoinedV1.new_status:type_name -> nexusim.conversation.timeline.v1.ConversationMemberStatus
	15, // 24: nexusim.conversation.timeline.v1.ConversationMemberJoinedV1.occurred_at:type_name -> google.protobuf.Timestamp
	1,  // 25: nexusim.conversation.timeline.v1.ConversationMemberLeftV1.change_type:type_name -> nexusim.conversation.timeline.v1.ConversationMemberChangeType
	2,  // 26: nexusim.conversation.timeline.v1.ConversationMemberLeftV1.old_role:type_name -> nexusim.conversation.timeline.v1.ConversationMemberRole
	2,  // 27: nexusim.conversation.timeline.v1.ConversationMemberLeftV1.new_role:type_name -> nexusim.conversation.timeline.v1.ConversationMemberRole
	3,  // 28: nexusim.conversation.timeline.v1.ConversationMemberLeftV1.old_status:type_name -> nexusim.conversation.timeline.v1.ConversationMemberStatus
	3,  // 29: nexusim.conversation.timeline.v1.ConversationMemberLeftV1.new_status:type_name -> nexusim.conversation.timeline.v1.ConversationMemberStatus
	15, // 30: nexusim.conversation.timeline.v1.ConversationMemberLeftV1.occurred_at:type_name -> google.protobuf.Timestamp
	1,  // 31: nexusim.conversation.timeline.v1.ConversationMemberRemovedV1.change_type:type_name -> nexusim.conversation.timeline.v1.ConversationMemberChangeType
	2,  // 32: nexusim.conversation.timeline.v1.ConversationMemberRemovedV1.old_role:type_name -> nexusim.conversation.timeline.v1.ConversationMemberRole
	2,  // 33: nexusim.conversation.timeline.v1.ConversationMemberRemovedV1.new_role:type_name -> nexusim.conversation.timeline.v1.ConversationMemberRole
	3,  // 34: nexusim.conversation.timeline.v1.ConversationMemberRemovedV1.old_status:type_name -> nexusim.conversation.timeline.v1.ConversationMemberStatus
	3,  // 35: nexusim.conversation.timeline.v1.ConversationMemberRemovedV1.new_status:type_name -> nexusim.conversation.timeline.v1.ConversationMemberStatus
	15, // 36: nexusim.conversation.timeline.v1.ConversationMemberRemovedV1.occurred_at:type_name -> google.protobuf.Timestamp
	1,  // 37: nexusim.conversation.timeline.v1.ConversationMemberRoleChangedV1.change_type:type_name -> nexusim.conversation.timeline.v1.ConversationMemberChangeType
	2,  // 38: nexusim.conversation.timeline.v1.ConversationMemberRoleChangedV1.old_role:type_name -> nexusim.conversation.timeline.v1.ConversationMemberRole
	2,  // 39: nexusim.conversation.timeline.v1.ConversationMemberRoleChangedV1.new_role:type_name -> nexusim.conversation.timeline.v1.ConversationMemberRole
	3,  // 40: nexusim.conversation.timeline.v1.ConversationMemberRoleChangedV1.old_status:type_name -> nexusim.conversation.timeline.v1.ConversationMemberStatus
	3,  // 41: nexusim.conversation.timeline.v1.ConversationMemberRoleChangedV1.new_status:type_name -> nexusim.conversation.timeline.v1.ConversationMemberStatus
	15, // 42: nexusim.conversation.timeline.v1.ConversationMemberRoleChangedV1.occurred_at:type_name -> google.protobuf.Timestamp
	1,  // 43: nexusim.conversation.timeline.v1.ConversationMemberBoundaryCancelledV1.change_type:type_name -> nexusim.conversation.timeline.v1.ConversationMemberChangeType
	2,  // 44: nexusim.conversation.timeline.v1.ConversationMemberBoundaryCancelledV1.old_role:type_name -> nexusim.conversation.timeline.v1.ConversationMemberRole
	2,  // 45: nexusim.conversation.timeline.v1.ConversationMemberBoundaryCancelledV1.new_role:type_name -> nexusim.conversation.timeline.v1.ConversationMemberRole
	3,  // 46: nexusim.conversation.timeline.v1.ConversationMemberBoundaryCancelledV1.old_status:type_name -> nexusim.conversation.timeline.v1.ConversationMemberStatus
	3,  // 47: nexusim.conversation.timeline.v1.ConversationMemberBoundaryCancelledV1.new_status:type_name -> nexusim.conversation.timeline.v1.ConversationMemberStatus
	15, // 48: nexusim.conversation.timeline.v1.ConversationMemberBoundaryCancelledV1.occurred_at:type_name -> google.protobuf.Timestamp
	49, // [49:49] is the sub-list for method output_type
	49, // [49:49] is the sub-list for method input_type
	49, // [49:49] is the sub-list for extension type_name
	49, // [49:49] is the sub-list for extension extendee
	0,  // [0:49] is the sub-list for field type_name
}

func init() { file_conversation_timeline_events_proto_init() }
func file_conversation_timeline_events_proto_init() {
	if File_conversation_timeline_events_proto != nil {
		return
	}
	file_conversation_timeline_events_proto_msgTypes[0].OneofWrappers = []any{
		(*ConversationTimelineEvent_MessagePersisted)(nil),
		(*ConversationTimelineEvent_MessageEdited)(nil),
		(*ConversationTimelineEvent_MessageRevoked)(nil),
		(*ConversationTimelineEvent_MessageDeleted)(nil),
		(*ConversationTimelineEvent_ConversationMemberJoined)(nil),
		(*ConversationTimelineEvent_ConversationMemberLeft)(nil),
		(*ConversationTimelineEvent_ConversationMemberRemoved)(nil),
		(*ConversationTimelineEvent_ConversationMemberRoleChanged)(nil),
		(*ConversationTimelineEvent_ConversationMemberBoundaryCancelled)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conversation_timeline_events_proto_rawDesc), len(file_conversation_timeline_events_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conversation_timeline_events_proto_goTypes,
		DependencyIndexes: file_conversation_timeline_events_proto_depIdxs,
		EnumInfos:         file_conversation_timeline_events_proto_enumTypes,
		MessageInfos:      file_conversation_timeline_events_proto_msgTypes,
	}.Build()
	File_conversation_timeline_events_proto = out.File
	file_conversation_timeline_events_proto_goTypes = nil
	file_conversation_timeline_events_proto_depIdxs = nil
}
