// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: nexusim/identity/v1/identity_service.proto

package identityv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentityService_RegisterUser_FullMethodName                 = "/nexusim.identity.v1.IdentityService/RegisterUser"
	IdentityService_Login_FullMethodName                        = "/nexusim.identity.v1.IdentityService/Login"
	IdentityService_RefreshGatewayToken_FullMethodName          = "/nexusim.identity.v1.IdentityService/RefreshGatewayToken"
	IdentityService_RequestVerificationChallenge_FullMethodName = "/nexusim.identity.v1.IdentityService/RequestVerificationChallenge"
	IdentityService_ConfirmVerificationChallenge_FullMethodName = "/nexusim.identity.v1.IdentityService/ConfirmVerificationChallenge"
	IdentityService_RequestPasswordReset_FullMethodName         = "/nexusim.identity.v1.IdentityService/RequestPasswordReset"
	IdentityService_ConfirmPasswordReset_FullMethodName         = "/nexusim.identity.v1.IdentityService/ConfirmPasswordReset"
	IdentityService_BeginMFAEnrollment_FullMethodName           = "/nexusim.identity.v1.IdentityService/BeginMFAEnrollment"
	IdentityService_ConfirmMFAEnrollment_FullMethodName         = "/nexusim.identity.v1.IdentityService/ConfirmMFAEnrollment"
	IdentityService_DisableMFAFactor_FullMethodName             = "/nexusim.identity.v1.IdentityService/DisableMFAFactor"
	IdentityService_RegenerateMFARecoveryCodes_FullMethodName   = "/nexusim.identity.v1.IdentityService/RegenerateMFARecoveryCodes"
	IdentityService_RevokeMFARecoveryCodes_FullMethodName       = "/nexusim.identity.v1.IdentityService/RevokeMFARecoveryCodes"
	IdentityService_IssueGatewayToken_FullMethodName            = "/nexusim.identity.v1.IdentityService/IssueGatewayToken"
	IdentityService_RevokeDevice_FullMethodName                 = "/nexusim.identity.v1.IdentityService/RevokeDevice"
	IdentityService_RevokeSession_FullMethodName                = "/nexusim.identity.v1.IdentityService/RevokeSession"
	IdentityService_GetDeviceState_FullMethodName               = "/nexusim.identity.v1.IdentityService/GetDeviceState"
)

// IdentityServiceClient is the client API for IdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdentityServiceClient interface {
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	RefreshGatewayToken(ctx context.Context, in *RefreshGatewayTokenRequest, opts ...grpc.CallOption) (*RefreshGatewayTokenResponse, error)
	RequestVerificationChallenge(ctx context.Context, in *RequestVerificationChallengeRequest, opts ...grpc.CallOption) (*RequestVerificationChallengeResponse, error)
	ConfirmVerificationChallenge(ctx context.Context, in *ConfirmVerificationChallengeRequest, opts ...grpc.CallOption) (*ConfirmVerificationChallengeResponse, error)
	RequestPasswordReset(ctx context.Context, in *RequestPasswordResetRequest, opts ...grpc.CallOption) (*RequestPasswordResetResponse, error)
	ConfirmPasswordReset(ctx context.Context, in *ConfirmPasswordResetRequest, opts ...grpc.CallOption) (*ConfirmPasswordResetResponse, error)
	BeginMFAEnrollment(ctx context.Context, in *BeginMFAEnrollmentRequest, opts ...grpc.CallOption) (*BeginMFAEnrollmentResponse, error)
	ConfirmMFAEnrollment(ctx context.Context, in *ConfirmMFAEnrollmentRequest, opts ...grpc.CallOption) (*ConfirmMFAEnrollmentResponse, error)
	DisableMFAFactor(ctx context.Context, in *DisableMFAFactorRequest, opts ...grpc.CallOption) (*DisableMFAFactorResponse, error)
	RegenerateMFARecoveryCodes(ctx context.Context, in *RegenerateMFARecoveryCodesRequest, opts ...grpc.CallOption) (*RegenerateMFARecoveryCodesResponse, error)
	RevokeMFARecoveryCodes(ctx context.Context, in *RevokeMFARecoveryCodesRequest, opts ...grpc.CallOption) (*RevokeMFARecoveryCodesResponse, error)
	IssueGatewayToken(ctx context.Context, in *IssueGatewayTokenRequest, opts ...grpc.CallOption) (*IssueGatewayTokenResponse, error)
	RevokeDevice(ctx context.Context, in *RevokeDeviceRequest, opts ...grpc.CallOption) (*RevokeDeviceResponse, error)
	RevokeSession(ctx context.Context, in *RevokeSessionRequest, opts ...grpc.CallOption) (*RevokeSessionResponse, error)
	GetDeviceState(ctx context.Context, in *GetDeviceStateRequest, opts ...grpc.CallOption) (*GetDeviceStateResponse, error)
}

type identityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityServiceClient(cc grpc.ClientConnInterface) IdentityServiceClient {
	return &identityServiceClient{cc}
}

func (c *identityServiceClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...grpc.CallOption) (*RegisterUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterUserResponse)
	err := c.cc.Invoke(ctx, IdentityService_RegisterUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, IdentityService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) RefreshGatewayToken(ctx context.Context, in *RefreshGatewayTokenRequest, opts ...grpc.CallOption) (*RefreshGatewayTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshGatewayTokenResponse)
	err := c.cc.Invoke(ctx, IdentityService_RefreshGatewayToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) RequestVerificationChallenge(ctx context.Context, in *RequestVerificationChallengeRequest, opts ...grpc.CallOption) (*RequestVerificationChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestVerificationChallengeResponse)
	err := c.cc.Invoke(ctx, IdentityService_RequestVerificationChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) ConfirmVerificationChallenge(ctx context.Context, in *ConfirmVerificationChallengeRequest, opts ...grpc.CallOption) (*ConfirmVerificationChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmVerificationChallengeResponse)
	err := c.cc.Invoke(ctx, IdentityService_ConfirmVerificationChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) RequestPasswordReset(ctx context.Context, in *RequestPasswordResetRequest, opts ...grpc.CallOption) (*RequestPasswordResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestPasswordResetResponse)
	err := c.cc.Invoke(ctx, IdentityService_RequestPasswordReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) ConfirmPasswordReset(ctx context.Context, in *ConfirmPasswordResetRequest, opts ...grpc.CallOption) (*ConfirmPasswordResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmPasswordResetResponse)
	err := c.cc.Invoke(ctx, IdentityService_ConfirmPasswordReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) BeginMFAEnrollment(ctx context.Context, in *BeginMFAEnrollmentRequest, opts ...grpc.CallOption) (*BeginMFAEnrollmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginMFAEnrollmentResponse)
	err := c.cc.Invoke(ctx, IdentityService_BeginMFAEnrollment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) ConfirmMFAEnrollment(ctx context.Context, in *ConfirmMFAEnrollmentRequest, opts ...grpc.CallOption) (*ConfirmMFAEnrollmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmMFAEnrollmentResponse)
	err := c.cc.Invoke(ctx, IdentityService_ConfirmMFAEnrollment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) DisableMFAFactor(ctx context.Context, in *DisableMFAFactorRequest, opts ...grpc.CallOption) (*DisableMFAFactorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableMFAFactorResponse)
	err := c.cc.Invoke(ctx, IdentityService_DisableMFAFactor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) RegenerateMFARecoveryCodes(ctx context.Context, in *RegenerateMFARecoveryCodesRequest, opts ...grpc.CallOption) (*RegenerateMFARecoveryCodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegenerateMFARecoveryCodesResponse)
	err := c.cc.Invoke(ctx, IdentityService_RegenerateMFARecoveryCodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) RevokeMFARecoveryCodes(ctx context.Context, in *RevokeMFARecoveryCodesRequest, opts ...grpc.CallOption) (*RevokeMFARecoveryCodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeMFARecoveryCodesResponse)
	err := c.cc.Invoke(ctx, IdentityService_RevokeMFARecoveryCodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) IssueGatewayToken(ctx context.Context, in *IssueGatewayTokenRequest, opts ...grpc.CallOption) (*IssueGatewayTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueGatewayTokenResponse)
	err := c.cc.Invoke(ctx, IdentityService_IssueGatewayToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) RevokeDevice(ctx context.Context, in *RevokeDeviceRequest, opts ...grpc.CallOption) (*RevokeDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeDeviceResponse)
	err := c.cc.Invoke(ctx, IdentityService_RevokeDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) RevokeSession(ctx context.Context, in *RevokeSessionRequest, opts ...grpc.CallOption) (*RevokeSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeSessionResponse)
	err := c.cc.Invoke(ctx, IdentityService_RevokeSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetDeviceState(ctx context.Context, in *GetDeviceStateRequest, opts ...grpc.CallOption) (*GetDeviceStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeviceStateResponse)
	err := c.cc.Invoke(ctx, IdentityService_GetDeviceState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServiceServer is the server API for IdentityService service.
// All implementations must embed UnimplementedIdentityServiceServer
// for forward compatibility.
type IdentityServiceServer interface {
	RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	RefreshGatewayToken(context.Context, *RefreshGatewayTokenRequest) (*RefreshGatewayTokenResponse, error)
	RequestVerificationChallenge(context.Context, *RequestVerificationChallengeRequest) (*RequestVerificationChallengeResponse, error)
	ConfirmVerificationChallenge(context.Context, *ConfirmVerificationChallengeRequest) (*ConfirmVerificationChallengeResponse, error)
	RequestPasswordReset(context.Context, *RequestPasswordResetRequest) (*RequestPasswordResetResponse, error)
	ConfirmPasswordReset(context.Context, *ConfirmPasswordResetRequest) (*ConfirmPasswordResetResponse, error)
	BeginMFAEnrollment(context.Context, *BeginMFAEnrollmentRequest) (*BeginMFAEnrollmentResponse, error)
	ConfirmMFAEnrollment(context.Context, *ConfirmMFAEnrollmentRequest) (*ConfirmMFAEnrollmentResponse, error)
	DisableMFAFactor(context.Context, *DisableMFAFactorRequest) (*DisableMFAFactorResponse, error)
	RegenerateMFARecoveryCodes(context.Context, *RegenerateMFARecoveryCodesRequest) (*RegenerateMFARecoveryCodesResponse, error)
	RevokeMFARecoveryCodes(context.Context, *RevokeMFARecoveryCodesRequest) (*RevokeMFARecoveryCodesResponse, error)
	IssueGatewayToken(context.Context, *IssueGatewayTokenRequest) (*IssueGatewayTokenResponse, error)
	RevokeDevice(context.Context, *RevokeDeviceRequest) (*RevokeDeviceResponse, error)
	RevokeSession(context.Context, *RevokeSessionRequest) (*RevokeSessionResponse, error)
	GetDeviceState(context.Context, *GetDeviceStateRequest) (*GetDeviceStateResponse, error)
	mustEmbedUnimplementedIdentityServiceServer()
}

// UnimplementedIdentityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityServiceServer struct{}

func (UnimplementedIdentityServiceServer) RegisterUser(context.Context, *RegisterUserRequest) (*RegisterUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterUser not implemented")
}
func (UnimplementedIdentityServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedIdentityServiceServer) RefreshGatewayToken(context.Context, *RefreshGatewayTokenRequest) (*RefreshGatewayTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshGatewayToken not implemented")
}
func (UnimplementedIdentityServiceServer) RequestVerificationChallenge(context.Context, *RequestVerificationChallengeRequest) (*RequestVerificationChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestVerificationChallenge not implemented")
}
func (UnimplementedIdentityServiceServer) ConfirmVerificationChallenge(context.Context, *ConfirmVerificationChallengeRequest) (*ConfirmVerificationChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmVerificationChallenge not implemented")
}
func (UnimplementedIdentityServiceServer) RequestPasswordReset(context.Context, *RequestPasswordResetRequest) (*RequestPasswordResetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestPasswordReset not implemented")
}
func (UnimplementedIdentityServiceServer) ConfirmPasswordReset(context.Context, *ConfirmPasswordResetRequest) (*ConfirmPasswordResetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmPasswordReset not implemented")
}
func (UnimplementedIdentityServiceServer) BeginMFAEnrollment(context.Context, *BeginMFAEnrollmentRequest) (*BeginMFAEnrollmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginMFAEnrollment not implemented")
}
func (UnimplementedIdentityServiceServer) ConfirmMFAEnrollment(context.Context, *ConfirmMFAEnrollmentRequest) (*ConfirmMFAEnrollmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmMFAEnrollment not implemented")
}
func (UnimplementedIdentityServiceServer) DisableMFAFactor(context.Context, *DisableMFAFactorRequest) (*DisableMFAFactorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisableMFAFactor not implemented")
}
func (UnimplementedIdentityServiceServer) RegenerateMFARecoveryCodes(context.Context, *RegenerateMFARecoveryCodesRequest) (*RegenerateMFARecoveryCodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegenerateMFARecoveryCodes not implemented")
}
func (UnimplementedIdentityServiceServer) RevokeMFARecoveryCodes(context.Context, *RevokeMFARecoveryCodesRequest) (*RevokeMFARecoveryCodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeMFARecoveryCodes not implemented")
}
func (UnimplementedIdentityServiceServer) IssueGatewayToken(context.Context, *IssueGatewayTokenRequest) (*IssueGatewayTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueGatewayToken not implemented")
}
func (UnimplementedIdentityServiceServer) RevokeDevice(context.Context, *RevokeDeviceRequest) (*RevokeDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeDevice not implemented")
}
func (UnimplementedIdentityServiceServer) RevokeSession(context.Context, *RevokeSessionRequest) (*RevokeSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeSession not implemented")
}
func (UnimplementedIdentityServiceServer) GetDeviceState(context.Context, *GetDeviceStateRequest) (*GetDeviceStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeviceState not implemented")
}
func (UnimplementedIdentityServiceServer) mustEmbedUnimplementedIdentityServiceServer() {}
func (UnimplementedIdentityServiceServer) testEmbeddedByValue()                         {}

// UnsafeIdentityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServiceServer will
// result in compilation errors.
type UnsafeIdentityServiceServer interface {
	mustEmbedUnimplementedIdentityServiceServer()
}

func RegisterIdentityServiceServer(s grpc.ServiceRegistrar, srv IdentityServiceServer) {
	// If the following call panics, it indicates UnimplementedIdentityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityService_ServiceDesc, srv)
}

func _IdentityService_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_RegisterUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).RegisterUser(ctx, req.(*RegisterUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_RefreshGatewayToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshGatewayTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).RefreshGatewayToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_RefreshGatewayToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).RefreshGatewayToken(ctx, req.(*RefreshGatewayTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_RequestVerificationChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVerificationChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).RequestVerificationChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_RequestVerificationChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).RequestVerificationChallenge(ctx, req.(*RequestVerificationChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_ConfirmVerificationChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmVerificationChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).ConfirmVerificationChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_ConfirmVerificationChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).ConfirmVerificationChallenge(ctx, req.(*ConfirmVerificationChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_RequestPasswordReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPasswordResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).RequestPasswordReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_RequestPasswordReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).RequestPasswordReset(ctx, req.(*RequestPasswordResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_ConfirmPasswordReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPasswordResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).ConfirmPasswordReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_ConfirmPasswordReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).ConfirmPasswordReset(ctx, req.(*ConfirmPasswordResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_BeginMFAEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginMFAEnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).BeginMFAEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_BeginMFAEnrollment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).BeginMFAEnrollment(ctx, req.(*BeginMFAEnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_ConfirmMFAEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmMFAEnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).ConfirmMFAEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_ConfirmMFAEnrollment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).ConfirmMFAEnrollment(ctx, req.(*ConfirmMFAEnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_DisableMFAFactor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableMFAFactorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).DisableMFAFactor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_DisableMFAFactor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).DisableMFAFactor(ctx, req.(*DisableMFAFactorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_RegenerateMFARecoveryCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegenerateMFARecoveryCodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).RegenerateMFARecoveryCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_RegenerateMFARecoveryCodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).RegenerateMFARecoveryCodes(ctx, req.(*RegenerateMFARecoveryCodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_RevokeMFARecoveryCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeMFARecoveryCodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).RevokeMFARecoveryCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_RevokeMFARecoveryCodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).RevokeMFARecoveryCodes(ctx, req.(*RevokeMFARecoveryCodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_IssueGatewayToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueGatewayTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).IssueGatewayToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_IssueGatewayToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).IssueGatewayToken(ctx, req.(*IssueGatewayTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_RevokeDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).RevokeDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_RevokeDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).RevokeDevice(ctx, req.(*RevokeDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_RevokeSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).RevokeSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_RevokeSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).RevokeSession(ctx, req.(*RevokeSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetDeviceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetDeviceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetDeviceState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetDeviceState(ctx, req.(*GetDeviceStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityService_ServiceDesc is the grpc.ServiceDesc for IdentityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexusim.identity.v1.IdentityService",
	HandlerType: (*IdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterUser",
			Handler:    _IdentityService_RegisterUser_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _IdentityService_Login_Handler,
		},
		{
			MethodName: "RefreshGatewayToken",
			Handler:    _IdentityService_RefreshGatewayToken_Handler,
		},
		{
			MethodName: "RequestVerificationChallenge",
			Handler:    _IdentityService_RequestVerificationChallenge_Handler,
		},
		{
			MethodName: "ConfirmVerificationChallenge",
			Handler:    _IdentityService_ConfirmVerificationChallenge_Handler,
		},
		{
			MethodName: "RequestPasswordReset",
			Handler:    _IdentityService_RequestPasswordReset_Handler,
		},
		{
			MethodName: "ConfirmPasswordReset",
			Handler:    _IdentityService_ConfirmPasswordReset_Handler,
		},
		{
			MethodName: "BeginMFAEnrollment",
			Handler:    _IdentityService_BeginMFAEnrollment_Handler,
		},
		{
			MethodName: "ConfirmMFAEnrollment",
			Handler:    _IdentityService_ConfirmMFAEnrollment_Handler,
		},
		{
			MethodName: "DisableMFAFactor",
			Handler:    _IdentityService_DisableMFAFactor_Handler,
		},
		{
			MethodName: "RegenerateMFARecoveryCodes",
			Handler:    _IdentityService_RegenerateMFARecoveryCodes_Handler,
		},
		{
			MethodName: "RevokeMFARecoveryCodes",
			Handler:    _IdentityService_RevokeMFARecoveryCodes_Handler,
		},
		{
			MethodName: "IssueGatewayToken",
			Handler:    _IdentityService_IssueGatewayToken_Handler,
		},
		{
			MethodName: "RevokeDevice",
			Handler:    _IdentityService_RevokeDevice_Handler,
		},
		{
			MethodName: "RevokeSession",
			Handler:    _IdentityService_RevokeSession_Handler,
		},
		{
			MethodName: "GetDeviceState",
			Handler:    _IdentityService_GetDeviceState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nexusim/identity/v1/identity_service.proto",
}
