// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: nexusim/identity/v1/identity_service.proto

package identityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceStatus int32

const (
	DeviceStatus_DEVICE_STATUS_UNSPECIFIED DeviceStatus = 0
	DeviceStatus_DEVICE_STATUS_ACTIVE      DeviceStatus = 1
	DeviceStatus_DEVICE_STATUS_REVOKED     DeviceStatus = 2
)

// Enum value maps for DeviceStatus.
var (
	DeviceStatus_name = map[int32]string{
		0: "DEVICE_STATUS_UNSPECIFIED",
		1: "DEVICE_STATUS_ACTIVE",
		2: "DEVICE_STATUS_REVOKED",
	}
	DeviceStatus_value = map[string]int32{
		"DEVICE_STATUS_UNSPECIFIED": 0,
		"DEVICE_STATUS_ACTIVE":      1,
		"DEVICE_STATUS_REVOKED":     2,
	}
)

func (x DeviceStatus) Enum() *DeviceStatus {
	p := new(DeviceStatus)
	*p = x
	return p
}

func (x DeviceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_nexusim_identity_v1_identity_service_proto_enumTypes[0].Descriptor()
}

func (DeviceStatus) Type() protoreflect.EnumType {
	return &file_nexusim_identity_v1_identity_service_proto_enumTypes[0]
}

func (x DeviceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceStatus.Descriptor instead.
func (DeviceStatus) EnumDescriptor() ([]byte, []int) {
	return file_nexusim_identity_v1_identity_service_proto_rawDescGZIP(), []int{0}
}

type UserStatus int32

const (
	UserStatus_USER_STATUS_UNSPECIFIED UserStatus = 0
	UserStatus_USER_STATUS_ACTIVE      UserStatus = 1
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "USER_STATUS_UNSPECIFIED",
		1: "USER_STATUS_ACTIVE",
	}
	UserStatus_value = map[string]int32{
		"USER_STATUS_UNSPECIFIED": 0,
		"USER_STATUS_ACTIVE":      1,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_nexusim_identity_v1_identity_service_proto_enumTypes[1].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_nexusim_identity_v1_identity_service_proto_enumTypes[1]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_nexusim_identity_v1_identity_service_proto_rawDescGZIP(), []int{1}
}

type SessionStatus int32

const (
	SessionStatus_SESSION_STATUS_UNSPECIFIED SessionStatus = 0
	SessionStatus_SESSION_STATUS_ACTIVE      SessionStatus = 1
	SessionStatus_SESSION_STATUS_REVOKED     SessionStatus = 2
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_UNSPECIFIED",
		1: "SESSION_STATUS_ACTIVE",
		2: "SESSION_STATUS_REVOKED",
	}
	SessionStatus_value = map[string]int32{
		"SESSION_STATUS_UNSPECIFIED": 0,
		"SESSION_STATUS_ACTIVE":      1,
		"SESSION_STATUS_REVOKED":     2,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_nexusim_identity_v1_identity_service_proto_enumTypes[2].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_nexusim_identity_v1_identity_service_proto_enumTypes[2]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_nexusim_identity_v1_identity_service_proto_rawDescGZIP(), []int{2}
}

type AdminContext struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	OperatorUserId string                 `protobuf:"bytes,2,opt,name=operator_user_id,json=operatorUserId,proto3" json:"operator_user_id,omitempty"`
	TraceId        string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	RequestId      string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdminContext) Reset() {
	*x = AdminContext{}
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminContext) ProtoMessage() {}

func (x *AdminContext) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminContext.ProtoReflect.Descriptor instead.
func (*AdminContext) Descriptor() ([]byte, []int) {
	return file_nexusim_identity_v1_identity_service_proto_rawDescGZIP(), []int{0}
}

func (x *AdminContext) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AdminContext) GetOperatorUserId() string {
	if x != nil {
		return x.OperatorUserId
	}
	return ""
}

func (x *AdminContext) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *AdminContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	TraceId       string                 `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_nexusim_identity_v1_identity_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterUserRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RegisterUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterUserRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RegisterUserRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type RegisterUserResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status          UserStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=nexusim.identity.v1.UserStatus" json:"status,omitempty"`
	CreatedAtUnixMs int64                  `protobuf:"varint,4,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_nexusim_identity_v1_identity_service_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterUserResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RegisterUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterUserResponse) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

func (x *RegisterUserResponse) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

type LoginRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TenantId          string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId            string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password          string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	DeviceId          string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Audience          string                 `protobuf:"bytes,5,opt,name=audience,proto3" json:"audience,omitempty"`
	GatewayTtlSeconds int64                  `protobuf:"varint,6,opt,name=gateway_ttl_seconds,json=gatewayTtlSeconds,proto3" json:"gateway_ttl_seconds,omitempty"`
	RefreshTtlSeconds int64                  `protobuf:"varint,7,opt,name=refresh_ttl_seconds,json=refreshTtlSeconds,proto3" json:"refresh_ttl_seconds,omitempty"`
	TraceId           string                 `protobuf:"bytes,8,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	RequestId         string                 `protobuf:"bytes,9,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_nexusim_identity_v1_identity_service_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *LoginRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *LoginRequest) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *LoginRequest) GetGatewayTtlSeconds() int64 {
	if x != nil {
		return x.GatewayTtlSeconds
	}
	return 0
}

func (x *LoginRequest) GetRefreshTtlSeconds() int64 {
	if x != nil {
		return x.RefreshTtlSeconds
	}
	return 0
}

func (x *LoginRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *LoginRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type LoginResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TenantId               string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId                 string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId               string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SessionId              string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Audience               string                 `protobuf:"bytes,5,opt,name=audience,proto3" json:"audience,omitempty"`
	TokenType              string                 `protobuf:"bytes,6,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	GatewayToken           string                 `protobuf:"bytes,7,opt,name=gateway_token,json=gatewayToken,proto3" json:"gateway_token,omitempty"`
	RefreshToken           string                 `protobuf:"bytes,8,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	GatewayExpiresAtUnixMs int64                  `protobuf:"varint,9,opt,name=gateway_expires_at_unix_ms,json=gatewayExpiresAtUnixMs,proto3" json:"gateway_expires_at_unix_ms,omitempty"`
	RefreshExpiresAtUnixMs int64                  `protobuf:"varint,10,opt,name=refresh_expires_at_unix_ms,json=refreshExpiresAtUnixMs,proto3" json:"refresh_expires_at_unix_ms,omitempty"`
	IssuedAtUnixMs         int64                  `protobuf:"varint,11,opt,name=issued_at_unix_ms,json=issuedAtUnixMs,proto3" json:"issued_at_unix_ms,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_nexusim_identity_v1_identity_service_proto_rawDescGZIP(), []int{4}
}

func (x *LoginResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *LoginResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LoginResponse) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *LoginResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *LoginResponse) GetGatewayToken() string {
	if x != nil {
		return x.GatewayToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetGatewayExpiresAtUnixMs() int64 {
	if x != nil {
		return x.GatewayExpiresAtUnixMs
	}
	return 0
}

func (x *LoginResponse) GetRefreshExpiresAtUnixMs() int64 {
	if x != nil {
		return x.RefreshExpiresAtUnixMs
	}
	return 0
}

func (x *LoginResponse) GetIssuedAtUnixMs() int64 {
	if x != nil {
		return x.IssuedAtUnixMs
	}
	return 0
}

type RefreshGatewayTokenRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TenantId          string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId            string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId          string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	RefreshToken      string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Audience          string                 `protobuf:"bytes,5,opt,name=audience,proto3" json:"audience,omitempty"`
	GatewayTtlSeconds int64                  `protobuf:"varint,6,opt,name=gateway_ttl_seconds,json=gatewayTtlSeconds,proto3" json:"gateway_ttl_seconds,omitempty"`
	RefreshTtlSeconds int64                  `protobuf:"varint,7,opt,name=refresh_ttl_seconds,json=refreshTtlSeconds,proto3" json:"refresh_ttl_seconds,omitempty"`
	TraceId           string                 `protobuf:"bytes,8,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	RequestId         string                 `protobuf:"bytes,9,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RefreshGatewayTokenRequest) Reset() {
	*x = RefreshGatewayTokenRequest{}
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshGatewayTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshGatewayTokenRequest) ProtoMessage() {}

func (x *RefreshGatewayTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshGatewayTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshGatewayTokenRequest) Descriptor() ([]byte, []int) {
	return file_nexusim_identity_v1_identity_service_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshGatewayTokenRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RefreshGatewayTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RefreshGatewayTokenRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RefreshGatewayTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshGatewayTokenRequest) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *RefreshGatewayTokenRequest) GetGatewayTtlSeconds() int64 {
	if x != nil {
		return x.GatewayTtlSeconds
	}
	return 0
}

func (x *RefreshGatewayTokenRequest) GetRefreshTtlSeconds() int64 {
	if x != nil {
		return x.RefreshTtlSeconds
	}
	return 0
}

func (x *RefreshGatewayTokenRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *RefreshGatewayTokenRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type RefreshGatewayTokenResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TenantId               string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId                 string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId               string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SessionId              string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Audience               string                 `protobuf:"bytes,5,opt,name=audience,proto3" json:"audience,omitempty"`
	TokenType              string                 `protobuf:"bytes,6,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	GatewayToken           string                 `protobuf:"bytes,7,opt,name=gateway_token,json=gatewayToken,proto3" json:"gateway_token,omitempty"`
	RefreshToken           string                 `protobuf:"bytes,8,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	GatewayExpiresAtUnixMs int64                  `protobuf:"varint,9,opt,name=gateway_expires_at_unix_ms,json=gatewayExpiresAtUnixMs,proto3" json:"gateway_expires_at_unix_ms,omitempty"`
	RefreshExpiresAtUnixMs int64                  `protobuf:"varint,10,opt,name=refresh_expires_at_unix_ms,json=refreshExpiresAtUnixMs,proto3" json:"refresh_expires_at_unix_ms,omitempty"`
	IssuedAtUnixMs         int64                  `protobuf:"varint,11,opt,name=issued_at_unix_ms,json=issuedAtUnixMs,proto3" json:"issued_at_unix_ms,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RefreshGatewayTokenResponse) Reset() {
	*x = RefreshGatewayTokenResponse{}
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshGatewayTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshGatewayTokenResponse) ProtoMessage() {}

func (x *RefreshGatewayTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshGatewayTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshGatewayTokenResponse) Descriptor() ([]byte, []int) {
	return file_nexusim_identity_v1_identity_service_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshGatewayTokenResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RefreshGatewayTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RefreshGatewayTokenResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RefreshGatewayTokenResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RefreshGatewayTokenResponse) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *RefreshGatewayTokenResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *RefreshGatewayTokenResponse) GetGatewayToken() string {
	if x != nil {
		return x.GatewayToken
	}
	return ""
}

func (x *RefreshGatewayTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshGatewayTokenResponse) GetGatewayExpiresAtUnixMs() int64 {
	if x != nil {
		return x.GatewayExpiresAtUnixMs
	}
	return 0
}

func (x *RefreshGatewayTokenResponse) GetRefreshExpiresAtUnixMs() int64 {
	if x != nil {
		return x.RefreshExpiresAtUnixMs
	}
	return 0
}

func (x *RefreshGatewayTokenResponse) GetIssuedAtUnixMs() int64 {
	if x != nil {
		return x.IssuedAtUnixMs
	}
	return 0
}

type IssueGatewayTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Audience      string                 `protobuf:"bytes,5,opt,name=audience,proto3" json:"audience,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,6,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	TraceId       string                 `protobuf:"bytes,7,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,8,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueGatewayTokenRequest) Reset() {
	*x = IssueGatewayTokenRequest{}
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueGatewayTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueGatewayTokenRequest) ProtoMessage() {}

func (x *IssueGatewayTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueGatewayTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueGatewayTokenRequest) Descriptor() ([]byte, []int) {
	return file_nexusim_identity_v1_identity_service_proto_rawDescGZIP(), []int{7}
}

func (x *IssueGatewayTokenRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *IssueGatewayTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IssueGatewayTokenRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *IssueGatewayTokenRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *IssueGatewayTokenRequest) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *IssueGatewayTokenRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *IssueGatewayTokenRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *IssueGatewayTokenRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type IssueGatewayTokenResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId        string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SessionId       string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Audience        string                 `protobuf:"bytes,5,opt,name=audience,proto3" json:"audience,omitempty"`
	GatewayToken    string                 `protobuf:"bytes,6,opt,name=gateway_token,json=gatewayToken,proto3" json:"gateway_token,omitempty"`
	ExpiresAtUnixMs int64                  `protobuf:"varint,7,opt,name=expires_at_unix_ms,json=expiresAtUnixMs,proto3" json:"expires_at_unix_ms,omitempty"`
	IssuedAtUnixMs  int64                  `protobuf:"varint,8,opt,name=issued_at_unix_ms,json=issuedAtUnixMs,proto3" json:"issued_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IssueGatewayTokenResponse) Reset() {
	*x = IssueGatewayTokenResponse{}
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueGatewayTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueGatewayTokenResponse) ProtoMessage() {}

func (x *IssueGatewayTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueGatewayTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueGatewayTokenResponse) Descriptor() ([]byte, []int) {
	return file_nexusim_identity_v1_identity_service_proto_rawDescGZIP(), []int{8}
}

func (x *IssueGatewayTokenResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *IssueGatewayTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IssueGatewayTokenResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *IssueGatewayTokenResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *IssueGatewayTokenResponse) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *IssueGatewayTokenResponse) GetGatewayToken() string {
	if x != nil {
		return x.GatewayToken
	}
	return ""
}

func (x *IssueGatewayTokenResponse) GetExpiresAtUnixMs() int64 {
	if x != nil {
		return x.ExpiresAtUnixMs
	}
	return 0
}

func (x *IssueGatewayTokenResponse) GetIssuedAtUnixMs() int64 {
	if x != nil {
		return x.IssuedAtUnixMs
	}
	return 0
}

type RevokeDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminContext  *AdminContext          `protobuf:"bytes,1,opt,name=admin_context,json=adminContext,proto3" json:"admin_context,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeDeviceRequest) Reset() {
	*x = RevokeDeviceRequest{}
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeDeviceRequest) ProtoMessage() {}

func (x *RevokeDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeDeviceRequest.ProtoReflect.Descriptor instead.
func (*RevokeDeviceRequest) Descriptor() ([]byte, []int) {
	return file_nexusim_identity_v1_identity_service_proto_rawDescGZIP(), []int{9}
}

func (x *RevokeDeviceRequest) GetAdminContext() *AdminContext {
	if x != nil {
		return x.AdminContext
	}
	return nil
}

func (x *RevokeDeviceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RevokeDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RevokeDeviceRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RevokeDeviceResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId        string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Status          DeviceStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=nexusim.identity.v1.DeviceStatus" json:"status,omitempty"`
	RevokedAtUnixMs int64                  `protobuf:"varint,5,opt,name=revoked_at_unix_ms,json=revokedAtUnixMs,proto3" json:"revoked_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RevokeDeviceResponse) Reset() {
	*x = RevokeDeviceResponse{}
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeDeviceResponse) ProtoMessage() {}

func (x *RevokeDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeDeviceResponse.ProtoReflect.Descriptor instead.
func (*RevokeDeviceResponse) Descriptor() ([]byte, []int) {
	return file_nexusim_identity_v1_identity_service_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeDeviceResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RevokeDeviceResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RevokeDeviceResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RevokeDeviceResponse) GetStatus() DeviceStatus {
	if x != nil {
		return x.Status
	}
	return DeviceStatus_DEVICE_STATUS_UNSPECIFIED
}

func (x *RevokeDeviceResponse) GetRevokedAtUnixMs() int64 {
	if x != nil {
		return x.RevokedAtUnixMs
	}
	return 0
}

type RevokeSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminContext  *AdminContext          `protobuf:"bytes,1,opt,name=admin_context,json=adminContext,proto3" json:"admin_context,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionRequest) Reset() {
	*x = RevokeSessionRequest{}
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionRequest) ProtoMessage() {}

func (x *RevokeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionRequest.ProtoReflect.Descriptor instead.
func (*RevokeSessionRequest) Descriptor() ([]byte, []int) {
	return file_nexusim_identity_v1_identity_service_proto_rawDescGZIP(), []int{11}
}

func (x *RevokeSessionRequest) GetAdminContext() *AdminContext {
	if x != nil {
		return x.AdminContext
	}
	return nil
}

func (x *RevokeSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RevokeSessionRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RevokeSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RevokeSessionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RevokeSessionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId        string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	SessionId       string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status          SessionStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=nexusim.identity.v1.SessionStatus" json:"status,omitempty"`
	RevokedAtUnixMs int64                  `protobuf:"varint,6,opt,name=revoked_at_unix_ms,json=revokedAtUnixMs,proto3" json:"revoked_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RevokeSessionResponse) Reset() {
	*x = RevokeSessionResponse{}
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionResponse) ProtoMessage() {}

func (x *RevokeSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionResponse.ProtoReflect.Descriptor instead.
func (*RevokeSessionResponse) Descriptor() ([]byte, []int) {
	return file_nexusim_identity_v1_identity_service_proto_rawDescGZIP(), []int{12}
}

func (x *RevokeSessionResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RevokeSessionResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RevokeSessionResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RevokeSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RevokeSessionResponse) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *RevokeSessionResponse) GetRevokedAtUnixMs() int64 {
	if x != nil {
		return x.RevokedAtUnixMs
	}
	return 0
}

type GetDeviceStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminContext  *AdminContext          `protobuf:"bytes,1,opt,name=admin_context,json=adminContext,proto3" json:"admin_context,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceStateRequest) Reset() {
	*x = GetDeviceStateRequest{}
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceStateRequest) ProtoMessage() {}

func (x *GetDeviceStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceStateRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceStateRequest) Descriptor() ([]byte, []int) {
	return file_nexusim_identity_v1_identity_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetDeviceStateRequest) GetAdminContext() *AdminContext {
	if x != nil {
		return x.AdminContext
	}
	return nil
}

func (x *GetDeviceStateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetDeviceStateRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type GetDeviceStateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId        string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Status          DeviceStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=nexusim.identity.v1.DeviceStatus" json:"status,omitempty"`
	CreatedAtUnixMs int64                  `protobuf:"varint,5,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	UpdatedAtUnixMs int64                  `protobuf:"varint,6,opt,name=updated_at_unix_ms,json=updatedAtUnixMs,proto3" json:"updated_at_unix_ms,omitempty"`
	RevokedAtUnixMs int64                  `protobuf:"varint,7,opt,name=revoked_at_unix_ms,json=revokedAtUnixMs,proto3" json:"revoked_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetDeviceStateResponse) Reset() {
	*x = GetDeviceStateResponse{}
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceStateResponse) ProtoMessage() {}

func (x *GetDeviceStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_identity_v1_identity_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceStateResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceStateResponse) Descriptor() ([]byte, []int) {
	return file_nexusim_identity_v1_identity_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetDeviceStateResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetDeviceStateResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetDeviceStateResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetDeviceStateResponse) GetStatus() DeviceStatus {
	if x != nil {
		return x.Status
	}
	return DeviceStatus_DEVICE_STATUS_UNSPECIFIED
}

func (x *GetDeviceStateResponse) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

func (x *GetDeviceStateResponse) GetUpdatedAtUnixMs() int64 {
	if x != nil {
		return x.UpdatedAtUnixMs
	}
	return 0
}

func (x *GetDeviceStateResponse) GetRevokedAtUnixMs() int64 {
	if x != nil {
		return x.RevokedAtUnixMs
	}
	return 0
}

var File_nexusim_identity_v1_identity_service_proto protoreflect.FileDescriptor

const file_nexusim_identity_v1_identity_service_proto_rawDesc = "" +
	"\n" +
	"*nexusim/identity/v1/identity_service.proto\x12\x13nexusim.identity.v1\"\x8f\x01\n" +
	"\fAdminContext\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12(\n" +
	"\x10operator_user_id\x18\x02 \x01(\tR\x0eoperatorUserId\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"\xa1\x01\n" +
	"\x13RegisterUserRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x19\n" +
	"\btrace_id\x18\x04 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\"\xb2\x01\n" +
	"\x14RegisterUserResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x127\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1f.nexusim.identity.v1.UserStatusR\x06status\x12+\n" +
	"\x12created_at_unix_ms\x18\x04 \x01(\x03R\x0fcreatedAtUnixMs\"\xb3\x02\n" +
	"\fLoginRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\baudience\x18\x05 \x01(\tR\baudience\x12.\n" +
	"\x13gateway_ttl_seconds\x18\x06 \x01(\x03R\x11gatewayTtlSeconds\x12.\n" +
	"\x13refresh_ttl_seconds\x18\a \x01(\x03R\x11refreshTtlSeconds\x12\x19\n" +
	"\btrace_id\x18\b \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\t \x01(\tR\trequestId\"\xa9\x03\n" +
	"\rLoginResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x1a\n" +
	"\baudience\x18\x05 \x01(\tR\baudience\x12\x1d\n" +
	"\n" +
	"token_type\x18\x06 \x01(\tR\ttokenType\x12#\n" +
	"\rgateway_token\x18\a \x01(\tR\fgatewayToken\x12#\n" +
	"\rrefresh_token\x18\b \x01(\tR\frefreshToken\x12:\n" +
	"\x1agateway_expires_at_unix_ms\x18\t \x01(\x03R\x16gatewayExpiresAtUnixMs\x12:\n" +
	"\x1arefresh_expires_at_unix_ms\x18\n" +
	" \x01(\x03R\x16refreshExpiresAtUnixMs\x12)\n" +
	"\x11issued_at_unix_ms\x18\v \x01(\x03R\x0eissuedAtUnixMs\"\xca\x02\n" +
	"\x1aRefreshGatewayTokenRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12\x1a\n" +
	"\baudience\x18\x05 \x01(\tR\baudience\x12.\n" +
	"\x13gateway_ttl_seconds\x18\x06 \x01(\x03R\x11gatewayTtlSeconds\x12.\n" +
	"\x13refresh_ttl_seconds\x18\a \x01(\x03R\x11refreshTtlSeconds\x12\x19\n" +
	"\btrace_id\x18\b \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\t \x01(\tR\trequestId\"\xb7\x03\n" +
	"\x1bRefreshGatewayTokenResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x1a\n" +
	"\baudience\x18\x05 \x01(\tR\baudience\x12\x1d\n" +
	"\n" +
	"token_type\x18\x06 \x01(\tR\ttokenType\x12#\n" +
	"\rgateway_token\x18\a \x01(\tR\fgatewayToken\x12#\n" +
	"\rrefresh_token\x18\b \x01(\tR\frefreshToken\x12:\n" +
	"\x1agateway_expires_at_unix_ms\x18\t \x01(\x03R\x16gatewayExpiresAtUnixMs\x12:\n" +
	"\x1arefresh_expires_at_unix_ms\x18\n" +
	" \x01(\x03R\x16refreshExpiresAtUnixMs\x12)\n" +
	"\x11issued_at_unix_ms\x18\v \x01(\x03R\x0eissuedAtUnixMs\"\x83\x02\n" +
	"\x18IssueGatewayTokenRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x1a\n" +
	"\baudience\x18\x05 \x01(\tR\baudience\x12\x1f\n" +
	"\vttl_seconds\x18\x06 \x01(\x03R\n" +
	"ttlSeconds\x12\x19\n" +
	"\btrace_id\x18\a \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\b \x01(\tR\trequestId\"\xa6\x02\n" +
	"\x19IssueGatewayTokenResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x1a\n" +
	"\baudience\x18\x05 \x01(\tR\baudience\x12#\n" +
	"\rgateway_token\x18\x06 \x01(\tR\fgatewayToken\x12+\n" +
	"\x12expires_at_unix_ms\x18\a \x01(\x03R\x0fexpiresAtUnixMs\x12)\n" +
	"\x11issued_at_unix_ms\x18\b \x01(\x03R\x0eissuedAtUnixMs\"\xab\x01\n" +
	"\x13RevokeDeviceRequest\x12F\n" +
	"\radmin_context\x18\x01 \x01(\v2!.nexusim.identity.v1.AdminContextR\fadminContext\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\xd1\x01\n" +
	"\x14RevokeDeviceResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x129\n" +
	"\x06status\x18\x04 \x01(\x0e2!.nexusim.identity.v1.DeviceStatusR\x06status\x12+\n" +
	"\x12revoked_at_unix_ms\x18\x05 \x01(\x03R\x0frevokedAtUnixMs\"\xcb\x01\n" +
	"\x14RevokeSessionRequest\x12F\n" +
	"\radmin_context\x18\x01 \x01(\v2!.nexusim.identity.v1.AdminContextR\fadminContext\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\xf2\x01\n" +
	"\x15RevokeSessionResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12:\n" +
	"\x06status\x18\x05 \x01(\x0e2\".nexusim.identity.v1.SessionStatusR\x06status\x12+\n" +
	"\x12revoked_at_unix_ms\x18\x06 \x01(\x03R\x0frevokedAtUnixMs\"\x95\x01\n" +
	"\x15GetDeviceStateRequest\x12F\n" +
	"\radmin_context\x18\x01 \x01(\v2!.nexusim.identity.v1.AdminContextR\fadminContext\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\"\xad\x02\n" +
	"\x16GetDeviceStateResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x129\n" +
	"\x06status\x18\x04 \x01(\x0e2!.nexusim.identity.v1.DeviceStatusR\x06status\x12+\n" +
	"\x12created_at_unix_ms\x18\x05 \x01(\x03R\x0fcreatedAtUnixMs\x12+\n" +
	"\x12updated_at_unix_ms\x18\x06 \x01(\x03R\x0fupdatedAtUnixMs\x12+\n" +
	"\x12revoked_at_unix_ms\x18\a \x01(\x03R\x0frevokedAtUnixMs*b\n" +
	"\fDeviceStatus\x12\x1d\n" +
	"\x19DEVICE_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14DEVICE_STATUS_ACTIVE\x10\x01\x12\x19\n" +
	"\x15DEVICE_STATUS_REVOKED\x10\x02*A\n" +
	"\n" +
	"UserStatus\x12\x1b\n" +
	"\x17USER_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12USER_STATUS_ACTIVE\x10\x01*f\n" +
	"\rSessionStatus\x12\x1e\n" +
	"\x1aSESSION_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SESSION_STATUS_ACTIVE\x10\x01\x12\x1a\n" +
	"\x16SESSION_STATUS_REVOKED\x10\x022\xec\x05\n" +
	"\x0fIdentityService\x12c\n" +
	"\fRegisterUser\x12(.nexusim.identity.v1.RegisterUserRequest\x1a).nexusim.identity.v1.RegisterUserResponse\x12N\n" +
	"\x05Login\x12!.nexusim.identity.v1.LoginRequest\x1a\".nexusim.identity.v1.LoginResponse\x12x\n" +
	"\x13RefreshGatewayToken\x12/.nexusim.identity.v1.RefreshGatewayTokenRequest\x1a0.nexusim.identity.v1.RefreshGatewayTokenResponse\x12r\n" +
	"\x11IssueGatewayToken\x12-.nexusim.identity.v1.IssueGatewayTokenRequest\x1a..nexusim.identity.v1.IssueGatewayTokenResponse\x12c\n" +
	"\fRevokeDevice\x12(.nexusim.identity.v1.RevokeDeviceRequest\x1a).nexusim.identity.v1.RevokeDeviceResponse\x12f\n" +
	"\rRevokeSession\x12).nexusim.identity.v1.RevokeSessionRequest\x1a*.nexusim.identity.v1.RevokeSessionResponse\x12i\n" +
	"\x0eGetDeviceState\x12*.nexusim.identity.v1.GetDeviceStateRequest\x1a+.nexusim.identity.v1.GetDeviceStateResponseBAZ?github.com/qsyy0921/IM/api/proto/nexusim/identity/v1;identityv1b\x06proto3"

var (
	file_nexusim_identity_v1_identity_service_proto_rawDescOnce sync.Once
	file_nexusim_identity_v1_identity_service_proto_rawDescData []byte
)

func file_nexusim_identity_v1_identity_service_proto_rawDescGZIP() []byte {
	file_nexusim_identity_v1_identity_service_proto_rawDescOnce.Do(func() {
		file_nexusim_identity_v1_identity_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nexusim_identity_v1_identity_service_proto_rawDesc), len(file_nexusim_identity_v1_identity_service_proto_rawDesc)))
	})
	return file_nexusim_identity_v1_identity_service_proto_rawDescData
}

var file_nexusim_identity_v1_identity_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_nexusim_identity_v1_identity_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_nexusim_identity_v1_identity_service_proto_goTypes = []any{
	(DeviceStatus)(0),                   // 0: nexusim.identity.v1.DeviceStatus
	(UserStatus)(0),                     // 1: nexusim.identity.v1.UserStatus
	(SessionStatus)(0),                  // 2: nexusim.identity.v1.SessionStatus
	(*AdminContext)(nil),                // 3: nexusim.identity.v1.AdminContext
	(*RegisterUserRequest)(nil),         // 4: nexusim.identity.v1.RegisterUserRequest
	(*RegisterUserResponse)(nil),        // 5: nexusim.identity.v1.RegisterUserResponse
	(*LoginRequest)(nil),                // 6: nexusim.identity.v1.LoginRequest
	(*LoginResponse)(nil),               // 7: nexusim.identity.v1.LoginResponse
	(*RefreshGatewayTokenRequest)(nil),  // 8: nexusim.identity.v1.RefreshGatewayTokenRequest
	(*RefreshGatewayTokenResponse)(nil), // 9: nexusim.identity.v1.RefreshGatewayTokenResponse
	(*IssueGatewayTokenRequest)(nil),    // 10: nexusim.identity.v1.IssueGatewayTokenRequest
	(*IssueGatewayTokenResponse)(nil),   // 11: nexusim.identity.v1.IssueGatewayTokenResponse
	(*RevokeDeviceRequest)(nil),         // 12: nexusim.identity.v1.RevokeDeviceRequest
	(*RevokeDeviceResponse)(nil),        // 13: nexusim.identity.v1.RevokeDeviceResponse
	(*RevokeSessionRequest)(nil),        // 14: nexusim.identity.v1.RevokeSessionRequest
	(*RevokeSessionResponse)(nil),       // 15: nexusim.identity.v1.RevokeSessionResponse
	(*GetDeviceStateRequest)(nil),       // 16: nexusim.identity.v1.GetDeviceStateRequest
	(*GetDeviceStateResponse)(nil),      // 17: nexusim.identity.v1.GetDeviceStateResponse
}
var file_nexusim_identity_v1_identity_service_proto_depIdxs = []int32{
	1,  // 0: nexusim.identity.v1.RegisterUserResponse.status:type_name -> nexusim.identity.v1.UserStatus
	3,  // 1: nexusim.identity.v1.RevokeDeviceRequest.admin_context:type_name -> nexusim.identity.v1.AdminContext
	0,  // 2: nexusim.identity.v1.RevokeDeviceResponse.status:type_name -> nexusim.identity.v1.DeviceStatus
	3,  // 3: nexusim.identity.v1.RevokeSessionRequest.admin_context:type_name -> nexusim.identity.v1.AdminContext
	2,  // 4: nexusim.identity.v1.RevokeSessionResponse.status:type_name -> nexusim.identity.v1.SessionStatus
	3,  // 5: nexusim.identity.v1.GetDeviceStateRequest.admin_context:type_name -> nexusim.identity.v1.AdminContext
	0,  // 6: nexusim.identity.v1.GetDeviceStateResponse.status:type_name -> nexusim.identity.v1.DeviceStatus
	4,  // 7: nexusim.identity.v1.IdentityService.RegisterUser:input_type -> nexusim.identity.v1.RegisterUserRequest
	6,  // 8: nexusim.identity.v1.IdentityService.Login:input_type -> nexusim.identity.v1.LoginRequest
	8,  // 9: nexusim.identity.v1.IdentityService.RefreshGatewayToken:input_type -> nexusim.identity.v1.RefreshGatewayTokenRequest
	10, // 10: nexusim.identity.v1.IdentityService.IssueGatewayToken:input_type -> nexusim.identity.v1.IssueGatewayTokenRequest
	12, // 11: nexusim.identity.v1.IdentityService.RevokeDevice:input_type -> nexusim.identity.v1.RevokeDeviceRequest
	14, // 12: nexusim.identity.v1.IdentityService.RevokeSession:input_type -> nexusim.identity.v1.RevokeSessionRequest
	16, // 13: nexusim.identity.v1.IdentityService.GetDeviceState:input_type -> nexusim.identity.v1.GetDeviceStateRequest
	5,  // 14: nexusim.identity.v1.IdentityService.RegisterUser:output_type -> nexusim.identity.v1.RegisterUserResponse
	7,  // 15: nexusim.identity.v1.IdentityService.Login:output_type -> nexusim.identity.v1.LoginResponse
	9,  // 16: nexusim.identity.v1.IdentityService.RefreshGatewayToken:output_type -> nexusim.identity.v1.RefreshGatewayTokenResponse
	11, // 17: nexusim.identity.v1.IdentityService.IssueGatewayToken:output_type -> nexusim.identity.v1.IssueGatewayTokenResponse
	13, // 18: nexusim.identity.v1.IdentityService.RevokeDevice:output_type -> nexusim.identity.v1.RevokeDeviceResponse
	15, // 19: nexusim.identity.v1.IdentityService.RevokeSession:output_type -> nexusim.identity.v1.RevokeSessionResponse
	17, // 20: nexusim.identity.v1.IdentityService.GetDeviceState:output_type -> nexusim.identity.v1.GetDeviceStateResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_nexusim_identity_v1_identity_service_proto_init() }
func file_nexusim_identity_v1_identity_service_proto_init() {
	if File_nexusim_identity_v1_identity_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nexusim_identity_v1_identity_service_proto_rawDesc), len(file_nexusim_identity_v1_identity_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nexusim_identity_v1_identity_service_proto_goTypes,
		DependencyIndexes: file_nexusim_identity_v1_identity_service_proto_depIdxs,
		EnumInfos:         file_nexusim_identity_v1_identity_service_proto_enumTypes,
		MessageInfos:      file_nexusim_identity_v1_identity_service_proto_msgTypes,
	}.Build()
	File_nexusim_identity_v1_identity_service_proto = out.File
	file_nexusim_identity_v1_identity_service_proto_goTypes = nil
	file_nexusim_identity_v1_identity_service_proto_depIdxs = nil
}
