// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: nexusim/workflow/v1/workflow_service.proto

package workflowv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	InstanceRef   string                 `protobuf:"bytes,4,opt,name=instance_ref,json=instanceRef,proto3" json:"instance_ref,omitempty"`
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthContext) Reset() {
	*x = AuthContext{}
	mi := &file_nexusim_workflow_v1_workflow_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthContext) ProtoMessage() {}

func (x *AuthContext) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_workflow_v1_workflow_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthContext.ProtoReflect.Descriptor instead.
func (*AuthContext) Descriptor() ([]byte, []int) {
	return file_nexusim_workflow_v1_workflow_service_proto_rawDescGZIP(), []int{0}
}

func (x *AuthContext) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AuthContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthContext) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *AuthContext) GetInstanceRef() string {
	if x != nil {
		return x.InstanceRef
	}
	return ""
}

func (x *AuthContext) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *AuthContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type Workflow struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TenantId              string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	WorkflowId            string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	WorkflowType          string                 `protobuf:"bytes,3,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	RiskLevel             string                 `protobuf:"bytes,4,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	RequesterRef          string                 `protobuf:"bytes,5,opt,name=requester_ref,json=requesterRef,proto3" json:"requester_ref,omitempty"`
	RequesterService      string                 `protobuf:"bytes,6,opt,name=requester_service,json=requesterService,proto3" json:"requester_service,omitempty"`
	TargetService         string                 `protobuf:"bytes,7,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"`
	TargetOperation       string                 `protobuf:"bytes,8,opt,name=target_operation,json=targetOperation,proto3" json:"target_operation,omitempty"`
	TargetRefHash         string                 `protobuf:"bytes,9,opt,name=target_ref_hash,json=targetRefHash,proto3" json:"target_ref_hash,omitempty"`
	PayloadSchemaVersion  string                 `protobuf:"bytes,10,opt,name=payload_schema_version,json=payloadSchemaVersion,proto3" json:"payload_schema_version,omitempty"`
	PayloadRefHash        string                 `protobuf:"bytes,11,opt,name=payload_ref_hash,json=payloadRefHash,proto3" json:"payload_ref_hash,omitempty"`
	ApprovalPolicyRef     string                 `protobuf:"bytes,12,opt,name=approval_policy_ref,json=approvalPolicyRef,proto3" json:"approval_policy_ref,omitempty"`
	TimeoutPolicyRef      string                 `protobuf:"bytes,13,opt,name=timeout_policy_ref,json=timeoutPolicyRef,proto3" json:"timeout_policy_ref,omitempty"`
	CompensationPolicyRef string                 `protobuf:"bytes,14,opt,name=compensation_policy_ref,json=compensationPolicyRef,proto3" json:"compensation_policy_ref,omitempty"`
	ReasonRef             string                 `protobuf:"bytes,15,opt,name=reason_ref,json=reasonRef,proto3" json:"reason_ref,omitempty"`
	EvidenceRefs          []string               `protobuf:"bytes,16,rep,name=evidence_refs,json=evidenceRefs,proto3" json:"evidence_refs,omitempty"`
	Status                string                 `protobuf:"bytes,17,opt,name=status,proto3" json:"status,omitempty"`
	CurrentStepId         string                 `protobuf:"bytes,18,opt,name=current_step_id,json=currentStepId,proto3" json:"current_step_id,omitempty"`
	CorrelationId         string                 `protobuf:"bytes,19,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	CausationId           string                 `protobuf:"bytes,20,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	TraceId               string                 `protobuf:"bytes,21,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	CreatedAtUnixMs       int64                  `protobuf:"varint,22,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	UpdatedAtUnixMs       int64                  `protobuf:"varint,23,opt,name=updated_at_unix_ms,json=updatedAtUnixMs,proto3" json:"updated_at_unix_ms,omitempty"`
	CompletedAtUnixMs     int64                  `protobuf:"varint,24,opt,name=completed_at_unix_ms,json=completedAtUnixMs,proto3" json:"completed_at_unix_ms,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_nexusim_workflow_v1_workflow_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_workflow_v1_workflow_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_nexusim_workflow_v1_workflow_service_proto_rawDescGZIP(), []int{1}
}

func (x *Workflow) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Workflow) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *Workflow) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *Workflow) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *Workflow) GetRequesterRef() string {
	if x != nil {
		return x.RequesterRef
	}
	return ""
}

func (x *Workflow) GetRequesterService() string {
	if x != nil {
		return x.RequesterService
	}
	return ""
}

func (x *Workflow) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

func (x *Workflow) GetTargetOperation() string {
	if x != nil {
		return x.TargetOperation
	}
	return ""
}

func (x *Workflow) GetTargetRefHash() string {
	if x != nil {
		return x.TargetRefHash
	}
	return ""
}

func (x *Workflow) GetPayloadSchemaVersion() string {
	if x != nil {
		return x.PayloadSchemaVersion
	}
	return ""
}

func (x *Workflow) GetPayloadRefHash() string {
	if x != nil {
		return x.PayloadRefHash
	}
	return ""
}

func (x *Workflow) GetApprovalPolicyRef() string {
	if x != nil {
		return x.ApprovalPolicyRef
	}
	return ""
}

func (x *Workflow) GetTimeoutPolicyRef() string {
	if x != nil {
		return x.TimeoutPolicyRef
	}
	return ""
}

func (x *Workflow) GetCompensationPolicyRef() string {
	if x != nil {
		return x.CompensationPolicyRef
	}
	return ""
}

func (x *Workflow) GetReasonRef() string {
	if x != nil {
		return x.ReasonRef
	}
	return ""
}

func (x *Workflow) GetEvidenceRefs() []string {
	if x != nil {
		return x.EvidenceRefs
	}
	return nil
}

func (x *Workflow) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Workflow) GetCurrentStepId() string {
	if x != nil {
		return x.CurrentStepId
	}
	return ""
}

func (x *Workflow) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Workflow) GetCausationId() string {
	if x != nil {
		return x.CausationId
	}
	return ""
}

func (x *Workflow) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Workflow) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

func (x *Workflow) GetUpdatedAtUnixMs() int64 {
	if x != nil {
		return x.UpdatedAtUnixMs
	}
	return 0
}

func (x *Workflow) GetCompletedAtUnixMs() int64 {
	if x != nil {
		return x.CompletedAtUnixMs
	}
	return 0
}

type WorkflowDecision struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TenantId          string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	WorkflowId        string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	DecisionId        string                 `protobuf:"bytes,3,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	StepId            string                 `protobuf:"bytes,4,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	DeciderRef        string                 `protobuf:"bytes,5,opt,name=decider_ref,json=deciderRef,proto3" json:"decider_ref,omitempty"`
	DecisionType      string                 `protobuf:"bytes,6,opt,name=decision_type,json=decisionType,proto3" json:"decision_type,omitempty"`
	DecisionPolicyRef string                 `protobuf:"bytes,7,opt,name=decision_policy_ref,json=decisionPolicyRef,proto3" json:"decision_policy_ref,omitempty"`
	ReasonRef         string                 `protobuf:"bytes,8,opt,name=reason_ref,json=reasonRef,proto3" json:"reason_ref,omitempty"`
	EvidenceRefs      []string               `protobuf:"bytes,9,rep,name=evidence_refs,json=evidenceRefs,proto3" json:"evidence_refs,omitempty"`
	CreatedAtUnixMs   int64                  `protobuf:"varint,10,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WorkflowDecision) Reset() {
	*x = WorkflowDecision{}
	mi := &file_nexusim_workflow_v1_workflow_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowDecision) ProtoMessage() {}

func (x *WorkflowDecision) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_workflow_v1_workflow_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowDecision.ProtoReflect.Descriptor instead.
func (*WorkflowDecision) Descriptor() ([]byte, []int) {
	return file_nexusim_workflow_v1_workflow_service_proto_rawDescGZIP(), []int{2}
}

func (x *WorkflowDecision) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *WorkflowDecision) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowDecision) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *WorkflowDecision) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *WorkflowDecision) GetDeciderRef() string {
	if x != nil {
		return x.DeciderRef
	}
	return ""
}

func (x *WorkflowDecision) GetDecisionType() string {
	if x != nil {
		return x.DecisionType
	}
	return ""
}

func (x *WorkflowDecision) GetDecisionPolicyRef() string {
	if x != nil {
		return x.DecisionPolicyRef
	}
	return ""
}

func (x *WorkflowDecision) GetReasonRef() string {
	if x != nil {
		return x.ReasonRef
	}
	return ""
}

func (x *WorkflowDecision) GetEvidenceRefs() []string {
	if x != nil {
		return x.EvidenceRefs
	}
	return nil
}

func (x *WorkflowDecision) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

type WorkflowCompensationInstruction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	InstructionId   string                 `protobuf:"bytes,2,opt,name=instruction_id,json=instructionId,proto3" json:"instruction_id,omitempty"`
	WorkflowId      string                 `protobuf:"bytes,3,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	PayloadRefHash  string                 `protobuf:"bytes,4,opt,name=payload_ref_hash,json=payloadRefHash,proto3" json:"payload_ref_hash,omitempty"`
	TargetService   string                 `protobuf:"bytes,5,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"`
	TargetOperation string                 `protobuf:"bytes,6,opt,name=target_operation,json=targetOperation,proto3" json:"target_operation,omitempty"`
	InstructionType string                 `protobuf:"bytes,7,opt,name=instruction_type,json=instructionType,proto3" json:"instruction_type,omitempty"`
	Environment     string                 `protobuf:"bytes,8,opt,name=environment,proto3" json:"environment,omitempty"`
	ConfigKind      string                 `protobuf:"bytes,9,opt,name=config_kind,json=configKind,proto3" json:"config_kind,omitempty"`
	BundleKey       string                 `protobuf:"bytes,10,opt,name=bundle_key,json=bundleKey,proto3" json:"bundle_key,omitempty"`
	TargetVersion   string                 `protobuf:"bytes,11,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	OperatorRef     string                 `protobuf:"bytes,12,opt,name=operator_ref,json=operatorRef,proto3" json:"operator_ref,omitempty"`
	ReasonRef       string                 `protobuf:"bytes,13,opt,name=reason_ref,json=reasonRef,proto3" json:"reason_ref,omitempty"`
	Status          string                 `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAtUnixMs int64                  `protobuf:"varint,15,opt,name=created_at_unix_ms,json=createdAtUnixMs,proto3" json:"created_at_unix_ms,omitempty"`
	UpdatedAtUnixMs int64                  `protobuf:"varint,16,opt,name=updated_at_unix_ms,json=updatedAtUnixMs,proto3" json:"updated_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkflowCompensationInstruction) Reset() {
	*x = WorkflowCompensationInstruction{}
	mi := &file_nexusim_workflow_v1_workflow_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowCompensationInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowCompensationInstruction) ProtoMessage() {}

func (x *WorkflowCompensationInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_workflow_v1_workflow_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowCompensationInstruction.ProtoReflect.Descriptor instead.
func (*WorkflowCompensationInstruction) Descriptor() ([]byte, []int) {
	return file_nexusim_workflow_v1_workflow_service_proto_rawDescGZIP(), []int{3}
}

func (x *WorkflowCompensationInstruction) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *WorkflowCompensationInstruction) GetInstructionId() string {
	if x != nil {
		return x.InstructionId
	}
	return ""
}

func (x *WorkflowCompensationInstruction) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowCompensationInstruction) GetPayloadRefHash() string {
	if x != nil {
		return x.PayloadRefHash
	}
	return ""
}

func (x *WorkflowCompensationInstruction) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

func (x *WorkflowCompensationInstruction) GetTargetOperation() string {
	if x != nil {
		return x.TargetOperation
	}
	return ""
}

func (x *WorkflowCompensationInstruction) GetInstructionType() string {
	if x != nil {
		return x.InstructionType
	}
	return ""
}

func (x *WorkflowCompensationInstruction) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *WorkflowCompensationInstruction) GetConfigKind() string {
	if x != nil {
		return x.ConfigKind
	}
	return ""
}

func (x *WorkflowCompensationInstruction) GetBundleKey() string {
	if x != nil {
		return x.BundleKey
	}
	return ""
}

func (x *WorkflowCompensationInstruction) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

func (x *WorkflowCompensationInstruction) GetOperatorRef() string {
	if x != nil {
		return x.OperatorRef
	}
	return ""
}

func (x *WorkflowCompensationInstruction) GetReasonRef() string {
	if x != nil {
		return x.ReasonRef
	}
	return ""
}

func (x *WorkflowCompensationInstruction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkflowCompensationInstruction) GetCreatedAtUnixMs() int64 {
	if x != nil {
		return x.CreatedAtUnixMs
	}
	return 0
}

func (x *WorkflowCompensationInstruction) GetUpdatedAtUnixMs() int64 {
	if x != nil {
		return x.UpdatedAtUnixMs
	}
	return 0
}

type CreateWorkflowRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AuthContext           *AuthContext           `protobuf:"bytes,1,opt,name=auth_context,json=authContext,proto3" json:"auth_context,omitempty"`
	RequesterRef          string                 `protobuf:"bytes,2,opt,name=requester_ref,json=requesterRef,proto3" json:"requester_ref,omitempty"`
	RequesterService      string                 `protobuf:"bytes,3,opt,name=requester_service,json=requesterService,proto3" json:"requester_service,omitempty"`
	WorkflowType          string                 `protobuf:"bytes,4,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	RiskLevel             string                 `protobuf:"bytes,5,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	TargetRefHash         string                 `protobuf:"bytes,6,opt,name=target_ref_hash,json=targetRefHash,proto3" json:"target_ref_hash,omitempty"`
	TargetService         string                 `protobuf:"bytes,7,opt,name=target_service,json=targetService,proto3" json:"target_service,omitempty"`
	TargetOperation       string                 `protobuf:"bytes,8,opt,name=target_operation,json=targetOperation,proto3" json:"target_operation,omitempty"`
	ApprovalPolicyRef     string                 `protobuf:"bytes,9,opt,name=approval_policy_ref,json=approvalPolicyRef,proto3" json:"approval_policy_ref,omitempty"`
	TimeoutPolicyRef      string                 `protobuf:"bytes,10,opt,name=timeout_policy_ref,json=timeoutPolicyRef,proto3" json:"timeout_policy_ref,omitempty"`
	CompensationPolicyRef string                 `protobuf:"bytes,11,opt,name=compensation_policy_ref,json=compensationPolicyRef,proto3" json:"compensation_policy_ref,omitempty"`
	PayloadSchemaVersion  string                 `protobuf:"bytes,12,opt,name=payload_schema_version,json=payloadSchemaVersion,proto3" json:"payload_schema_version,omitempty"`
	PayloadRefHash        string                 `protobuf:"bytes,13,opt,name=payload_ref_hash,json=payloadRefHash,proto3" json:"payload_ref_hash,omitempty"`
	ReasonRef             string                 `protobuf:"bytes,14,opt,name=reason_ref,json=reasonRef,proto3" json:"reason_ref,omitempty"`
	EvidenceRefs          []string               `protobuf:"bytes,15,rep,name=evidence_refs,json=evidenceRefs,proto3" json:"evidence_refs,omitempty"`
	IdempotencyKey        string                 `protobuf:"bytes,16,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	CorrelationId         string                 `protobuf:"bytes,17,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	CausationId           string                 `protobuf:"bytes,18,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	TraceId               string                 `protobuf:"bytes,19,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateWorkflowRequest) Reset() {
	*x = CreateWorkflowRequest{}
	mi := &file_nexusim_workflow_v1_workflow_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkflowRequest) ProtoMessage() {}

func (x *CreateWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_workflow_v1_workflow_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkflowRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_nexusim_workflow_v1_workflow_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateWorkflowRequest) GetAuthContext() *AuthContext {
	if x != nil {
		return x.AuthContext
	}
	return nil
}

func (x *CreateWorkflowRequest) GetRequesterRef() string {
	if x != nil {
		return x.RequesterRef
	}
	return ""
}

func (x *CreateWorkflowRequest) GetRequesterService() string {
	if x != nil {
		return x.RequesterService
	}
	return ""
}

func (x *CreateWorkflowRequest) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *CreateWorkflowRequest) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *CreateWorkflowRequest) GetTargetRefHash() string {
	if x != nil {
		return x.TargetRefHash
	}
	return ""
}

func (x *CreateWorkflowRequest) GetTargetService() string {
	if x != nil {
		return x.TargetService
	}
	return ""
}

func (x *CreateWorkflowRequest) GetTargetOperation() string {
	if x != nil {
		return x.TargetOperation
	}
	return ""
}

func (x *CreateWorkflowRequest) GetApprovalPolicyRef() string {
	if x != nil {
		return x.ApprovalPolicyRef
	}
	return ""
}

func (x *CreateWorkflowRequest) GetTimeoutPolicyRef() string {
	if x != nil {
		return x.TimeoutPolicyRef
	}
	return ""
}

func (x *CreateWorkflowRequest) GetCompensationPolicyRef() string {
	if x != nil {
		return x.CompensationPolicyRef
	}
	return ""
}

func (x *CreateWorkflowRequest) GetPayloadSchemaVersion() string {
	if x != nil {
		return x.PayloadSchemaVersion
	}
	return ""
}

func (x *CreateWorkflowRequest) GetPayloadRefHash() string {
	if x != nil {
		return x.PayloadRefHash
	}
	return ""
}

func (x *CreateWorkflowRequest) GetReasonRef() string {
	if x != nil {
		return x.ReasonRef
	}
	return ""
}

func (x *CreateWorkflowRequest) GetEvidenceRefs() []string {
	if x != nil {
		return x.EvidenceRefs
	}
	return nil
}

func (x *CreateWorkflowRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateWorkflowRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *CreateWorkflowRequest) GetCausationId() string {
	if x != nil {
		return x.CausationId
	}
	return ""
}

func (x *CreateWorkflowRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type CreateWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflow      *Workflow              `protobuf:"bytes,1,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Replayed      bool                   `protobuf:"varint,2,opt,name=replayed,proto3" json:"replayed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkflowResponse) Reset() {
	*x = CreateWorkflowResponse{}
	mi := &file_nexusim_workflow_v1_workflow_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkflowResponse) ProtoMessage() {}

func (x *CreateWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_workflow_v1_workflow_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkflowResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_nexusim_workflow_v1_workflow_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateWorkflowResponse) GetWorkflow() *Workflow {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *CreateWorkflowResponse) GetReplayed() bool {
	if x != nil {
		return x.Replayed
	}
	return false
}

type RecordWorkflowDecisionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AuthContext       *AuthContext           `protobuf:"bytes,1,opt,name=auth_context,json=authContext,proto3" json:"auth_context,omitempty"`
	WorkflowId        string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	StepId            string                 `protobuf:"bytes,3,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	DecisionType      string                 `protobuf:"bytes,4,opt,name=decision_type,json=decisionType,proto3" json:"decision_type,omitempty"`
	DeciderRef        string                 `protobuf:"bytes,5,opt,name=decider_ref,json=deciderRef,proto3" json:"decider_ref,omitempty"`
	DecisionPolicyRef string                 `protobuf:"bytes,6,opt,name=decision_policy_ref,json=decisionPolicyRef,proto3" json:"decision_policy_ref,omitempty"`
	ReasonRef         string                 `protobuf:"bytes,7,opt,name=reason_ref,json=reasonRef,proto3" json:"reason_ref,omitempty"`
	EvidenceRefs      []string               `protobuf:"bytes,8,rep,name=evidence_refs,json=evidenceRefs,proto3" json:"evidence_refs,omitempty"`
	IdempotencyKey    string                 `protobuf:"bytes,9,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	CorrelationId     string                 `protobuf:"bytes,10,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	CausationId       string                 `protobuf:"bytes,11,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	TraceId           string                 `protobuf:"bytes,12,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RecordWorkflowDecisionRequest) Reset() {
	*x = RecordWorkflowDecisionRequest{}
	mi := &file_nexusim_workflow_v1_workflow_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordWorkflowDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordWorkflowDecisionRequest) ProtoMessage() {}

func (x *RecordWorkflowDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_workflow_v1_workflow_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordWorkflowDecisionRequest.ProtoReflect.Descriptor instead.
func (*RecordWorkflowDecisionRequest) Descriptor() ([]byte, []int) {
	return file_nexusim_workflow_v1_workflow_service_proto_rawDescGZIP(), []int{6}
}

func (x *RecordWorkflowDecisionRequest) GetAuthContext() *AuthContext {
	if x != nil {
		return x.AuthContext
	}
	return nil
}

func (x *RecordWorkflowDecisionRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *RecordWorkflowDecisionRequest) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *RecordWorkflowDecisionRequest) GetDecisionType() string {
	if x != nil {
		return x.DecisionType
	}
	return ""
}

func (x *RecordWorkflowDecisionRequest) GetDeciderRef() string {
	if x != nil {
		return x.DeciderRef
	}
	return ""
}

func (x *RecordWorkflowDecisionRequest) GetDecisionPolicyRef() string {
	if x != nil {
		return x.DecisionPolicyRef
	}
	return ""
}

func (x *RecordWorkflowDecisionRequest) GetReasonRef() string {
	if x != nil {
		return x.ReasonRef
	}
	return ""
}

func (x *RecordWorkflowDecisionRequest) GetEvidenceRefs() []string {
	if x != nil {
		return x.EvidenceRefs
	}
	return nil
}

func (x *RecordWorkflowDecisionRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *RecordWorkflowDecisionRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RecordWorkflowDecisionRequest) GetCausationId() string {
	if x != nil {
		return x.CausationId
	}
	return ""
}

func (x *RecordWorkflowDecisionRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type RecordWorkflowDecisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflow      *Workflow              `protobuf:"bytes,1,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Decision      *WorkflowDecision      `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"`
	Replayed      bool                   `protobuf:"varint,3,opt,name=replayed,proto3" json:"replayed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordWorkflowDecisionResponse) Reset() {
	*x = RecordWorkflowDecisionResponse{}
	mi := &file_nexusim_workflow_v1_workflow_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordWorkflowDecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordWorkflowDecisionResponse) ProtoMessage() {}

func (x *RecordWorkflowDecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_workflow_v1_workflow_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordWorkflowDecisionResponse.ProtoReflect.Descriptor instead.
func (*RecordWorkflowDecisionResponse) Descriptor() ([]byte, []int) {
	return file_nexusim_workflow_v1_workflow_service_proto_rawDescGZIP(), []int{7}
}

func (x *RecordWorkflowDecisionResponse) GetWorkflow() *Workflow {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *RecordWorkflowDecisionResponse) GetDecision() *WorkflowDecision {
	if x != nil {
		return x.Decision
	}
	return nil
}

func (x *RecordWorkflowDecisionResponse) GetReplayed() bool {
	if x != nil {
		return x.Replayed
	}
	return false
}

type GetWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthContext   *AuthContext           `protobuf:"bytes,1,opt,name=auth_context,json=authContext,proto3" json:"auth_context,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowRequest) Reset() {
	*x = GetWorkflowRequest{}
	mi := &file_nexusim_workflow_v1_workflow_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowRequest) ProtoMessage() {}

func (x *GetWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_workflow_v1_workflow_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_nexusim_workflow_v1_workflow_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetWorkflowRequest) GetAuthContext() *AuthContext {
	if x != nil {
		return x.AuthContext
	}
	return nil
}

func (x *GetWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type GetWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflow      *Workflow              `protobuf:"bytes,1,opt,name=workflow,proto3" json:"workflow,omitempty"`
	Decisions     []*WorkflowDecision    `protobuf:"bytes,2,rep,name=decisions,proto3" json:"decisions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowResponse) Reset() {
	*x = GetWorkflowResponse{}
	mi := &file_nexusim_workflow_v1_workflow_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowResponse) ProtoMessage() {}

func (x *GetWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_workflow_v1_workflow_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowResponse.ProtoReflect.Descriptor instead.
func (*GetWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_nexusim_workflow_v1_workflow_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetWorkflowResponse) GetWorkflow() *Workflow {
	if x != nil {
		return x.Workflow
	}
	return nil
}

func (x *GetWorkflowResponse) GetDecisions() []*WorkflowDecision {
	if x != nil {
		return x.Decisions
	}
	return nil
}

type ListWorkflowCompensationInstructionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthContext   *AuthContext           `protobuf:"bytes,1,opt,name=auth_context,json=authContext,proto3" json:"auth_context,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowCompensationInstructionsRequest) Reset() {
	*x = ListWorkflowCompensationInstructionsRequest{}
	mi := &file_nexusim_workflow_v1_workflow_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowCompensationInstructionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowCompensationInstructionsRequest) ProtoMessage() {}

func (x *ListWorkflowCompensationInstructionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_workflow_v1_workflow_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowCompensationInstructionsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkflowCompensationInstructionsRequest) Descriptor() ([]byte, []int) {
	return file_nexusim_workflow_v1_workflow_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListWorkflowCompensationInstructionsRequest) GetAuthContext() *AuthContext {
	if x != nil {
		return x.AuthContext
	}
	return nil
}

func (x *ListWorkflowCompensationInstructionsRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ListWorkflowCompensationInstructionsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListWorkflowCompensationInstructionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListWorkflowCompensationInstructionsResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Instructions  []*WorkflowCompensationInstruction `protobuf:"bytes,1,rep,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowCompensationInstructionsResponse) Reset() {
	*x = ListWorkflowCompensationInstructionsResponse{}
	mi := &file_nexusim_workflow_v1_workflow_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowCompensationInstructionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowCompensationInstructionsResponse) ProtoMessage() {}

func (x *ListWorkflowCompensationInstructionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexusim_workflow_v1_workflow_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowCompensationInstructionsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkflowCompensationInstructionsResponse) Descriptor() ([]byte, []int) {
	return file_nexusim_workflow_v1_workflow_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListWorkflowCompensationInstructionsResponse) GetInstructions() []*WorkflowCompensationInstruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

var File_nexusim_workflow_v1_workflow_service_proto protoreflect.FileDescriptor

const file_nexusim_workflow_v1_workflow_service_proto_rawDesc = "" +
	"\n" +
	"*nexusim/workflow/v1/workflow_service.proto\x12\x13nexusim.workflow.v1\"\xc3\x01\n" +
	"\vAuthContext\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12!\n" +
	"\finstance_ref\x18\x04 \x01(\tR\vinstanceRef\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\"\xc2\a\n" +
	"\bWorkflow\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12#\n" +
	"\rworkflow_type\x18\x03 \x01(\tR\fworkflowType\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x04 \x01(\tR\triskLevel\x12#\n" +
	"\rrequester_ref\x18\x05 \x01(\tR\frequesterRef\x12+\n" +
	"\x11requester_service\x18\x06 \x01(\tR\x10requesterService\x12%\n" +
	"\x0etarget_service\x18\a \x01(\tR\rtargetService\x12)\n" +
	"\x10target_operation\x18\b \x01(\tR\x0ftargetOperation\x12&\n" +
	"\x0ftarget_ref_hash\x18\t \x01(\tR\rtargetRefHash\x124\n" +
	"\x16payload_schema_version\x18\n" +
	" \x01(\tR\x14payloadSchemaVersion\x12(\n" +
	"\x10payload_ref_hash\x18\v \x01(\tR\x0epayloadRefHash\x12.\n" +
	"\x13approval_policy_ref\x18\f \x01(\tR\x11approvalPolicyRef\x12,\n" +
	"\x12timeout_policy_ref\x18\r \x01(\tR\x10timeoutPolicyRef\x126\n" +
	"\x17compensation_policy_ref\x18\x0e \x01(\tR\x15compensationPolicyRef\x12\x1d\n" +
	"\n" +
	"reason_ref\x18\x0f \x01(\tR\treasonRef\x12#\n" +
	"\revidence_refs\x18\x10 \x03(\tR\fevidenceRefs\x12\x16\n" +
	"\x06status\x18\x11 \x01(\tR\x06status\x12&\n" +
	"\x0fcurrent_step_id\x18\x12 \x01(\tR\rcurrentStepId\x12%\n" +
	"\x0ecorrelation_id\x18\x13 \x01(\tR\rcorrelationId\x12!\n" +
	"\fcausation_id\x18\x14 \x01(\tR\vcausationId\x12\x19\n" +
	"\btrace_id\x18\x15 \x01(\tR\atraceId\x12+\n" +
	"\x12created_at_unix_ms\x18\x16 \x01(\x03R\x0fcreatedAtUnixMs\x12+\n" +
	"\x12updated_at_unix_ms\x18\x17 \x01(\x03R\x0fupdatedAtUnixMs\x12/\n" +
	"\x14completed_at_unix_ms\x18\x18 \x01(\x03R\x11completedAtUnixMs\"\xf1\x02\n" +
	"\x10WorkflowDecision\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x1f\n" +
	"\vdecision_id\x18\x03 \x01(\tR\n" +
	"decisionId\x12\x17\n" +
	"\astep_id\x18\x04 \x01(\tR\x06stepId\x12\x1f\n" +
	"\vdecider_ref\x18\x05 \x01(\tR\n" +
	"deciderRef\x12#\n" +
	"\rdecision_type\x18\x06 \x01(\tR\fdecisionType\x12.\n" +
	"\x13decision_policy_ref\x18\a \x01(\tR\x11decisionPolicyRef\x12\x1d\n" +
	"\n" +
	"reason_ref\x18\b \x01(\tR\treasonRef\x12#\n" +
	"\revidence_refs\x18\t \x03(\tR\fevidenceRefs\x12+\n" +
	"\x12created_at_unix_ms\x18\n" +
	" \x01(\x03R\x0fcreatedAtUnixMs\"\xea\x04\n" +
	"\x1fWorkflowCompensationInstruction\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12%\n" +
	"\x0einstruction_id\x18\x02 \x01(\tR\rinstructionId\x12\x1f\n" +
	"\vworkflow_id\x18\x03 \x01(\tR\n" +
	"workflowId\x12(\n" +
	"\x10payload_ref_hash\x18\x04 \x01(\tR\x0epayloadRefHash\x12%\n" +
	"\x0etarget_service\x18\x05 \x01(\tR\rtargetService\x12)\n" +
	"\x10target_operation\x18\x06 \x01(\tR\x0ftargetOperation\x12)\n" +
	"\x10instruction_type\x18\a \x01(\tR\x0finstructionType\x12 \n" +
	"\venvironment\x18\b \x01(\tR\venvironment\x12\x1f\n" +
	"\vconfig_kind\x18\t \x01(\tR\n" +
	"configKind\x12\x1d\n" +
	"\n" +
	"bundle_key\x18\n" +
	" \x01(\tR\tbundleKey\x12%\n" +
	"\x0etarget_version\x18\v \x01(\tR\rtargetVersion\x12!\n" +
	"\foperator_ref\x18\f \x01(\tR\voperatorRef\x12\x1d\n" +
	"\n" +
	"reason_ref\x18\r \x01(\tR\treasonRef\x12\x16\n" +
	"\x06status\x18\x0e \x01(\tR\x06status\x12+\n" +
	"\x12created_at_unix_ms\x18\x0f \x01(\x03R\x0fcreatedAtUnixMs\x12+\n" +
	"\x12updated_at_unix_ms\x18\x10 \x01(\x03R\x0fupdatedAtUnixMs\"\xb4\x06\n" +
	"\x15CreateWorkflowRequest\x12C\n" +
	"\fauth_context\x18\x01 \x01(\v2 .nexusim.workflow.v1.AuthContextR\vauthContext\x12#\n" +
	"\rrequester_ref\x18\x02 \x01(\tR\frequesterRef\x12+\n" +
	"\x11requester_service\x18\x03 \x01(\tR\x10requesterService\x12#\n" +
	"\rworkflow_type\x18\x04 \x01(\tR\fworkflowType\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x05 \x01(\tR\triskLevel\x12&\n" +
	"\x0ftarget_ref_hash\x18\x06 \x01(\tR\rtargetRefHash\x12%\n" +
	"\x0etarget_service\x18\a \x01(\tR\rtargetService\x12)\n" +
	"\x10target_operation\x18\b \x01(\tR\x0ftargetOperation\x12.\n" +
	"\x13approval_policy_ref\x18\t \x01(\tR\x11approvalPolicyRef\x12,\n" +
	"\x12timeout_policy_ref\x18\n" +
	" \x01(\tR\x10timeoutPolicyRef\x126\n" +
	"\x17compensation_policy_ref\x18\v \x01(\tR\x15compensationPolicyRef\x124\n" +
	"\x16payload_schema_version\x18\f \x01(\tR\x14payloadSchemaVersion\x12(\n" +
	"\x10payload_ref_hash\x18\r \x01(\tR\x0epayloadRefHash\x12\x1d\n" +
	"\n" +
	"reason_ref\x18\x0e \x01(\tR\treasonRef\x12#\n" +
	"\revidence_refs\x18\x0f \x03(\tR\fevidenceRefs\x12'\n" +
	"\x0fidempotency_key\x18\x10 \x01(\tR\x0eidempotencyKey\x12%\n" +
	"\x0ecorrelation_id\x18\x11 \x01(\tR\rcorrelationId\x12!\n" +
	"\fcausation_id\x18\x12 \x01(\tR\vcausationId\x12\x19\n" +
	"\btrace_id\x18\x13 \x01(\tR\atraceId\"o\n" +
	"\x16CreateWorkflowResponse\x129\n" +
	"\bworkflow\x18\x01 \x01(\v2\x1d.nexusim.workflow.v1.WorkflowR\bworkflow\x12\x1a\n" +
	"\breplayed\x18\x02 \x01(\bR\breplayed\"\xe6\x03\n" +
	"\x1dRecordWorkflowDecisionRequest\x12C\n" +
	"\fauth_context\x18\x01 \x01(\v2 .nexusim.workflow.v1.AuthContextR\vauthContext\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x17\n" +
	"\astep_id\x18\x03 \x01(\tR\x06stepId\x12#\n" +
	"\rdecision_type\x18\x04 \x01(\tR\fdecisionType\x12\x1f\n" +
	"\vdecider_ref\x18\x05 \x01(\tR\n" +
	"deciderRef\x12.\n" +
	"\x13decision_policy_ref\x18\x06 \x01(\tR\x11decisionPolicyRef\x12\x1d\n" +
	"\n" +
	"reason_ref\x18\a \x01(\tR\treasonRef\x12#\n" +
	"\revidence_refs\x18\b \x03(\tR\fevidenceRefs\x12'\n" +
	"\x0fidempotency_key\x18\t \x01(\tR\x0eidempotencyKey\x12%\n" +
	"\x0ecorrelation_id\x18\n" +
	" \x01(\tR\rcorrelationId\x12!\n" +
	"\fcausation_id\x18\v \x01(\tR\vcausationId\x12\x19\n" +
	"\btrace_id\x18\f \x01(\tR\atraceId\"\xba\x01\n" +
	"\x1eRecordWorkflowDecisionResponse\x129\n" +
	"\bworkflow\x18\x01 \x01(\v2\x1d.nexusim.workflow.v1.WorkflowR\bworkflow\x12A\n" +
	"\bdecision\x18\x02 \x01(\v2%.nexusim.workflow.v1.WorkflowDecisionR\bdecision\x12\x1a\n" +
	"\breplayed\x18\x03 \x01(\bR\breplayed\"z\n" +
	"\x12GetWorkflowRequest\x12C\n" +
	"\fauth_context\x18\x01 \x01(\v2 .nexusim.workflow.v1.AuthContextR\vauthContext\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\"\x95\x01\n" +
	"\x13GetWorkflowResponse\x129\n" +
	"\bworkflow\x18\x01 \x01(\v2\x1d.nexusim.workflow.v1.WorkflowR\bworkflow\x12C\n" +
	"\tdecisions\x18\x02 \x03(\v2%.nexusim.workflow.v1.WorkflowDecisionR\tdecisions\"\xc8\x01\n" +
	"+ListWorkflowCompensationInstructionsRequest\x12C\n" +
	"\fauth_context\x18\x01 \x01(\v2 .nexusim.workflow.v1.AuthContextR\vauthContext\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x88\x01\n" +
	",ListWorkflowCompensationInstructionsResponse\x12X\n" +
	"\finstructions\x18\x01 \x03(\v24.nexusim.workflow.v1.WorkflowCompensationInstructionR\finstructions2\x90\x04\n" +
	"\x0fWorkflowService\x12i\n" +
	"\x0eCreateWorkflow\x12*.nexusim.workflow.v1.CreateWorkflowRequest\x1a+.nexusim.workflow.v1.CreateWorkflowResponse\x12\x81\x01\n" +
	"\x16RecordWorkflowDecision\x122.nexusim.workflow.v1.RecordWorkflowDecisionRequest\x1a3.nexusim.workflow.v1.RecordWorkflowDecisionResponse\x12`\n" +
	"\vGetWorkflow\x12'.nexusim.workflow.v1.GetWorkflowRequest\x1a(.nexusim.workflow.v1.GetWorkflowResponse\x12\xab\x01\n" +
	"$ListWorkflowCompensationInstructions\x12@.nexusim.workflow.v1.ListWorkflowCompensationInstructionsRequest\x1aA.nexusim.workflow.v1.ListWorkflowCompensationInstructionsResponseBAZ?github.com/qsyy0921/IM/api/proto/nexusim/workflow/v1;workflowv1b\x06proto3"

var (
	file_nexusim_workflow_v1_workflow_service_proto_rawDescOnce sync.Once
	file_nexusim_workflow_v1_workflow_service_proto_rawDescData []byte
)

func file_nexusim_workflow_v1_workflow_service_proto_rawDescGZIP() []byte {
	file_nexusim_workflow_v1_workflow_service_proto_rawDescOnce.Do(func() {
		file_nexusim_workflow_v1_workflow_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nexusim_workflow_v1_workflow_service_proto_rawDesc), len(file_nexusim_workflow_v1_workflow_service_proto_rawDesc)))
	})
	return file_nexusim_workflow_v1_workflow_service_proto_rawDescData
}

var file_nexusim_workflow_v1_workflow_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_nexusim_workflow_v1_workflow_service_proto_goTypes = []any{
	(*AuthContext)(nil),                                  // 0: nexusim.workflow.v1.AuthContext
	(*Workflow)(nil),                                     // 1: nexusim.workflow.v1.Workflow
	(*WorkflowDecision)(nil),                             // 2: nexusim.workflow.v1.WorkflowDecision
	(*WorkflowCompensationInstruction)(nil),              // 3: nexusim.workflow.v1.WorkflowCompensationInstruction
	(*CreateWorkflowRequest)(nil),                        // 4: nexusim.workflow.v1.CreateWorkflowRequest
	(*CreateWorkflowResponse)(nil),                       // 5: nexusim.workflow.v1.CreateWorkflowResponse
	(*RecordWorkflowDecisionRequest)(nil),                // 6: nexusim.workflow.v1.RecordWorkflowDecisionRequest
	(*RecordWorkflowDecisionResponse)(nil),               // 7: nexusim.workflow.v1.RecordWorkflowDecisionResponse
	(*GetWorkflowRequest)(nil),                           // 8: nexusim.workflow.v1.GetWorkflowRequest
	(*GetWorkflowResponse)(nil),                          // 9: nexusim.workflow.v1.GetWorkflowResponse
	(*ListWorkflowCompensationInstructionsRequest)(nil),  // 10: nexusim.workflow.v1.ListWorkflowCompensationInstructionsRequest
	(*ListWorkflowCompensationInstructionsResponse)(nil), // 11: nexusim.workflow.v1.ListWorkflowCompensationInstructionsResponse
}
var file_nexusim_workflow_v1_workflow_service_proto_depIdxs = []int32{
	0,  // 0: nexusim.workflow.v1.CreateWorkflowRequest.auth_context:type_name -> nexusim.workflow.v1.AuthContext
	1,  // 1: nexusim.workflow.v1.CreateWorkflowResponse.workflow:type_name -> nexusim.workflow.v1.Workflow
	0,  // 2: nexusim.workflow.v1.RecordWorkflowDecisionRequest.auth_context:type_name -> nexusim.workflow.v1.AuthContext
	1,  // 3: nexusim.workflow.v1.RecordWorkflowDecisionResponse.workflow:type_name -> nexusim.workflow.v1.Workflow
	2,  // 4: nexusim.workflow.v1.RecordWorkflowDecisionResponse.decision:type_name -> nexusim.workflow.v1.WorkflowDecision
	0,  // 5: nexusim.workflow.v1.GetWorkflowRequest.auth_context:type_name -> nexusim.workflow.v1.AuthContext
	1,  // 6: nexusim.workflow.v1.GetWorkflowResponse.workflow:type_name -> nexusim.workflow.v1.Workflow
	2,  // 7: nexusim.workflow.v1.GetWorkflowResponse.decisions:type_name -> nexusim.workflow.v1.WorkflowDecision
	0,  // 8: nexusim.workflow.v1.ListWorkflowCompensationInstructionsRequest.auth_context:type_name -> nexusim.workflow.v1.AuthContext
	3,  // 9: nexusim.workflow.v1.ListWorkflowCompensationInstructionsResponse.instructions:type_name -> nexusim.workflow.v1.WorkflowCompensationInstruction
	4,  // 10: nexusim.workflow.v1.WorkflowService.CreateWorkflow:input_type -> nexusim.workflow.v1.CreateWorkflowRequest
	6,  // 11: nexusim.workflow.v1.WorkflowService.RecordWorkflowDecision:input_type -> nexusim.workflow.v1.RecordWorkflowDecisionRequest
	8,  // 12: nexusim.workflow.v1.WorkflowService.GetWorkflow:input_type -> nexusim.workflow.v1.GetWorkflowRequest
	10, // 13: nexusim.workflow.v1.WorkflowService.ListWorkflowCompensationInstructions:input_type -> nexusim.workflow.v1.ListWorkflowCompensationInstructionsRequest
	5,  // 14: nexusim.workflow.v1.WorkflowService.CreateWorkflow:output_type -> nexusim.workflow.v1.CreateWorkflowResponse
	7,  // 15: nexusim.workflow.v1.WorkflowService.RecordWorkflowDecision:output_type -> nexusim.workflow.v1.RecordWorkflowDecisionResponse
	9,  // 16: nexusim.workflow.v1.WorkflowService.GetWorkflow:output_type -> nexusim.workflow.v1.GetWorkflowResponse
	11, // 17: nexusim.workflow.v1.WorkflowService.ListWorkflowCompensationInstructions:output_type -> nexusim.workflow.v1.ListWorkflowCompensationInstructionsResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_nexusim_workflow_v1_workflow_service_proto_init() }
func file_nexusim_workflow_v1_workflow_service_proto_init() {
	if File_nexusim_workflow_v1_workflow_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nexusim_workflow_v1_workflow_service_proto_rawDesc), len(file_nexusim_workflow_v1_workflow_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nexusim_workflow_v1_workflow_service_proto_goTypes,
		DependencyIndexes: file_nexusim_workflow_v1_workflow_service_proto_depIdxs,
		MessageInfos:      file_nexusim_workflow_v1_workflow_service_proto_msgTypes,
	}.Build()
	File_nexusim_workflow_v1_workflow_service_proto = out.File
	file_nexusim_workflow_v1_workflow_service_proto_goTypes = nil
	file_nexusim_workflow_v1_workflow_service_proto_depIdxs = nil
}
