// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: nexusim/gateway/v1/gateway_service.proto

package gatewayv1

import (
	context "context"
	v1 "github.com/qsyy0921/IM/api/proto/nexusim/conversation/v1"
	v12 "github.com/qsyy0921/IM/api/proto/nexusim/delivery/v1"
	v11 "github.com/qsyy0921/IM/api/proto/nexusim/message/v1"
	v13 "github.com/qsyy0921/IM/api/proto/nexusim/receipt/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayService_CreateMemberChange_FullMethodName        = "/nexusim.gateway.v1.GatewayService/CreateMemberChange"
	GatewayService_GetMemberChange_FullMethodName           = "/nexusim.gateway.v1.GatewayService/GetMemberChange"
	GatewayService_ListConversationMembers_FullMethodName   = "/nexusim.gateway.v1.GatewayService/ListConversationMembers"
	GatewayService_TransferConversationOwner_FullMethodName = "/nexusim.gateway.v1.GatewayService/TransferConversationOwner"
	GatewayService_SendMessage_FullMethodName               = "/nexusim.gateway.v1.GatewayService/SendMessage"
	GatewayService_EditMessage_FullMethodName               = "/nexusim.gateway.v1.GatewayService/EditMessage"
	GatewayService_RevokeMessage_FullMethodName             = "/nexusim.gateway.v1.GatewayService/RevokeMessage"
	GatewayService_DeleteMessage_FullMethodName             = "/nexusim.gateway.v1.GatewayService/DeleteMessage"
	GatewayService_PullInbox_FullMethodName                 = "/nexusim.gateway.v1.GatewayService/PullInbox"
	GatewayService_AckDelivery_FullMethodName               = "/nexusim.gateway.v1.GatewayService/AckDelivery"
	GatewayService_MarkRead_FullMethodName                  = "/nexusim.gateway.v1.GatewayService/MarkRead"
	GatewayService_GetReceiptState_FullMethodName           = "/nexusim.gateway.v1.GatewayService/GetReceiptState"
	GatewayService_ListReceiptStates_FullMethodName         = "/nexusim.gateway.v1.GatewayService/ListReceiptStates"
	GatewayService_ListConversations_FullMethodName         = "/nexusim.gateway.v1.GatewayService/ListConversations"
	GatewayService_ArchiveConversation_FullMethodName       = "/nexusim.gateway.v1.GatewayService/ArchiveConversation"
	GatewayService_PinConversation_FullMethodName           = "/nexusim.gateway.v1.GatewayService/PinConversation"
	GatewayService_MuteConversation_FullMethodName          = "/nexusim.gateway.v1.GatewayService/MuteConversation"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GatewayService is the first-stage public client facade.
// It intentionally excludes service-internal RPCs such as ConversationService.GetSendContext.
type GatewayServiceClient interface {
	CreateMemberChange(ctx context.Context, in *v1.CreateMemberChangeRequest, opts ...grpc.CallOption) (*v1.CreateMemberChangeResponse, error)
	GetMemberChange(ctx context.Context, in *v1.GetMemberChangeRequest, opts ...grpc.CallOption) (*v1.GetMemberChangeResponse, error)
	ListConversationMembers(ctx context.Context, in *v1.ListConversationMembersRequest, opts ...grpc.CallOption) (*v1.ListConversationMembersResponse, error)
	TransferConversationOwner(ctx context.Context, in *v1.TransferConversationOwnerRequest, opts ...grpc.CallOption) (*v1.TransferConversationOwnerResponse, error)
	SendMessage(ctx context.Context, in *v11.SendMessageRequest, opts ...grpc.CallOption) (*v11.SendMessageResponse, error)
	EditMessage(ctx context.Context, in *v11.EditMessageRequest, opts ...grpc.CallOption) (*v11.MessageChangeResponse, error)
	RevokeMessage(ctx context.Context, in *v11.RevokeMessageRequest, opts ...grpc.CallOption) (*v11.MessageChangeResponse, error)
	DeleteMessage(ctx context.Context, in *v11.DeleteMessageRequest, opts ...grpc.CallOption) (*v11.MessageChangeResponse, error)
	PullInbox(ctx context.Context, in *v12.PullInboxRequest, opts ...grpc.CallOption) (*v12.PullInboxResponse, error)
	AckDelivery(ctx context.Context, in *v12.AckDeliveryRequest, opts ...grpc.CallOption) (*v12.AckDeliveryResponse, error)
	MarkRead(ctx context.Context, in *v13.MarkReadRequest, opts ...grpc.CallOption) (*v13.MarkReadResponse, error)
	GetReceiptState(ctx context.Context, in *v13.GetReceiptStateRequest, opts ...grpc.CallOption) (*v13.GetReceiptStateResponse, error)
	ListReceiptStates(ctx context.Context, in *v13.ListReceiptStatesRequest, opts ...grpc.CallOption) (*v13.ListReceiptStatesResponse, error)
	ListConversations(ctx context.Context, in *v13.ListConversationsRequest, opts ...grpc.CallOption) (*v13.ListConversationsResponse, error)
	ArchiveConversation(ctx context.Context, in *v13.ArchiveConversationRequest, opts ...grpc.CallOption) (*v13.ArchiveConversationResponse, error)
	PinConversation(ctx context.Context, in *v13.PinConversationRequest, opts ...grpc.CallOption) (*v13.PinConversationResponse, error)
	MuteConversation(ctx context.Context, in *v13.MuteConversationRequest, opts ...grpc.CallOption) (*v13.MuteConversationResponse, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) CreateMemberChange(ctx context.Context, in *v1.CreateMemberChangeRequest, opts ...grpc.CallOption) (*v1.CreateMemberChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.CreateMemberChangeResponse)
	err := c.cc.Invoke(ctx, GatewayService_CreateMemberChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetMemberChange(ctx context.Context, in *v1.GetMemberChangeRequest, opts ...grpc.CallOption) (*v1.GetMemberChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.GetMemberChangeResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetMemberChange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ListConversationMembers(ctx context.Context, in *v1.ListConversationMembersRequest, opts ...grpc.CallOption) (*v1.ListConversationMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ListConversationMembersResponse)
	err := c.cc.Invoke(ctx, GatewayService_ListConversationMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) TransferConversationOwner(ctx context.Context, in *v1.TransferConversationOwnerRequest, opts ...grpc.CallOption) (*v1.TransferConversationOwnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.TransferConversationOwnerResponse)
	err := c.cc.Invoke(ctx, GatewayService_TransferConversationOwner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) SendMessage(ctx context.Context, in *v11.SendMessageRequest, opts ...grpc.CallOption) (*v11.SendMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v11.SendMessageResponse)
	err := c.cc.Invoke(ctx, GatewayService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) EditMessage(ctx context.Context, in *v11.EditMessageRequest, opts ...grpc.CallOption) (*v11.MessageChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v11.MessageChangeResponse)
	err := c.cc.Invoke(ctx, GatewayService_EditMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) RevokeMessage(ctx context.Context, in *v11.RevokeMessageRequest, opts ...grpc.CallOption) (*v11.MessageChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v11.MessageChangeResponse)
	err := c.cc.Invoke(ctx, GatewayService_RevokeMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) DeleteMessage(ctx context.Context, in *v11.DeleteMessageRequest, opts ...grpc.CallOption) (*v11.MessageChangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v11.MessageChangeResponse)
	err := c.cc.Invoke(ctx, GatewayService_DeleteMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) PullInbox(ctx context.Context, in *v12.PullInboxRequest, opts ...grpc.CallOption) (*v12.PullInboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v12.PullInboxResponse)
	err := c.cc.Invoke(ctx, GatewayService_PullInbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) AckDelivery(ctx context.Context, in *v12.AckDeliveryRequest, opts ...grpc.CallOption) (*v12.AckDeliveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v12.AckDeliveryResponse)
	err := c.cc.Invoke(ctx, GatewayService_AckDelivery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) MarkRead(ctx context.Context, in *v13.MarkReadRequest, opts ...grpc.CallOption) (*v13.MarkReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v13.MarkReadResponse)
	err := c.cc.Invoke(ctx, GatewayService_MarkRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetReceiptState(ctx context.Context, in *v13.GetReceiptStateRequest, opts ...grpc.CallOption) (*v13.GetReceiptStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v13.GetReceiptStateResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetReceiptState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ListReceiptStates(ctx context.Context, in *v13.ListReceiptStatesRequest, opts ...grpc.CallOption) (*v13.ListReceiptStatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v13.ListReceiptStatesResponse)
	err := c.cc.Invoke(ctx, GatewayService_ListReceiptStates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ListConversations(ctx context.Context, in *v13.ListConversationsRequest, opts ...grpc.CallOption) (*v13.ListConversationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v13.ListConversationsResponse)
	err := c.cc.Invoke(ctx, GatewayService_ListConversations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ArchiveConversation(ctx context.Context, in *v13.ArchiveConversationRequest, opts ...grpc.CallOption) (*v13.ArchiveConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v13.ArchiveConversationResponse)
	err := c.cc.Invoke(ctx, GatewayService_ArchiveConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) PinConversation(ctx context.Context, in *v13.PinConversationRequest, opts ...grpc.CallOption) (*v13.PinConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v13.PinConversationResponse)
	err := c.cc.Invoke(ctx, GatewayService_PinConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) MuteConversation(ctx context.Context, in *v13.MuteConversationRequest, opts ...grpc.CallOption) (*v13.MuteConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v13.MuteConversationResponse)
	err := c.cc.Invoke(ctx, GatewayService_MuteConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility.
//
// GatewayService is the first-stage public client facade.
// It intentionally excludes service-internal RPCs such as ConversationService.GetSendContext.
type GatewayServiceServer interface {
	CreateMemberChange(context.Context, *v1.CreateMemberChangeRequest) (*v1.CreateMemberChangeResponse, error)
	GetMemberChange(context.Context, *v1.GetMemberChangeRequest) (*v1.GetMemberChangeResponse, error)
	ListConversationMembers(context.Context, *v1.ListConversationMembersRequest) (*v1.ListConversationMembersResponse, error)
	TransferConversationOwner(context.Context, *v1.TransferConversationOwnerRequest) (*v1.TransferConversationOwnerResponse, error)
	SendMessage(context.Context, *v11.SendMessageRequest) (*v11.SendMessageResponse, error)
	EditMessage(context.Context, *v11.EditMessageRequest) (*v11.MessageChangeResponse, error)
	RevokeMessage(context.Context, *v11.RevokeMessageRequest) (*v11.MessageChangeResponse, error)
	DeleteMessage(context.Context, *v11.DeleteMessageRequest) (*v11.MessageChangeResponse, error)
	PullInbox(context.Context, *v12.PullInboxRequest) (*v12.PullInboxResponse, error)
	AckDelivery(context.Context, *v12.AckDeliveryRequest) (*v12.AckDeliveryResponse, error)
	MarkRead(context.Context, *v13.MarkReadRequest) (*v13.MarkReadResponse, error)
	GetReceiptState(context.Context, *v13.GetReceiptStateRequest) (*v13.GetReceiptStateResponse, error)
	ListReceiptStates(context.Context, *v13.ListReceiptStatesRequest) (*v13.ListReceiptStatesResponse, error)
	ListConversations(context.Context, *v13.ListConversationsRequest) (*v13.ListConversationsResponse, error)
	ArchiveConversation(context.Context, *v13.ArchiveConversationRequest) (*v13.ArchiveConversationResponse, error)
	PinConversation(context.Context, *v13.PinConversationRequest) (*v13.PinConversationResponse, error)
	MuteConversation(context.Context, *v13.MuteConversationRequest) (*v13.MuteConversationResponse, error)
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServiceServer struct{}

func (UnimplementedGatewayServiceServer) CreateMemberChange(context.Context, *v1.CreateMemberChangeRequest) (*v1.CreateMemberChangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMemberChange not implemented")
}
func (UnimplementedGatewayServiceServer) GetMemberChange(context.Context, *v1.GetMemberChangeRequest) (*v1.GetMemberChangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMemberChange not implemented")
}
func (UnimplementedGatewayServiceServer) ListConversationMembers(context.Context, *v1.ListConversationMembersRequest) (*v1.ListConversationMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConversationMembers not implemented")
}
func (UnimplementedGatewayServiceServer) TransferConversationOwner(context.Context, *v1.TransferConversationOwnerRequest) (*v1.TransferConversationOwnerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferConversationOwner not implemented")
}
func (UnimplementedGatewayServiceServer) SendMessage(context.Context, *v11.SendMessageRequest) (*v11.SendMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedGatewayServiceServer) EditMessage(context.Context, *v11.EditMessageRequest) (*v11.MessageChangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EditMessage not implemented")
}
func (UnimplementedGatewayServiceServer) RevokeMessage(context.Context, *v11.RevokeMessageRequest) (*v11.MessageChangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeMessage not implemented")
}
func (UnimplementedGatewayServiceServer) DeleteMessage(context.Context, *v11.DeleteMessageRequest) (*v11.MessageChangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMessage not implemented")
}
func (UnimplementedGatewayServiceServer) PullInbox(context.Context, *v12.PullInboxRequest) (*v12.PullInboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PullInbox not implemented")
}
func (UnimplementedGatewayServiceServer) AckDelivery(context.Context, *v12.AckDeliveryRequest) (*v12.AckDeliveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AckDelivery not implemented")
}
func (UnimplementedGatewayServiceServer) MarkRead(context.Context, *v13.MarkReadRequest) (*v13.MarkReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkRead not implemented")
}
func (UnimplementedGatewayServiceServer) GetReceiptState(context.Context, *v13.GetReceiptStateRequest) (*v13.GetReceiptStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReceiptState not implemented")
}
func (UnimplementedGatewayServiceServer) ListReceiptStates(context.Context, *v13.ListReceiptStatesRequest) (*v13.ListReceiptStatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListReceiptStates not implemented")
}
func (UnimplementedGatewayServiceServer) ListConversations(context.Context, *v13.ListConversationsRequest) (*v13.ListConversationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConversations not implemented")
}
func (UnimplementedGatewayServiceServer) ArchiveConversation(context.Context, *v13.ArchiveConversationRequest) (*v13.ArchiveConversationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArchiveConversation not implemented")
}
func (UnimplementedGatewayServiceServer) PinConversation(context.Context, *v13.PinConversationRequest) (*v13.PinConversationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PinConversation not implemented")
}
func (UnimplementedGatewayServiceServer) MuteConversation(context.Context, *v13.MuteConversationRequest) (*v13.MuteConversationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MuteConversation not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}
func (UnimplementedGatewayServiceServer) testEmbeddedByValue()                        {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_CreateMemberChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.CreateMemberChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).CreateMemberChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_CreateMemberChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).CreateMemberChange(ctx, req.(*v1.CreateMemberChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetMemberChange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetMemberChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetMemberChange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetMemberChange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetMemberChange(ctx, req.(*v1.GetMemberChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ListConversationMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ListConversationMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ListConversationMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ListConversationMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ListConversationMembers(ctx, req.(*v1.ListConversationMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_TransferConversationOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.TransferConversationOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).TransferConversationOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_TransferConversationOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).TransferConversationOwner(ctx, req.(*v1.TransferConversationOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v11.SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).SendMessage(ctx, req.(*v11.SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_EditMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v11.EditMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).EditMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_EditMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).EditMessage(ctx, req.(*v11.EditMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_RevokeMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v11.RevokeMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).RevokeMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_RevokeMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).RevokeMessage(ctx, req.(*v11.RevokeMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v11.DeleteMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).DeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_DeleteMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).DeleteMessage(ctx, req.(*v11.DeleteMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_PullInbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v12.PullInboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).PullInbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_PullInbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).PullInbox(ctx, req.(*v12.PullInboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_AckDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v12.AckDeliveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).AckDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_AckDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).AckDelivery(ctx, req.(*v12.AckDeliveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_MarkRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v13.MarkReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).MarkRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_MarkRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).MarkRead(ctx, req.(*v13.MarkReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetReceiptState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v13.GetReceiptStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetReceiptState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetReceiptState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetReceiptState(ctx, req.(*v13.GetReceiptStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ListReceiptStates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v13.ListReceiptStatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ListReceiptStates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ListReceiptStates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ListReceiptStates(ctx, req.(*v13.ListReceiptStatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ListConversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v13.ListConversationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ListConversations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ListConversations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ListConversations(ctx, req.(*v13.ListConversationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ArchiveConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v13.ArchiveConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ArchiveConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ArchiveConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ArchiveConversation(ctx, req.(*v13.ArchiveConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_PinConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v13.PinConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).PinConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_PinConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).PinConversation(ctx, req.(*v13.PinConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_MuteConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v13.MuteConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).MuteConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_MuteConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).MuteConversation(ctx, req.(*v13.MuteConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexusim.gateway.v1.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMemberChange",
			Handler:    _GatewayService_CreateMemberChange_Handler,
		},
		{
			MethodName: "GetMemberChange",
			Handler:    _GatewayService_GetMemberChange_Handler,
		},
		{
			MethodName: "ListConversationMembers",
			Handler:    _GatewayService_ListConversationMembers_Handler,
		},
		{
			MethodName: "TransferConversationOwner",
			Handler:    _GatewayService_TransferConversationOwner_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _GatewayService_SendMessage_Handler,
		},
		{
			MethodName: "EditMessage",
			Handler:    _GatewayService_EditMessage_Handler,
		},
		{
			MethodName: "RevokeMessage",
			Handler:    _GatewayService_RevokeMessage_Handler,
		},
		{
			MethodName: "DeleteMessage",
			Handler:    _GatewayService_DeleteMessage_Handler,
		},
		{
			MethodName: "PullInbox",
			Handler:    _GatewayService_PullInbox_Handler,
		},
		{
			MethodName: "AckDelivery",
			Handler:    _GatewayService_AckDelivery_Handler,
		},
		{
			MethodName: "MarkRead",
			Handler:    _GatewayService_MarkRead_Handler,
		},
		{
			MethodName: "GetReceiptState",
			Handler:    _GatewayService_GetReceiptState_Handler,
		},
		{
			MethodName: "ListReceiptStates",
			Handler:    _GatewayService_ListReceiptStates_Handler,
		},
		{
			MethodName: "ListConversations",
			Handler:    _GatewayService_ListConversations_Handler,
		},
		{
			MethodName: "ArchiveConversation",
			Handler:    _GatewayService_ArchiveConversation_Handler,
		},
		{
			MethodName: "PinConversation",
			Handler:    _GatewayService_PinConversation_Handler,
		},
		{
			MethodName: "MuteConversation",
			Handler:    _GatewayService_MuteConversation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nexusim/gateway/v1/gateway_service.proto",
}
